// Code generated by revogen. DO NOT EDIT.

package business

import (
	"context"
	"errors"
	"net/http"

	"github.com/greatliontech/revolut-go/internal/transport"
)

// Transfers groups the Transfers endpoints.
type Transfers struct {
	t *transport.Transport
}

// CreatePayment create a transfer to another account or card
//
// Docs: https://developer.revolut.com/docs/business/create-payment
// Required scopes: PAY, READ
func (s *Transfers) CreatePayment(ctx context.Context, req TransactionPaymentRequest) (*TransferResponse, error) {
	if req.AccountID == "" {
		return nil, errors.New("business: TransactionPaymentRequest.account_id is required")
	}
	if req.Amount == "" {
		return nil, errors.New("business: TransactionPaymentRequest.amount is required")
	}
	if req.Receiver.CounterpartyID == "" {
		return nil, errors.New("business: TransactionPaymentRequest.receiver.counterparty_id is required")
	}
	if req.RequestID == "" {
		return nil, errors.New("business: TransactionPaymentRequest.request_id is required")
	}
	var out TransferResponse
	if err := s.t.Do(ctx, http.MethodPost, "pay", req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Create move money between your accounts
//
// Docs: https://developer.revolut.com/docs/business/create-transfer
// Required scopes: PAY, READ
func (s *Transfers) Create(ctx context.Context, req TransferRequest) (*TransferResponse, error) {
	if req.Amount == "" {
		return nil, errors.New("business: TransferRequest.amount is required")
	}
	if req.Currency == "" {
		return nil, errors.New("business: TransferRequest.currency is required")
	}
	if req.RequestID == "" {
		return nil, errors.New("business: TransferRequest.request_id is required")
	}
	if req.SourceAccountID == "" {
		return nil, errors.New("business: TransferRequest.source_account_id is required")
	}
	if req.TargetAccountID == "" {
		return nil, errors.New("business: TransferRequest.target_account_id is required")
	}
	var out TransferResponse
	if err := s.t.Do(ctx, http.MethodPost, "transfer", req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetReasons get transfer reasons
//
// Docs: https://developer.revolut.com/docs/business/get-transfer-reasons
// Required scopes: READ
func (s *Transfers) GetReasons(ctx context.Context) ([]TransferReason, error) {
	var out []TransferReason
	if err := s.t.Do(ctx, http.MethodGet, "transfer-reasons", nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}
