// Code generated by revogen. DO NOT EDIT.

package business

import (
	"context"
	"errors"
	"iter"
	"net/http"
	"net/url"

	"github.com/greatliontech/revolut-go/internal/transport"
)

// Cards groups the Cards endpoints.
type Cards struct {
	t *transport.Transport
}

// List retrieve a list of cards
//
// Docs: https://developer.revolut.com/docs/business/get-cards
// Required scopes: READ
func (s *Cards) List(ctx context.Context, opts *GetCardsParams) ([]CardResponse, error) {
	path := "cards"
	if q := opts.encode().Encode(); q != "" {
		path += "?" + q
	}
	var out []CardResponse
	if err := s.t.Do(ctx, http.MethodGet, path, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// ListAll iterates every page of List, yielding one CardResponse per
// step. Break out of the loop to stop early.
func (s *Cards) ListAll(ctx context.Context, opts *GetCardsParams) iter.Seq2[CardResponse, error] {
	return func(yield func(CardResponse, error) bool) {
		var p GetCardsParams
		if opts != nil {
			p = *opts
		}
		for {
			if err := ctx.Err(); err != nil {
				var zero CardResponse
				yield(zero, err)
				return
			}
			resp, err := s.List(ctx, &p)
			if err != nil {
				var zero CardResponse
				yield(zero, err)
				return
			}
			if len(resp) == 0 {
				return
			}
			for _, item := range resp {
				if !yield(item, nil) {
					return
				}
			}
			nextAdv := resp[len(resp)-1].CreatedAt
			if nextAdv == p.CreatedBefore {
				return
			}
			p.CreatedBefore = nextAdv
		}
	}
}

// Create create a card
//
// Docs: https://developer.revolut.com/docs/business/create-card
// Required scopes: WRITE
func (s *Cards) Create(ctx context.Context, req CardsBody) (*CardCreatedResponse, error) {
	if len(req.ContactIds) > 0 && uint64(len(req.ContactIds)) < 1 {
		return nil, errors.New("business: CardsBody.contact_ids must contain at least 1 items")
	}
	if uint64(len(req.ContactIds)) > 5 {
		return nil, errors.New("business: CardsBody.contact_ids must contain at most 5 items")
	}
	if req.Label != "" && len(req.Label) > 30 {
		return nil, errors.New("business: CardsBody.label must be at most 30 characters")
	}
	if len(req.References) > 0 && uint64(len(req.References)) < 1 {
		return nil, errors.New("business: CardsBody.references must contain at least 1 items")
	}
	if uint64(len(req.References)) > 5 {
		return nil, errors.New("business: CardsBody.references must contain at most 5 items")
	}
	if req.RequestID == "" {
		return nil, errors.New("business: CardsBody.request_id is required")
	}
	if len(req.RequestID) > 40 {
		return nil, errors.New("business: CardsBody.request_id must be at most 40 characters")
	}
	var out CardCreatedResponse
	if err := s.t.Do(ctx, http.MethodPost, "cards", req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Get retrieve card details
//
// Docs: https://developer.revolut.com/docs/business/get-card
// Required scopes: READ
func (s *Cards) Get(ctx context.Context, cardID string) (*CardResponse, error) {
	if cardID == "" {
		return nil, errors.New("business: card_id is required")
	}
	if !isUUID(cardID) {
		return nil, errors.New("business: card_id must be a valid UUID")
	}
	var out CardResponse
	if err := s.t.Do(ctx, http.MethodGet, "cards/"+url.PathEscape(cardID), nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update update card settings
//
// Docs: https://developer.revolut.com/docs/business/update-card
// Required scopes: WRITE
func (s *Cards) Update(ctx context.Context, cardID string, req CardsBody) (*CardResponse, error) {
	if cardID == "" {
		return nil, errors.New("business: card_id is required")
	}
	if !isUUID(cardID) {
		return nil, errors.New("business: card_id must be a valid UUID")
	}
	if len(req.ContactIds) > 0 && uint64(len(req.ContactIds)) < 1 {
		return nil, errors.New("business: CardsBody.contact_ids must contain at least 1 items")
	}
	if uint64(len(req.ContactIds)) > 5 {
		return nil, errors.New("business: CardsBody.contact_ids must contain at most 5 items")
	}
	if req.Label != "" && len(req.Label) > 30 {
		return nil, errors.New("business: CardsBody.label must be at most 30 characters")
	}
	if len(req.References) > 0 && uint64(len(req.References)) < 1 {
		return nil, errors.New("business: CardsBody.references must contain at least 1 items")
	}
	if uint64(len(req.References)) > 5 {
		return nil, errors.New("business: CardsBody.references must contain at most 5 items")
	}
	if req.RequestID == "" {
		return nil, errors.New("business: CardsBody.request_id is required")
	}
	if len(req.RequestID) > 40 {
		return nil, errors.New("business: CardsBody.request_id must be at most 40 characters")
	}
	var out CardResponse
	if err := s.t.Do(ctx, http.MethodPatch, "cards/"+url.PathEscape(cardID), req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete terminate a card
//
// Docs: https://developer.revolut.com/docs/business/delete-card
// Required scopes: WRITE
func (s *Cards) Delete(ctx context.Context, cardID string) error {
	if cardID == "" {
		return errors.New("business: card_id is required")
	}
	if !isUUID(cardID) {
		return errors.New("business: card_id must be a valid UUID")
	}
	return s.t.Do(ctx, http.MethodDelete, "cards/"+url.PathEscape(cardID), nil, nil)
}

// UpdateContacts update card contacts
//
// Docs: https://developer.revolut.com/docs/business/update-card-contacts
// Required scopes: WRITE
func (s *Cards) UpdateContacts(ctx context.Context, cardID string, req []CardContact) ([]CardContact, error) {
	if cardID == "" {
		return nil, errors.New("business: card_id is required")
	}
	if !isUUID(cardID) {
		return nil, errors.New("business: card_id must be a valid UUID")
	}
	var out []CardContact
	if err := s.t.Do(ctx, http.MethodPut, "cards/"+url.PathEscape(cardID)+"/contacts", req, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// FreezeCard freeze a card
//
// Docs: https://developer.revolut.com/docs/business/freeze-card
// Required scopes: WRITE
func (s *Cards) FreezeCard(ctx context.Context, cardID string) error {
	if cardID == "" {
		return errors.New("business: card_id is required")
	}
	if !isUUID(cardID) {
		return errors.New("business: card_id must be a valid UUID")
	}
	return s.t.Do(ctx, http.MethodPost, "cards/"+url.PathEscape(cardID)+"/freeze", nil, nil)
}

// LockCard lock a card
//
// Docs: https://developer.revolut.com/docs/business/lock-card
// Required scopes: WRITE
func (s *Cards) LockCard(ctx context.Context, cardID string) error {
	if cardID == "" {
		return errors.New("business: card_id is required")
	}
	if !isUUID(cardID) {
		return errors.New("business: card_id must be a valid UUID")
	}
	return s.t.Do(ctx, http.MethodPost, "cards/"+url.PathEscape(cardID)+"/lock", nil, nil)
}

// UpdateReferences update card references
//
// Docs: https://developer.revolut.com/docs/business/update-card-references
// Required scopes: WRITE
func (s *Cards) UpdateReferences(ctx context.Context, cardID string, req []CardReference) ([]CardReference, error) {
	if cardID == "" {
		return nil, errors.New("business: card_id is required")
	}
	if !isUUID(cardID) {
		return nil, errors.New("business: card_id must be a valid UUID")
	}
	var out []CardReference
	if err := s.t.Do(ctx, http.MethodPut, "cards/"+url.PathEscape(cardID)+"/references", req, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// GetSensitiveCardDetails retrieve sensitive card details
//
// Docs: https://developer.revolut.com/docs/business/get-sensitive-card-details
// Required scopes: READ_SENSITIVE_CARD_DATA
func (s *Cards) GetSensitiveCardDetails(ctx context.Context, cardID string) (*GetSensitiveCardDetailsResponse, error) {
	if cardID == "" {
		return nil, errors.New("business: card_id is required")
	}
	if !isUUID(cardID) {
		return nil, errors.New("business: card_id must be a valid UUID")
	}
	var out GetSensitiveCardDetailsResponse
	if err := s.t.Do(ctx, http.MethodGet, "cards/"+url.PathEscape(cardID)+"/sensitive-details", nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// UnfreezeCard unfreeze a card
//
// Docs: https://developer.revolut.com/docs/business/unfreeze-card
// Required scopes: WRITE
func (s *Cards) UnfreezeCard(ctx context.Context, cardID string) error {
	if cardID == "" {
		return errors.New("business: card_id is required")
	}
	if !isUUID(cardID) {
		return errors.New("business: card_id must be a valid UUID")
	}
	return s.t.Do(ctx, http.MethodPost, "cards/"+url.PathEscape(cardID)+"/unfreeze", nil, nil)
}

// UnlockCard unlock a card
//
// Docs: https://developer.revolut.com/docs/business/unlock-card
// Required scopes: WRITE
func (s *Cards) UnlockCard(ctx context.Context, cardID string) error {
	if cardID == "" {
		return errors.New("business: card_id is required")
	}
	if !isUUID(cardID) {
		return errors.New("business: card_id must be a valid UUID")
	}
	return s.t.Do(ctx, http.MethodPost, "cards/"+url.PathEscape(cardID)+"/unlock", nil, nil)
}
