// Code generated by revogen. DO NOT EDIT.

package business

import (
	"context"
	"errors"
	"net/http"

	"github.com/greatliontech/revolut-go/internal/transport"
	"github.com/greatliontech/revolut-go/internal/validate"
)

// ForeignExchange groups the ForeignExchange endpoints.
type ForeignExchange struct {
	t *transport.Transport
}

// ExchangeMoney exchange money
//
// Exchange money using one of these methods:
//
//   - **Sell currency**: You know the amount of currency to sell.
//     For example, you want to exchange 135.5 USD to some EUR.
//
//     Specify the amount in the `from` object.
//
//   - **Buy currency**: You know the amount of currency to buy.
//     For example, you want to exchange some USD to 200 EUR.
//
//     Specify the amount in the `to` object.
//
// :::note
// You must specify the `amount` field only once, either in the `from` object or in the `to` object.
// :::
//
// You can check the [currencies supported in Production](https://help.revolut.com/business/help/receiving-payments/currency-exchanges/which-currencies-can-i-exchange-and-keep-in-my-account/) in the Revolut Help Centre.
// Some of these currencies might not be available in Sandbox.
//
// For more information, see the guides: [Exchange money](https://developer.revolut.com/docs/guides/manage-accounts/exchange-money).
//
// Docs: https://developer.revolut.com/docs/business/exchange-money
// Required scopes: PAY, READ
func (s *ForeignExchange) ExchangeMoney(ctx context.Context, req ExchangeRequest) (*ExchangeResponse, error) {
	if req.From.AccountID == "" {
		return nil, errors.New("business: ExchangeRequest.from.account_id is required")
	}
	if req.From.Currency == "" {
		return nil, errors.New("business: ExchangeRequest.from.currency is required")
	}
	if !validate.MatchPattern("^[A-Z]{3}$", string(req.From.Currency)) {
		return nil, errors.New("business: ExchangeRequest.from.currency must match pattern ^[A-Z]{3}$")
	}
	if req.RequestID == "" {
		return nil, errors.New("business: ExchangeRequest.request_id is required")
	}
	if len(req.RequestID) > 40 {
		return nil, errors.New("business: ExchangeRequest.request_id must be at most 40 characters")
	}
	if req.To.AccountID == "" {
		return nil, errors.New("business: ExchangeRequest.to.account_id is required")
	}
	if req.To.Currency == "" {
		return nil, errors.New("business: ExchangeRequest.to.currency is required")
	}
	if !validate.MatchPattern("^[A-Z]{3}$", string(req.To.Currency)) {
		return nil, errors.New("business: ExchangeRequest.to.currency must match pattern ^[A-Z]{3}$")
	}
	var out ExchangeResponse
	if err := s.t.Do(ctx, http.MethodPost, "exchange", req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetExchangeReasons get exchange reasons
//
// Depending on the country and the amount of funds to be exchanged, you might be required to provide an exchange reason.
// With this endpoint, you can retrieve all exchange reasons available to your business account.
//
// After you retrieve the results, use the appropriate reason code in the `exchange_reason_code` field when [exchanging money](https://developer.revolut.com/docs/business/exchange-money) or [making a payment](https://developer.revolut.com/docs/business/create-payment) that involves foreign currency exchange.
//
// Docs: https://developer.revolut.com/docs/business/get-exchange-reasons
// Required scopes: READ
func (s *ForeignExchange) GetExchangeReasons(ctx context.Context) ([]ExchangeReason, error) {
	var out []ExchangeReason
	if err := s.t.Do(ctx, http.MethodGet, "exchange-reasons", nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// GetRate get an exchange rate
//
// Get the sell exchange rate between two currencies.
//
// You can check the [currencies supported in Production](https://help.revolut.com/business/help/receiving-payments/currency-exchanges/which-currencies-can-i-exchange-and-keep-in-my-account/) in the Revolut Help Centre.
// Some of these currencies might not be available in Sandbox.
//
// For more information, see the guides: [Exchange money](https://developer.revolut.com/docs/guides/manage-accounts/exchange-money).
//
// Docs: https://developer.revolut.com/docs/business/get-rate
// Required scopes: READ
func (s *ForeignExchange) GetRate(ctx context.Context, opts *GetRateParams) (*ExchangeRateResponse, error) {
	if opts == nil {
		return nil, errors.New("business: GetRateParams is required")
	}
	if opts.From == "" {
		return nil, errors.New("business: GetRateParams.from is required")
	}
	if !validate.MatchPattern("^[A-Z]{3}$", string(opts.From)) {
		return nil, errors.New("business: GetRateParams.from must match pattern ^[A-Z]{3}$")
	}
	if opts.To == "" {
		return nil, errors.New("business: GetRateParams.to is required")
	}
	if !validate.MatchPattern("^[A-Z]{3}$", string(opts.To)) {
		return nil, errors.New("business: GetRateParams.to must match pattern ^[A-Z]{3}$")
	}
	path := "rate"
	if q := opts.encode().Encode(); q != "" {
		path += "?" + q
	}
	var out ExchangeRateResponse
	if err := s.t.Do(ctx, http.MethodGet, path, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
