// Code generated by revogen. DO NOT EDIT.

package business

import (
	"context"
	"errors"
	"iter"
	"net/http"
	"net/url"

	"github.com/greatliontech/revolut-go/internal/transport"
	"github.com/greatliontech/revolut-go/internal/validate"
)

// Accounting groups the Accounting endpoints.
type Accounting struct {
	t *transport.Transport
}

// GetCategories retrieve a list of accounting categories
//
// Get available accounting categories based on the provided query criteria.
//
// :::note
// The API returns a maximum of 500 accounting categories per request.
// The default page size is 100.
// :::
//
// The accounting categories are sorted by the `created_at` date in reverse chronological order, and they're **paginated**.
// The page size, that is, the maximum number of accounting categories returned per page is specified by the `limit` parameter.
//
//   - If the number of results exceeds the page size, the response also returns a cursor for the next page under `next_page_token`.
//     To get the next page of results, make a new request using that `next_page_token` value in `page_token`.
//
//   - If the number of results is smaller than the page size, `next_page_token` is not returned.
//
// For more details, see the guides: [Manage accounting settings](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-accounting-settings) and [Manage accounting categories](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-accounting-categories).
//
// Docs: https://developer.revolut.com/docs/business/get-accounting-categories
// Required scopes: READ
func (s *Accounting) GetCategories(ctx context.Context, opts *GetAccountingCategoriesParams) (*GetAccountingCategoriesResponse, error) {
	path := "accounting-categories"
	if q := opts.encode().Encode(); q != "" {
		path += "?" + q
	}
	var out GetAccountingCategoriesResponse
	if err := s.t.Do(ctx, http.MethodGet, path, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCategoriesAll iterates every page of GetCategories, yielding one AccountingCategoryResponse per
// step. Break out of the loop to stop early.
func (s *Accounting) GetCategoriesAll(ctx context.Context, opts *GetAccountingCategoriesParams) iter.Seq2[AccountingCategoryResponse, error] {
	return func(yield func(AccountingCategoryResponse, error) bool) {
		var p GetAccountingCategoriesParams
		if opts != nil {
			p = *opts
		}
		for {
			if err := ctx.Err(); err != nil {
				var zero AccountingCategoryResponse
				yield(zero, err)
				return
			}
			resp, err := s.GetCategories(ctx, &p)
			if err != nil {
				var zero AccountingCategoryResponse
				yield(zero, err)
				return
			}
			for _, item := range resp.AccountingCategories {
				if !yield(item, nil) {
					return
				}
			}
			if resp.NextPageToken == "" {
				return
			}
			nextTok := resp.NextPageToken
			if nextTok == p.PageToken {
				return
			}
			p.PageToken = nextTok
		}
	}
}

// CreateCategory create an accounting category
//
// Add a new accounting category to the list of accounting categories that can be assigned to your financial records, such as expenses.
//
// :::note
// This operation is not supported for [externally managed accounting categories](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-accounting-categories#externally-managed-settings).
// :::
//
// For more details, see the guides: [Manage accounting settings](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-accounting-settings) and [Manage accounting categories](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-accounting-categories).
//
// Docs: https://developer.revolut.com/docs/business/create-accounting-category
// Required scopes: WRITE
func (s *Accounting) CreateCategory(ctx context.Context, req CreateAccountingCategoryRequest) (*ResourceCreatedResponse, error) {
	if req.Code == "" {
		return nil, errors.New("business: CreateAccountingCategoryRequest.code is required")
	}
	if len(req.Code) < 1 {
		return nil, errors.New("business: CreateAccountingCategoryRequest.code must be at least 1 characters")
	}
	if len(req.Code) > 50 {
		return nil, errors.New("business: CreateAccountingCategoryRequest.code must be at most 50 characters")
	}
	if req.Name == "" {
		return nil, errors.New("business: CreateAccountingCategoryRequest.name is required")
	}
	if len(req.Name) < 1 {
		return nil, errors.New("business: CreateAccountingCategoryRequest.name must be at least 1 characters")
	}
	if len(req.Name) > 60 {
		return nil, errors.New("business: CreateAccountingCategoryRequest.name must be at most 60 characters")
	}
	var out ResourceCreatedResponse
	if err := s.t.Do(ctx, http.MethodPost, "accounting-categories", req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCategory retrieve accounting category details
//
// Get the details of a specific accounting category based on its ID.
//
// The details include the accounting category name, code, and default tax rate, as well as when the accounting category was added to your settings, and when it was last updated.
//
// For more details, see the guides: [Manage accounting settings](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-accounting-settings) and [Manage accounting categories](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-accounting-categories).
//
// Docs: https://developer.revolut.com/docs/business/get-accounting-category
// Required scopes: READ
func (s *Accounting) GetCategory(ctx context.Context, accountingCategoryID string) (*AccountingCategoryResponse, error) {
	if accountingCategoryID == "" {
		return nil, errors.New("business: accounting_category_id is required")
	}
	if !validate.IsUUID(accountingCategoryID) {
		return nil, errors.New("business: accounting_category_id must be a valid UUID")
	}
	var out AccountingCategoryResponse
	if err := s.t.Do(ctx, http.MethodGet, "accounting-categories/"+url.PathEscape(accountingCategoryID), nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateCategory update accounting category settings
//
// Update settings for a specific accounting category, based on its ID.
//
// :::note
// This operation is not supported for [externally managed accounting categories](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-accounting-categories#externally-managed-settings).
// :::
//
// For more details, see the guides: [Manage accounting settings](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-accounting-settings) and [Manage accounting categories](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-accounting-categories).
//
// Docs: https://developer.revolut.com/docs/business/update-accounting-category
// Required scopes: WRITE
func (s *Accounting) UpdateCategory(ctx context.Context, accountingCategoryID string, req UpdateAccountingCategoryRequest) error {
	if accountingCategoryID == "" {
		return errors.New("business: accounting_category_id is required")
	}
	if !validate.IsUUID(accountingCategoryID) {
		return errors.New("business: accounting_category_id must be a valid UUID")
	}
	if req.Code != "" && len(req.Code) < 1 {
		return errors.New("business: UpdateAccountingCategoryRequest.code must be at least 1 characters")
	}
	if req.Code != "" && len(req.Code) > 50 {
		return errors.New("business: UpdateAccountingCategoryRequest.code must be at most 50 characters")
	}
	if req.Name != "" && len(req.Name) < 1 {
		return errors.New("business: UpdateAccountingCategoryRequest.name must be at least 1 characters")
	}
	if req.Name != "" && len(req.Name) > 60 {
		return errors.New("business: UpdateAccountingCategoryRequest.name must be at most 60 characters")
	}
	return s.t.Do(ctx, http.MethodPatch, "accounting-categories/"+url.PathEscape(accountingCategoryID), req, nil)
}

// DeleteCategory delete an accounting category
//
// Delete a specific accounting category, based on its ID.
//
// :::note
// This operation is not supported for [externally managed accounting categories](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-accounting-categories#externally-managed-settings).
// :::
//
// Once the accounting category is deleted, it will not be returned by the API or in the Revolut Business app, and:
//
// - You will not be able to assign it to new financial records (e.g. expenses).
//
// - Existing records assigned to this category that have not been completed will be marked as invalid, and you'll need to reassign them to another category.
//
// - Completed records will not be affected by the change.
//
// A successful response does not get any content in return.
//
// For more details, see the guides: [Manage accounting settings](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-accounting-settings) and [Manage accounting categories](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-accounting-categories).
//
// Docs: https://developer.revolut.com/docs/business/delete-accounting-category
// Required scopes: WRITE
func (s *Accounting) DeleteCategory(ctx context.Context, accountingCategoryID string) error {
	if accountingCategoryID == "" {
		return errors.New("business: accounting_category_id is required")
	}
	if !validate.IsUUID(accountingCategoryID) {
		return errors.New("business: accounting_category_id must be a valid UUID")
	}
	return s.t.Do(ctx, http.MethodDelete, "accounting-categories/"+url.PathEscape(accountingCategoryID), nil, nil)
}

// GetLabelGroups retrieve a list of label groups
//
// Get available label groups based on the provided query criteria.
//
// The label groups are sorted by the `created_at` date in reverse chronological order, and they're **paginated**.
//
// For more details, see the guides: [Manage accounting settings](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-accounting-settings) and [Manage labels and label groups](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-labels-and-label-groups).
//
// Docs: https://developer.revolut.com/docs/business/get-label-groups
// Required scopes: READ
func (s *Accounting) GetLabelGroups(ctx context.Context, opts *GetLabelGroupsParams) (*GetLabelGroupsResponse, error) {
	path := "label-groups"
	if q := opts.encode().Encode(); q != "" {
		path += "?" + q
	}
	var out GetLabelGroupsResponse
	if err := s.t.Do(ctx, http.MethodGet, path, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetLabelGroupsAll iterates every page of GetLabelGroups, yielding one LabelGroupResponse per
// step. Break out of the loop to stop early.
func (s *Accounting) GetLabelGroupsAll(ctx context.Context, opts *GetLabelGroupsParams) iter.Seq2[LabelGroupResponse, error] {
	return func(yield func(LabelGroupResponse, error) bool) {
		var p GetLabelGroupsParams
		if opts != nil {
			p = *opts
		}
		for {
			if err := ctx.Err(); err != nil {
				var zero LabelGroupResponse
				yield(zero, err)
				return
			}
			resp, err := s.GetLabelGroups(ctx, &p)
			if err != nil {
				var zero LabelGroupResponse
				yield(zero, err)
				return
			}
			for _, item := range resp.LabelGroups {
				if !yield(item, nil) {
					return
				}
			}
			if resp.NextPageToken == "" {
				return
			}
			nextTok := resp.NextPageToken
			if nextTok == p.PageToken {
				return
			}
			p.PageToken = nextTok
		}
	}
}

// CreateLabelGroup create a new label group
//
// Add a new group of labels that can be applied to your financial records, such as expenses.
//
// :::note
//
// - This operation is not supported for [externally managed label groups](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-labels-and-label-groups#externally-managed-settings).
//
// - You can have up to 5 label groups at a time per business.
// :::
//
// For more details, see the guides: [Manage accounting settings](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-accounting-settings) and [Manage labels and label groups](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-labels-and-label-groups).
//
// Docs: https://developer.revolut.com/docs/business/create-label-group
// Required scopes: WRITE
func (s *Accounting) CreateLabelGroup(ctx context.Context, req CreateLabelGroupRequest) (*ResourceCreatedResponse, error) {
	if len(req.Labels) == 0 {
		return nil, errors.New("business: CreateLabelGroupRequest.labels is required")
	}
	if len(req.Labels) > 0 && uint64(len(req.Labels)) < 1 {
		return nil, errors.New("business: CreateLabelGroupRequest.labels must contain at least 1 items")
	}
	if uint64(len(req.Labels)) < 1 {
		return nil, errors.New("business: CreateLabelGroupRequest.labels must contain at least 1 items")
	}
	if uint64(len(req.Labels)) > 200 {
		return nil, errors.New("business: CreateLabelGroupRequest.labels must contain at most 200 items")
	}
	if req.Name == "" {
		return nil, errors.New("business: CreateLabelGroupRequest.name is required")
	}
	if len(req.Name) < 1 {
		return nil, errors.New("business: CreateLabelGroupRequest.name must be at least 1 characters")
	}
	if len(req.Name) > 100 {
		return nil, errors.New("business: CreateLabelGroupRequest.name must be at most 100 characters")
	}
	var out ResourceCreatedResponse
	if err := s.t.Do(ctx, http.MethodPost, "label-groups", req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetLabelGroup retrieve label group details
//
// Get the details of a specific label group based on the label group ID.
//
// The details include the label group name, as well as when the label group was added to your settings, and when it was last updated.
//
// For more details, see the guides: [Manage accounting settings](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-accounting-settings) and [Manage labels and label groups](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-labels-and-label-groups).
//
// Docs: https://developer.revolut.com/docs/business/get-label-group
// Required scopes: READ
func (s *Accounting) GetLabelGroup(ctx context.Context, groupID string) (*LabelGroupResponse, error) {
	if groupID == "" {
		return nil, errors.New("business: group_id is required")
	}
	if !validate.IsUUID(groupID) {
		return nil, errors.New("business: group_id must be a valid UUID")
	}
	var out LabelGroupResponse
	if err := s.t.Do(ctx, http.MethodGet, "label-groups/"+url.PathEscape(groupID), nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateLabelGroup update label group settings
//
// Update the name for a specific label group, based on its ID.
//
// :::note
// This operation is not supported for [externally managed label groups](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-labels-and-label-groups#externally-managed-settings).
// :::
//
// For more details, see the guides: [Manage accounting settings](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-accounting-settings) and [Manage labels and label groups](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-labels-and-label-groups).
//
// Docs: https://developer.revolut.com/docs/business/update-label-group
// Required scopes: WRITE
func (s *Accounting) UpdateLabelGroup(ctx context.Context, groupID string, req UpdateLabelGroupRequest) error {
	if groupID == "" {
		return errors.New("business: group_id is required")
	}
	if !validate.IsUUID(groupID) {
		return errors.New("business: group_id must be a valid UUID")
	}
	if req.Name == "" {
		return errors.New("business: UpdateLabelGroupRequest.name is required")
	}
	if len(req.Name) < 1 {
		return errors.New("business: UpdateLabelGroupRequest.name must be at least 1 characters")
	}
	if len(req.Name) > 100 {
		return errors.New("business: UpdateLabelGroupRequest.name must be at most 100 characters")
	}
	return s.t.Do(ctx, http.MethodPatch, "label-groups/"+url.PathEscape(groupID), req, nil)
}

// DeleteLabelGroup delete a label group
//
// Delete a specific label group, based on its ID.
//
// :::note
// This operation is not supported for [externally managed label groups](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-labels-and-label-groups#externally-managed-settings).
// :::
//
// Once the label group is deleted, it will not be returned by the API or in the Revolut Business app, and:
//
// - You will not be able to apply labels from the group to new financial records (e.g. expenses).
//
// - Existing records that have not been completed and that contain labels from this group will be marked as invalid, and you'll need to update them to use different labels.
//
// - Completed records will not be affected by the change.
//
// A successful response does not get any content in return.
//
// For more details, see the guides: [Manage accounting settings](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-accounting-settings) and [Manage labels and label groups](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-labels-and-label-groups).
//
// Docs: https://developer.revolut.com/docs/business/delete-label-group
// Required scopes: WRITE
func (s *Accounting) DeleteLabelGroup(ctx context.Context, groupID string) error {
	if groupID == "" {
		return errors.New("business: group_id is required")
	}
	if !validate.IsUUID(groupID) {
		return errors.New("business: group_id must be a valid UUID")
	}
	return s.t.Do(ctx, http.MethodDelete, "label-groups/"+url.PathEscape(groupID), nil, nil)
}

// GetLabels retrieve a list of labels from a label group
//
// Get labels from a specific label group based on the provided query criteria.
//
// :::note
// The API returns a maximum of 500 labels per request.
// The default page size is 100.
// :::
//
// The labels are sorted by the `created_at` date in reverse chronological order, and they're **paginated**.
// The page size, that is, the maximum number of labels returned per page is specified by the `limit` parameter.
//
//   - If the number of results exceeds the page size, the response also returns a cursor for the next page under `next_page_token`.
//     To get the next page of results, make a new request using that `next_page_token` value in `page_token`.
//
//   - If the number of results is smaller than the page size, `next_page_token` is not returned.
//
// For more details, see the guides: [Manage accounting settings](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-accounting-settings) and [Manage labels and label groups](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-labels-and-label-groups).
//
// Docs: https://developer.revolut.com/docs/business/get-labels
// Required scopes: READ
func (s *Accounting) GetLabels(ctx context.Context, groupID string, opts *GetLabelsParams) (*GetLabelsResponse, error) {
	if groupID == "" {
		return nil, errors.New("business: group_id is required")
	}
	if !validate.IsUUID(groupID) {
		return nil, errors.New("business: group_id must be a valid UUID")
	}
	path := "label-groups/" + url.PathEscape(groupID) + "/labels"
	if q := opts.encode().Encode(); q != "" {
		path += "?" + q
	}
	var out GetLabelsResponse
	if err := s.t.Do(ctx, http.MethodGet, path, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetLabelsAll iterates every page of GetLabels, yielding one LabelResponse per
// step. Break out of the loop to stop early.
func (s *Accounting) GetLabelsAll(ctx context.Context, groupID string, opts *GetLabelsParams) iter.Seq2[LabelResponse, error] {
	return func(yield func(LabelResponse, error) bool) {
		var p GetLabelsParams
		if opts != nil {
			p = *opts
		}
		if groupID == "" {
			var zero LabelResponse
			yield(zero, errors.New("business: groupID is required"))
			return
		}
		for {
			if err := ctx.Err(); err != nil {
				var zero LabelResponse
				yield(zero, err)
				return
			}
			resp, err := s.GetLabels(ctx, groupID, &p)
			if err != nil {
				var zero LabelResponse
				yield(zero, err)
				return
			}
			for _, item := range resp.Labels {
				if !yield(item, nil) {
					return
				}
			}
			if resp.NextPageToken == "" {
				return
			}
			nextTok := resp.NextPageToken
			if nextTok == p.PageToken {
				return
			}
			p.PageToken = nextTok
		}
	}
}

// CreateLabel create a new label
//
// Add a new label to a label group.
//
// :::note
// This operation is not supported for [externally managed labels](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-labels-and-label-groups#externally-managed-settings).
// :::
//
// The labels are used for accounting and can be applied to your financial records, such as expenses.
//
// For more details, see the guides: [Manage accounting settings](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-accounting-settings) and [Manage labels and label groups](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-labels-and-label-groups).
//
// Docs: https://developer.revolut.com/docs/business/create-label
// Required scopes: WRITE
func (s *Accounting) CreateLabel(ctx context.Context, groupID string, req CreateLabelRequest) (*ResourceCreatedResponse, error) {
	if groupID == "" {
		return nil, errors.New("business: group_id is required")
	}
	if !validate.IsUUID(groupID) {
		return nil, errors.New("business: group_id must be a valid UUID")
	}
	if req.Name == "" {
		return nil, errors.New("business: CreateLabelRequest.name is required")
	}
	if len(req.Name) < 1 {
		return nil, errors.New("business: CreateLabelRequest.name must be at least 1 characters")
	}
	if len(req.Name) > 100 {
		return nil, errors.New("business: CreateLabelRequest.name must be at most 100 characters")
	}
	var out ResourceCreatedResponse
	if err := s.t.Do(ctx, http.MethodPost, "label-groups/"+url.PathEscape(groupID)+"/labels", req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateLabel update a label
//
// Update the name for a specific label, based on the IDs of the label and its label group.
//
// :::note
// This operation is not supported for [externally managed labels]/docs/guides/manage-accounts/accounting/manage-labels-and-label-groups(#externally-managed-settings).
// :::
//
// For more details, see the guides: [Manage accounting settings](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-accounting-settings) and [Manage labels and label groups](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-labels-and-label-groups).
//
// Docs: https://developer.revolut.com/docs/business/update-label
// Required scopes: WRITE
func (s *Accounting) UpdateLabel(ctx context.Context, groupID string, labelID string, req UpdateLabelRequest) error {
	if groupID == "" {
		return errors.New("business: group_id is required")
	}
	if !validate.IsUUID(groupID) {
		return errors.New("business: group_id must be a valid UUID")
	}
	if labelID == "" {
		return errors.New("business: label_id is required")
	}
	if !validate.IsUUID(labelID) {
		return errors.New("business: label_id must be a valid UUID")
	}
	if req.Name == "" {
		return errors.New("business: UpdateLabelRequest.name is required")
	}
	if len(req.Name) < 1 {
		return errors.New("business: UpdateLabelRequest.name must be at least 1 characters")
	}
	if len(req.Name) > 100 {
		return errors.New("business: UpdateLabelRequest.name must be at most 100 characters")
	}
	return s.t.Do(ctx, http.MethodPatch, "label-groups/"+url.PathEscape(groupID)+"/labels/"+url.PathEscape(labelID), req, nil)
}

// DeleteLabel delete a label
//
// Delete a specific label, based on the IDs of the label and its label group.
//
// :::note
// This operation is not supported for [externally managed labels](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-labels-and-label-groups#externally-managed-settings).
// :::
//
// Once the label is deleted, it will not be returned by the API or in the Revolut Business app, and:
//
// - You will not be able to apply it to new financial records (e.g. expenses).
//
// - Existing records with this label that have not been completed will be marked as invalid, and you'll need to update them to use a different label.
//
// - Completed records will not be affected by the change.
//
// A successful response does not get any content in return.
//
// For more details, see the guides: [Manage accounting settings](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-accounting-settings) and [Manage labels and label groups](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-labels-and-label-groups).
//
// Docs: https://developer.revolut.com/docs/business/delete-label
// Required scopes: WRITE
func (s *Accounting) DeleteLabel(ctx context.Context, groupID string, labelID string) error {
	if groupID == "" {
		return errors.New("business: group_id is required")
	}
	if !validate.IsUUID(groupID) {
		return errors.New("business: group_id must be a valid UUID")
	}
	if labelID == "" {
		return errors.New("business: label_id is required")
	}
	if !validate.IsUUID(labelID) {
		return errors.New("business: label_id must be a valid UUID")
	}
	return s.t.Do(ctx, http.MethodDelete, "label-groups/"+url.PathEscape(groupID)+"/labels/"+url.PathEscape(labelID), nil, nil)
}

// GetTaxRates retrieve a list of tax rates
//
// Get available tax rates based on the provided query criteria.
//
// :::note
// The API returns a maximum of 500 tax rates per request.
// The default page size is 100.
// :::
//
// The tax rates are sorted by the `created_at` date in reverse chronological order, and they're **paginated**.
// The page size, that is, the maximum number of tax rates returned per page is specified by the `limit` parameter.
//
//   - If the number of results exceeds the page size, the response also returns a cursor for the next page under `next_page_token`.
//     To get the next page of results, make a new request using that `next_page_token` value in `page_token`.
//
//   - If the number of results is smaller than the page size, `next_page_token` is not returned.
//
// For more details, see the guides: [Manage accounting settings](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-accounting-settings) and [Manage tax rates](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-tax-rates).
//
// Docs: https://developer.revolut.com/docs/business/get-tax-rates
// Required scopes: READ
func (s *Accounting) GetTaxRates(ctx context.Context, opts *GetTaxRatesParams) (*GetTaxRatesResponse, error) {
	path := "tax-rates"
	if q := opts.encode().Encode(); q != "" {
		path += "?" + q
	}
	var out GetTaxRatesResponse
	if err := s.t.Do(ctx, http.MethodGet, path, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetTaxRatesAll iterates every page of GetTaxRates, yielding one TaxRateResponse per
// step. Break out of the loop to stop early.
func (s *Accounting) GetTaxRatesAll(ctx context.Context, opts *GetTaxRatesParams) iter.Seq2[TaxRateResponse, error] {
	return func(yield func(TaxRateResponse, error) bool) {
		var p GetTaxRatesParams
		if opts != nil {
			p = *opts
		}
		for {
			if err := ctx.Err(); err != nil {
				var zero TaxRateResponse
				yield(zero, err)
				return
			}
			resp, err := s.GetTaxRates(ctx, &p)
			if err != nil {
				var zero TaxRateResponse
				yield(zero, err)
				return
			}
			for _, item := range resp.TaxRates {
				if !yield(item, nil) {
					return
				}
			}
			if resp.NextPageToken == "" {
				return
			}
			nextTok := resp.NextPageToken
			if nextTok == p.PageToken {
				return
			}
			p.PageToken = nextTok
		}
	}
}

// CreateTaxRate create a new tax rate
//
// Add a new tax rate to the list of tax rates that can be applied to your financial records, such as expenses.
//
// :::note
// This operation is not supported for [externally managed tax rates](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-tax-rates#externally-managed-settings).
// :::
//
// For more details, see the guides: [Manage accounting settings](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-accounting-settings) and [Manage tax rates](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-tax-rates).
//
// Docs: https://developer.revolut.com/docs/business/create-tax-rate
// Required scopes: WRITE
func (s *Accounting) CreateTaxRate(ctx context.Context, req CreateTaxRateRequest) (*ResourceCreatedResponse, error) {
	if req.Name == "" {
		return nil, errors.New("business: CreateTaxRateRequest.name is required")
	}
	if len(req.Name) < 1 {
		return nil, errors.New("business: CreateTaxRateRequest.name must be at least 1 characters")
	}
	if len(req.Name) > 20 {
		return nil, errors.New("business: CreateTaxRateRequest.name must be at most 20 characters")
	}
	if req.Percentage == "" {
		return nil, errors.New("business: CreateTaxRateRequest.percentage is required")
	}
	if validate.NumberAsFloat(req.Percentage) < 0 {
		return nil, errors.New("business: CreateTaxRateRequest.percentage must be at minimum 0")
	}
	if validate.NumberAsFloat(req.Percentage) > 100 {
		return nil, errors.New("business: CreateTaxRateRequest.percentage must be at maximum 100")
	}
	var out ResourceCreatedResponse
	if err := s.t.Do(ctx, http.MethodPost, "tax-rates", req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetTaxRate retrieve tax rate details
//
// Get the details of a specific tax rate based on the tax rate ID.
//
// The details include the tax rate name and percentage, as well as when the tax rate was added to your settings, and when it was last updated.
//
// For more details, see the guides: [Manage accounting settings](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-accounting-settings) and [Manage tax rates](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-tax-rates).
//
// Docs: https://developer.revolut.com/docs/business/get-tax-rate
// Required scopes: READ
func (s *Accounting) GetTaxRate(ctx context.Context, taxRateID string) (*TaxRateResponse, error) {
	if taxRateID == "" {
		return nil, errors.New("business: tax_rate_id is required")
	}
	if !validate.IsUUID(taxRateID) {
		return nil, errors.New("business: tax_rate_id must be a valid UUID")
	}
	var out TaxRateResponse
	if err := s.t.Do(ctx, http.MethodGet, "tax-rates/"+url.PathEscape(taxRateID), nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateTaxRate update tax rate settings
//
// Update settings for a specific tax rate, based on its ID.
//
// :::note
// This operation is not supported for [externally managed tax rates](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-tax-rates#externally-managed-settings).
// :::
//
// For more details, see the guides: [Manage accounting settings](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-accounting-settings) and [Manage tax rates](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-tax-rates).
//
// Docs: https://developer.revolut.com/docs/business/update-tax-rate
// Required scopes: WRITE
func (s *Accounting) UpdateTaxRate(ctx context.Context, taxRateID string, req UpdateTaxRateRequest) error {
	if taxRateID == "" {
		return errors.New("business: tax_rate_id is required")
	}
	if !validate.IsUUID(taxRateID) {
		return errors.New("business: tax_rate_id must be a valid UUID")
	}
	if req.Name != "" && len(req.Name) < 1 {
		return errors.New("business: UpdateTaxRateRequest.name must be at least 1 characters")
	}
	if req.Name != "" && len(req.Name) > 20 {
		return errors.New("business: UpdateTaxRateRequest.name must be at most 20 characters")
	}
	return s.t.Do(ctx, http.MethodPatch, "tax-rates/"+url.PathEscape(taxRateID), req, nil)
}

// DeleteTaxRate delete a tax rate
//
// Delete a specific tax rate, based on its ID.
//
// :::note
// This operation is not supported for [externally managed tax rates](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-tax-rates#externally-managed-settings).
// :::
//
// Once the tax rate is deleted, it will not be returned by the API or in the Revolut Business app, and:
//
// - You will not be able to apply it to new financial records (e.g. expenses).
//
// - Existing records with this tax rate that have not been completed will be marked as invalid, and you'll need to update them to use a different tax rate.
//
// - Completed records will not be affected by the change.
//
// A successful response does not get any content in return.
//
// For more details, see the guides: [Manage accounting settings](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-accounting-settings) and [Manage tax rates](https://developer.revolut.com/docs/guides/manage-accounts/accounting/manage-tax-rates).
//
// Docs: https://developer.revolut.com/docs/business/delete-tax-rate
// Required scopes: WRITE
func (s *Accounting) DeleteTaxRate(ctx context.Context, taxRateID string) error {
	if taxRateID == "" {
		return errors.New("business: tax_rate_id is required")
	}
	if !validate.IsUUID(taxRateID) {
		return errors.New("business: tax_rate_id must be a valid UUID")
	}
	return s.t.Do(ctx, http.MethodDelete, "tax-rates/"+url.PathEscape(taxRateID), nil, nil)
}
