// Code generated by revogen. DO NOT EDIT.

package business

import (
	"context"
	"errors"
	"net/http"
	"net/url"

	"github.com/greatliontech/revolut-go/internal/transport"
)

// Accounts groups the Accounts endpoints.
type Accounts struct {
	t *transport.Transport
}

// List retrieve all accounts
//
// Docs: https://developer.revolut.com/docs/business/get-accounts
func (s *Accounts) List(ctx context.Context) ([]Account, error) {
	var out []Account
	if err := s.t.Do(ctx, http.MethodGet, "accounts", nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Get retrieve an account
//
// Docs: https://developer.revolut.com/docs/business/get-account
func (s *Accounts) Get(ctx context.Context, accountID string) (*Account, error) {
	if accountID == "" {
		return nil, errors.New("business: account_id is required")
	}
	var out Account
	if err := s.t.Do(ctx, http.MethodGet, "accounts/"+url.PathEscape(accountID), nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListBankDetails retrieve account's full bank details
//
// Docs: https://developer.revolut.com/docs/business/get-account-details
func (s *Accounts) ListBankDetails(ctx context.Context, accountID string) ([]AccountBankDetailsItem, error) {
	if accountID == "" {
		return nil, errors.New("business: account_id is required")
	}
	var out []AccountBankDetailsItem
	if err := s.t.Do(ctx, http.MethodGet, "accounts/"+url.PathEscape(accountID)+"/bank-details", nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}
