// Code generated by revogen. DO NOT EDIT.

package business

import (
	"context"
	"errors"
	"net/http"
	"net/url"

	"github.com/greatliontech/revolut-go/internal/transport"
)

// CardInvitations groups the CardInvitations endpoints.
type CardInvitations struct {
	t *transport.Transport
}

// List retrieve a list of card invitations
//
// Docs: https://developer.revolut.com/docs/business/get-card-invitations
func (s *CardInvitations) List(ctx context.Context) ([][]CardInvitationResponse, error) {
	var out [][]CardInvitationResponse
	if err := s.t.Do(ctx, http.MethodGet, "card-invitations", nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Create create a card invitation
//
// Docs: https://developer.revolut.com/docs/business/create-card-invitation
func (s *CardInvitations) Create(ctx context.Context) (*CardInvitationCreatedResponse, error) {
	var out CardInvitationCreatedResponse
	if err := s.t.Do(ctx, http.MethodPost, "card-invitations", nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Cancel cancel a card invitation
//
// Docs: https://developer.revolut.com/docs/business/cancel-card-invitation
func (s *CardInvitations) Cancel(ctx context.Context, cardInvitationID string) error {
	if cardInvitationID == "" {
		return errors.New("business: card_invitation_id is required")
	}
	return s.t.Do(ctx, http.MethodPost, "card-invitations/"+"{cardInvitationId}"+"/cancel", nil, nil)
}

// Get retrieve card invitation details
//
// Docs: https://developer.revolut.com/docs/business/get-card-invitation
func (s *CardInvitations) Get(ctx context.Context, cardInvitationID string) (*CardInvitationResponse, error) {
	if cardInvitationID == "" {
		return nil, errors.New("business: card_invitation_id is required")
	}
	var out CardInvitationResponse
	if err := s.t.Do(ctx, http.MethodGet, "card-invitations/"+url.PathEscape(cardInvitationID), nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update update card invitation settings
//
// Docs: https://developer.revolut.com/docs/business/update-card-invitation
func (s *CardInvitations) Update(ctx context.Context, cardInvitationID string) (*CardInvitationUpdatedResponse, error) {
	if cardInvitationID == "" {
		return nil, errors.New("business: card_invitation_id is required")
	}
	var out CardInvitationUpdatedResponse
	if err := s.t.Do(ctx, http.MethodPatch, "card-invitations/"+url.PathEscape(cardInvitationID), nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
