// Code generated by revogen. DO NOT EDIT.

package business

import (
	"context"
	"errors"
	"net/http"
	"net/url"

	"github.com/greatliontech/revolut-go/internal/transport"
)

// PaymentDrafts groups the PaymentDrafts endpoints.
type PaymentDrafts struct {
	t *transport.Transport
}

// List retrieve a list of payment drafts
//
// Docs: https://developer.revolut.com/docs/business/get-payment-drafts
// Required scopes: READ
func (s *PaymentDrafts) List(ctx context.Context) (*PaymentDraftsResponse, error) {
	var out PaymentDraftsResponse
	if err := s.t.Do(ctx, http.MethodGet, "payment-drafts", nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Create create a payment draft
//
// Docs: https://developer.revolut.com/docs/business/create-payment-draft
// Required scopes: READ, WRITE
func (s *PaymentDrafts) Create(ctx context.Context, req CreatePaymentDraftRequest) (*CreatePaymentDraftResponse, error) {
	if len(req.Payments) == 0 {
		return nil, errors.New("business: CreatePaymentDraftRequest.payments is required")
	}
	var out CreatePaymentDraftResponse
	if err := s.t.Do(ctx, http.MethodPost, "payment-drafts", req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Get retrieve a payment draft
//
// Docs: https://developer.revolut.com/docs/business/get-payment-draft
// Required scopes: READ
func (s *PaymentDrafts) Get(ctx context.Context, paymentDraftID string) (*PaymentDraftResponse, error) {
	if paymentDraftID == "" {
		return nil, errors.New("business: payment_draft_id is required")
	}
	var out PaymentDraftResponse
	if err := s.t.Do(ctx, http.MethodGet, "payment-drafts/"+url.PathEscape(paymentDraftID), nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete delete a payment draft
//
// Docs: https://developer.revolut.com/docs/business/delete-payment-draft
// Required scopes: READ, WRITE
func (s *PaymentDrafts) Delete(ctx context.Context, paymentDraftID string) error {
	if paymentDraftID == "" {
		return errors.New("business: payment_draft_id is required")
	}
	return s.t.Do(ctx, http.MethodDelete, "payment-drafts/"+url.PathEscape(paymentDraftID), nil, nil)
}
