// Code generated by revogen. DO NOT EDIT.

package business

import (
	"context"
	"errors"
	"iter"
	"net/http"
	"net/url"

	"github.com/greatliontech/revolut-go/internal/transport"
)

// TeamMembers groups the TeamMembers endpoints.
type TeamMembers struct {
	t *transport.Transport
}

// GetRoles retrieve team roles
//
// Get the list of roles for your business.
//
// The results are paginated and sorted by the `created_at` date in reverse chronological order.
//
// For more information, see the guides: [Manage team members](https://developer.revolut.com/docs/guides/manage-accounts/teams/manage-team-members).
//
// Docs: https://developer.revolut.com/docs/business/get-roles
// Required scopes: READ
func (s *TeamMembers) GetRoles(ctx context.Context, opts *GetRolesParams) ([]Role, error) {
	path := "roles"
	if q := opts.encode().Encode(); q != "" {
		path += "?" + q
	}
	var out []Role
	if err := s.t.Do(ctx, http.MethodGet, path, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// GetRolesAll iterates every page of GetRoles, yielding one Role per
// step. Break out of the loop to stop early.
func (s *TeamMembers) GetRolesAll(ctx context.Context, opts *GetRolesParams) iter.Seq2[Role, error] {
	return func(yield func(Role, error) bool) {
		var p GetRolesParams
		if opts != nil {
			p = *opts
		}
		for {
			if err := ctx.Err(); err != nil {
				var zero Role
				yield(zero, err)
				return
			}
			resp, err := s.GetRoles(ctx, &p)
			if err != nil {
				var zero Role
				yield(zero, err)
				return
			}
			if len(resp) == 0 {
				return
			}
			for _, item := range resp {
				if !yield(item, nil) {
					return
				}
			}
			nextAdv := resp[len(resp)-1].CreatedAt
			if nextAdv == p.CreatedBefore {
				return
			}
			p.CreatedBefore = nextAdv
		}
	}
}

// List retrieve a list of team members
//
// Get information about all the team members of your business.
//
// The results are paginated and sorted by the `created_at` date in reverse chronological order.
//
// For more information, see the guides: [Manage team members](https://developer.revolut.com/docs/guides/manage-accounts/teams/manage-team-members).
//
// Docs: https://developer.revolut.com/docs/business/get-team-members
// Required scopes: READ
func (s *TeamMembers) List(ctx context.Context, opts *GetTeamMembersParams) ([]TeamMember, error) {
	path := "team-members"
	if q := opts.encode().Encode(); q != "" {
		path += "?" + q
	}
	var out []TeamMember
	if err := s.t.Do(ctx, http.MethodGet, path, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// ListAll iterates every page of List, yielding one TeamMember per
// step. Break out of the loop to stop early.
func (s *TeamMembers) ListAll(ctx context.Context, opts *GetTeamMembersParams) iter.Seq2[TeamMember, error] {
	return func(yield func(TeamMember, error) bool) {
		var p GetTeamMembersParams
		if opts != nil {
			p = *opts
		}
		for {
			if err := ctx.Err(); err != nil {
				var zero TeamMember
				yield(zero, err)
				return
			}
			resp, err := s.List(ctx, &p)
			if err != nil {
				var zero TeamMember
				yield(zero, err)
				return
			}
			if len(resp) == 0 {
				return
			}
			for _, item := range resp {
				if !yield(item, nil) {
					return
				}
			}
			nextAdv := resp[len(resp)-1].CreatedAt
			if nextAdv == p.CreatedBefore {
				return
			}
			p.CreatedBefore = nextAdv
		}
	}
}

// InviteTeamMember invite a new member to your business
//
// Invite a new member to your business account.
//
// When you invite a new team member to your business account, an invitation is sent to their email address that you provided in this request.
// To join your business account, the new team member has to accept this invitation.
//
// For more information, see the guides: [Manage team members](https://developer.revolut.com/docs/guides/manage-accounts/teams/manage-team-members).
//
// Docs: https://developer.revolut.com/docs/business/invite-team-member
// Required scopes: WRITE
func (s *TeamMembers) InviteTeamMember(ctx context.Context, req TeamMembersBody) (*InviteTeamMemberResponse, error) {
	if req.Email == "" {
		return nil, errors.New("business: TeamMembersBody.email is required")
	}
	if req.RoleID == "" {
		return nil, errors.New("business: TeamMembersBody.role_id is required")
	}
	var out InviteTeamMemberResponse
	if err := s.t.Do(ctx, http.MethodPost, "team-members", req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete delete a team member
//
// Delete a specific member of your team.
//
// :::note
// This action does not delete the person’s Revolut Business user account – it only removes them from your team.
// They will lose access to your Revolut Business account and team but can still log in to Revolut Business.
// Their user account will remain linked to any other teams and accounts it’s associated with.
// :::
//
// For more information, see the guides: [Manage team members](https://developer.revolut.com/docs/guides/manage-accounts/teams/manage-team-members).
//
// Docs: https://developer.revolut.com/docs/business/delete-team-member
// Required scopes: WRITE
func (s *TeamMembers) Delete(ctx context.Context, teamMemberID string) error {
	if teamMemberID == "" {
		return errors.New("business: team_member_id is required")
	}
	if !isUUID(teamMemberID) {
		return errors.New("business: team_member_id must be a valid UUID")
	}
	return s.t.Do(ctx, http.MethodDelete, "team-members/"+url.PathEscape(teamMemberID), nil, nil)
}
