// Code generated by revogen. DO NOT EDIT.

package business

import (
	"context"
	"errors"
	"iter"
	"net/http"
	"net/url"

	"github.com/greatliontech/revolut-go/internal/transport"
)

// WebhooksV2 groups the WebhooksV2 endpoints.
type WebhooksV2 struct {
	t *transport.Transport
}

// List retrieve a list of webhooks
//
// Get the list of all your existing webhooks and their details.
//
// For more information, see the guides: [About webhooks](https://developer.revolut.com/docs/guides/manage-accounts/webhooks/about-webhooks) and [Manage webhooks](https://developer.revolut.com/docs/guides/manage-accounts/webhooks/manage-webhooks#retrieve-a-list-of-webhooks).
//
// Docs: https://developer.revolut.com/docs/business/get-webhooks
// Required scopes: READ
func (s *WebhooksV2) List(ctx context.Context) ([]WebhookV2Basic, error) {
	var out []WebhookV2Basic
	if err := s.t.Do(ctx, http.MethodGet, "https://b2b.revolut.com/api/2.0/"+"webhooks", nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Create create a new webhook
//
// Create a new webhook to receive event notifications to the specified URL. Provide a list of event types that you want to subscribe to and a URL for the webhook.
// Only HTTPS URLs are supported.
//
// For more information, see the guides: [About webhooks](https://developer.revolut.com/docs/guides/manage-accounts/webhooks/about-webhooks) and [Manage webhooks](https://developer.revolut.com/docs/guides/manage-accounts/webhooks/manage-webhooks#create-a-webhook).
//
// Docs: https://developer.revolut.com/docs/business/create-webhook
// Required scopes: WRITE
func (s *WebhooksV2) Create(ctx context.Context, req CreateWebhookRequest) (*WebhookV2, error) {
	if req.URL == "" {
		return nil, errors.New("business: CreateWebhookRequest.url is required")
	}
	var out WebhookV2
	if err := s.t.Do(ctx, http.MethodPost, "https://b2b.revolut.com/api/2.0/"+"webhooks", req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Get retrieve a webhook
//
// Get the information about a specific webhook by ID.
//
// For more information, see the guides: [About webhooks](https://developer.revolut.com/docs/guides/manage-accounts/webhooks/about-webhooks) and [Manage webhooks](https://developer.revolut.com/docs/guides/manage-accounts/webhooks/manage-webhooks#retrieve-a-specific-webhook).
//
// Docs: https://developer.revolut.com/docs/business/get-webhook
// Required scopes: READ
func (s *WebhooksV2) Get(ctx context.Context, webhookID string) (*WebhookV2, error) {
	if webhookID == "" {
		return nil, errors.New("business: webhook_id is required")
	}
	if !isUUID(webhookID) {
		return nil, errors.New("business: webhook_id must be a valid UUID")
	}
	var out WebhookV2
	if err := s.t.Do(ctx, http.MethodGet, "https://b2b.revolut.com/api/2.0/"+"webhooks/"+url.PathEscape(webhookID), nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update update a webhook
//
// Update an existing webhook. Change the URL to which event notifications are sent or the list of event types to be notified about.
//
// You must specify at least one of these two. The fields that you don't specify are not updated.
//
// For more information, see the guides: [About webhooks](https://developer.revolut.com/docs/guides/manage-accounts/webhooks/about-webhooks) and [Manage webhooks](https://developer.revolut.com/docs/guides/manage-accounts/webhooks/manage-webhooks#update-a-webhook).
//
// Docs: https://developer.revolut.com/docs/business/update-webhook
// Required scopes: WRITE
func (s *WebhooksV2) Update(ctx context.Context, webhookID string, req UpdateWebhookRequest) (*WebhookV2Basic, error) {
	if webhookID == "" {
		return nil, errors.New("business: webhook_id is required")
	}
	if !isUUID(webhookID) {
		return nil, errors.New("business: webhook_id must be a valid UUID")
	}
	var out WebhookV2Basic
	if err := s.t.Do(ctx, http.MethodPatch, "https://b2b.revolut.com/api/2.0/"+"webhooks/"+url.PathEscape(webhookID), req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete delete a webhook
//
// Delete a specific webhook.
//
// A successful response does not get any content in return.
//
// For more information, see the guides: [About webhooks](https://developer.revolut.com/docs/guides/manage-accounts/webhooks/about-webhooks) and [Manage webhooks](https://developer.revolut.com/docs/guides/manage-accounts/webhooks/manage-webhooks#delete-a-webhook).
//
// Docs: https://developer.revolut.com/docs/business/delete-webhook
// Required scopes: WRITE
func (s *WebhooksV2) Delete(ctx context.Context, webhookID string) error {
	if webhookID == "" {
		return errors.New("business: webhook_id is required")
	}
	if !isUUID(webhookID) {
		return errors.New("business: webhook_id must be a valid UUID")
	}
	return s.t.Do(ctx, http.MethodDelete, "https://b2b.revolut.com/api/2.0/"+"webhooks/"+url.PathEscape(webhookID), nil, nil)
}

// GetFailedWebhookEvents retrieve a list of failed webhook events
//
// Get the list of all your failed webhook events, or use the query parameters to filter the results.
//
// The events are sorted by the `created_at` date in reverse chronological order.
//
// The returned failed events are **paginated**.
// The maximum number of events returned per page is specified by the `limit` parameter.
// To get to the next page, make a new request and use the `created_at` date of the last event returned in the previous response.
//
// For more information, see the guides: [About webhooks](https://developer.revolut.com/docs/guides/manage-accounts/webhooks/about-webhooks) and [Manage webhooks](https://developer.revolut.com/docs/guides/manage-accounts/webhooks/manage-webhooks#retrieve-a-list-of-failed-webhook-events).
//
// Docs: https://developer.revolut.com/docs/business/get-failed-webhook-events
// Required scopes: READ
func (s *WebhooksV2) GetFailedWebhookEvents(ctx context.Context, webhookID string, opts *GetFailedWebhookEventsParams) ([]WebhookEvent, error) {
	if webhookID == "" {
		return nil, errors.New("business: webhook_id is required")
	}
	if !isUUID(webhookID) {
		return nil, errors.New("business: webhook_id must be a valid UUID")
	}
	path := "https://b2b.revolut.com/api/2.0/" + "webhooks/" + url.PathEscape(webhookID) + "/failed-events"
	if q := opts.encode().Encode(); q != "" {
		path += "?" + q
	}
	var out []WebhookEvent
	if err := s.t.Do(ctx, http.MethodGet, path, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// GetFailedWebhookEventsAll iterates every page of GetFailedWebhookEvents, yielding one WebhookEvent per
// step. Break out of the loop to stop early.
func (s *WebhooksV2) GetFailedWebhookEventsAll(ctx context.Context, webhookID string, opts *GetFailedWebhookEventsParams) iter.Seq2[WebhookEvent, error] {
	return func(yield func(WebhookEvent, error) bool) {
		var p GetFailedWebhookEventsParams
		if opts != nil {
			p = *opts
		}
		if webhookID == "" {
			var zero WebhookEvent
			yield(zero, errors.New("business: webhookID is required"))
			return
		}
		for {
			if err := ctx.Err(); err != nil {
				var zero WebhookEvent
				yield(zero, err)
				return
			}
			resp, err := s.GetFailedWebhookEvents(ctx, webhookID, &p)
			if err != nil {
				var zero WebhookEvent
				yield(zero, err)
				return
			}
			if len(resp) == 0 {
				return
			}
			for _, item := range resp {
				if !yield(item, nil) {
					return
				}
			}
			nextAdv := resp[len(resp)-1].CreatedAt
			if nextAdv == p.CreatedBefore {
				return
			}
			p.CreatedBefore = nextAdv
		}
	}
}

// RotateWebhookSigningSecret rotate a webhook signing secret
//
// Rotate a signing secret for a specific webhook.
//
// For more information, see the guides: [About webhooks](https://developer.revolut.com/docs/guides/manage-accounts/webhooks/about-webhooks) and [Manage webhooks](https://developer.revolut.com/docs/guides/manage-accounts/webhooks/manage-webhooks#rotate-a-webhook-signing-secret).
//
// Docs: https://developer.revolut.com/docs/business/rotate-webhook-signing-secret
// Required scopes: WRITE
func (s *WebhooksV2) RotateWebhookSigningSecret(ctx context.Context, webhookID string, req WebhookSigningSecretRotateRequest) (*WebhookV2, error) {
	if webhookID == "" {
		return nil, errors.New("business: webhook_id is required")
	}
	if !isUUID(webhookID) {
		return nil, errors.New("business: webhook_id must be a valid UUID")
	}
	var out WebhookV2
	if err := s.t.Do(ctx, http.MethodPost, "https://b2b.revolut.com/api/2.0/"+"webhooks/"+url.PathEscape(webhookID)+"/rotate-signing-secret", req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
