// Code generated by revogen. DO NOT EDIT.

package business

import (
	"context"
	"errors"
	"net/http"

	"github.com/greatliontech/revolut-go/internal/transport"
)

// Transfers groups the Transfers endpoints.
type Transfers struct {
	t *transport.Transport
}

// Pay create a transfer to another account or card
//
// Docs: https://developer.revolut.com/docs/business/create-payment
func (s *Transfers) Pay(ctx context.Context, req TransactionPaymentRequest) (*TransferResponse, error) {
	if req.AccountID == "" {
		return nil, errors.New("business: TransactionPaymentRequest.AccountID is required")
	}
	if req.Amount == "" {
		return nil, errors.New("business: TransactionPaymentRequest.Amount is required")
	}
	if req.RequestID == "" {
		return nil, errors.New("business: TransactionPaymentRequest.RequestID is required")
	}
	var out TransferResponse
	if err := s.t.Do(ctx, http.MethodPost, "pay", req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Create move money between your accounts
//
// Docs: https://developer.revolut.com/docs/business/create-transfer
func (s *Transfers) Create(ctx context.Context, req TransferRequest) (*TransferResponse, error) {
	if req.Amount == "" {
		return nil, errors.New("business: TransferRequest.Amount is required")
	}
	if req.Currency == "" {
		return nil, errors.New("business: TransferRequest.Currency is required")
	}
	if req.RequestID == "" {
		return nil, errors.New("business: TransferRequest.RequestID is required")
	}
	if req.SourceAccountID == "" {
		return nil, errors.New("business: TransferRequest.SourceAccountID is required")
	}
	if req.TargetAccountID == "" {
		return nil, errors.New("business: TransferRequest.TargetAccountID is required")
	}
	var out TransferResponse
	if err := s.t.Do(ctx, http.MethodPost, "transfer", req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListReasons get transfer reasons
//
// Docs: https://developer.revolut.com/docs/business/get-transfer-reasons
func (s *Transfers) ListReasons(ctx context.Context) ([]TransferReason, error) {
	var out []TransferReason
	if err := s.t.Do(ctx, http.MethodGet, "transfer-reasons", nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}
