// Code generated by revogen. DO NOT EDIT.

package business

import (
	"context"
	"errors"
	"net/http"
	"net/url"

	"github.com/greatliontech/revolut-go/internal/transport"
)

// Accounting groups the Accounting endpoints.
type Accounting struct {
	t *transport.Transport
}

// GetCategories retrieve a list of accounting categories
//
// Docs: https://developer.revolut.com/docs/business/get-accounting-categories
func (s *Accounting) GetCategories(ctx context.Context) (*GetAccountingCategoriesResponse, error) {
	var out GetAccountingCategoriesResponse
	if err := s.t.Do(ctx, http.MethodGet, "accounting-categories", nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateCategory create an accounting category
//
// Docs: https://developer.revolut.com/docs/business/create-accounting-category
func (s *Accounting) CreateCategory(ctx context.Context, req CreateAccountingCategoryRequest) (*ResourceCreatedResponse, error) {
	if req.Code == "" {
		return nil, errors.New("business: CreateAccountingCategoryRequest.Code is required")
	}
	if req.Name == "" {
		return nil, errors.New("business: CreateAccountingCategoryRequest.Name is required")
	}
	var out ResourceCreatedResponse
	if err := s.t.Do(ctx, http.MethodPost, "accounting-categories", req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCategory retrieve accounting category details
//
// Docs: https://developer.revolut.com/docs/business/get-accounting-category
func (s *Accounting) GetCategory(ctx context.Context, accountingCategoryID string) (*AccountingCategoryResponse, error) {
	if accountingCategoryID == "" {
		return nil, errors.New("business: accounting_category_id is required")
	}
	var out AccountingCategoryResponse
	if err := s.t.Do(ctx, http.MethodGet, "accounting-categories/"+url.PathEscape(accountingCategoryID), nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateCategory update accounting category settings
//
// Docs: https://developer.revolut.com/docs/business/update-accounting-category
func (s *Accounting) UpdateCategory(ctx context.Context, accountingCategoryID string, req UpdateAccountingCategoryRequest) error {
	if accountingCategoryID == "" {
		return errors.New("business: accounting_category_id is required")
	}
	return s.t.Do(ctx, http.MethodPatch, "accounting-categories/"+url.PathEscape(accountingCategoryID), req, nil)
}

// DeleteCategory delete an accounting category
//
// Docs: https://developer.revolut.com/docs/business/delete-accounting-category
func (s *Accounting) DeleteCategory(ctx context.Context, accountingCategoryID string) error {
	if accountingCategoryID == "" {
		return errors.New("business: accounting_category_id is required")
	}
	return s.t.Do(ctx, http.MethodDelete, "accounting-categories/"+url.PathEscape(accountingCategoryID), nil, nil)
}

// GetLabelGroups retrieve a list of label groups
//
// Docs: https://developer.revolut.com/docs/business/get-label-groups
func (s *Accounting) GetLabelGroups(ctx context.Context) (*GetLabelGroupsResponse, error) {
	var out GetLabelGroupsResponse
	if err := s.t.Do(ctx, http.MethodGet, "label-groups", nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateLabelGroup create a new label group
//
// Docs: https://developer.revolut.com/docs/business/create-label-group
func (s *Accounting) CreateLabelGroup(ctx context.Context, req CreateLabelGroupRequest) (*ResourceCreatedResponse, error) {
	if req.Name == "" {
		return nil, errors.New("business: CreateLabelGroupRequest.Name is required")
	}
	var out ResourceCreatedResponse
	if err := s.t.Do(ctx, http.MethodPost, "label-groups", req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetLabelGroup retrieve label group details
//
// Docs: https://developer.revolut.com/docs/business/get-label-group
func (s *Accounting) GetLabelGroup(ctx context.Context, groupID string) (*LabelGroupResponse, error) {
	if groupID == "" {
		return nil, errors.New("business: group_id is required")
	}
	var out LabelGroupResponse
	if err := s.t.Do(ctx, http.MethodGet, "label-groups/"+url.PathEscape(groupID), nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateLabelGroup update label group settings
//
// Docs: https://developer.revolut.com/docs/business/update-label-group
func (s *Accounting) UpdateLabelGroup(ctx context.Context, groupID string, req UpdateLabelGroupRequest) error {
	if groupID == "" {
		return errors.New("business: group_id is required")
	}
	if req.Name == "" {
		return errors.New("business: UpdateLabelGroupRequest.Name is required")
	}
	return s.t.Do(ctx, http.MethodPatch, "label-groups/"+url.PathEscape(groupID), req, nil)
}

// DeleteLabelGroup delete a label group
//
// Docs: https://developer.revolut.com/docs/business/delete-label-group
func (s *Accounting) DeleteLabelGroup(ctx context.Context, groupID string) error {
	if groupID == "" {
		return errors.New("business: group_id is required")
	}
	return s.t.Do(ctx, http.MethodDelete, "label-groups/"+url.PathEscape(groupID), nil, nil)
}

// GetLabels retrieve a list of labels from a label group
//
// Docs: https://developer.revolut.com/docs/business/get-labels
func (s *Accounting) GetLabels(ctx context.Context, groupID string) (*GetLabelsResponse, error) {
	if groupID == "" {
		return nil, errors.New("business: group_id is required")
	}
	var out GetLabelsResponse
	if err := s.t.Do(ctx, http.MethodGet, "label-groups/"+url.PathEscape(groupID)+"/labels", nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateLabel create a new label
//
// Docs: https://developer.revolut.com/docs/business/create-label
func (s *Accounting) CreateLabel(ctx context.Context, groupID string, req CreateLabelRequest) (*ResourceCreatedResponse, error) {
	if groupID == "" {
		return nil, errors.New("business: group_id is required")
	}
	if req.Name == "" {
		return nil, errors.New("business: CreateLabelRequest.Name is required")
	}
	var out ResourceCreatedResponse
	if err := s.t.Do(ctx, http.MethodPost, "label-groups/"+url.PathEscape(groupID)+"/labels", req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateLabel update a label
//
// Docs: https://developer.revolut.com/docs/business/update-label
func (s *Accounting) UpdateLabel(ctx context.Context, groupID string, labelID string, req UpdateLabelRequest) error {
	if groupID == "" {
		return errors.New("business: group_id is required")
	}
	if labelID == "" {
		return errors.New("business: label_id is required")
	}
	if req.Name == "" {
		return errors.New("business: UpdateLabelRequest.Name is required")
	}
	return s.t.Do(ctx, http.MethodPatch, "label-groups/"+url.PathEscape(groupID)+"/labels/"+url.PathEscape(labelID), req, nil)
}

// DeleteLabel delete a label
//
// Docs: https://developer.revolut.com/docs/business/delete-label
func (s *Accounting) DeleteLabel(ctx context.Context, groupID string, labelID string) error {
	if groupID == "" {
		return errors.New("business: group_id is required")
	}
	if labelID == "" {
		return errors.New("business: label_id is required")
	}
	return s.t.Do(ctx, http.MethodDelete, "label-groups/"+url.PathEscape(groupID)+"/labels/"+url.PathEscape(labelID), nil, nil)
}

// GetTaxRates retrieve a list of tax rates
//
// Docs: https://developer.revolut.com/docs/business/get-tax-rates
func (s *Accounting) GetTaxRates(ctx context.Context) (*GetTaxRatesResponse, error) {
	var out GetTaxRatesResponse
	if err := s.t.Do(ctx, http.MethodGet, "tax-rates", nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateTaxRate create a new tax rate
//
// Docs: https://developer.revolut.com/docs/business/create-tax-rate
func (s *Accounting) CreateTaxRate(ctx context.Context, req CreateTaxRateRequest) (*ResourceCreatedResponse, error) {
	if req.Name == "" {
		return nil, errors.New("business: CreateTaxRateRequest.Name is required")
	}
	if req.Percentage == "" {
		return nil, errors.New("business: CreateTaxRateRequest.Percentage is required")
	}
	var out ResourceCreatedResponse
	if err := s.t.Do(ctx, http.MethodPost, "tax-rates", req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetTaxRate retrieve tax rate details
//
// Docs: https://developer.revolut.com/docs/business/get-tax-rate
func (s *Accounting) GetTaxRate(ctx context.Context, taxRateID string) (*TaxRateResponse, error) {
	if taxRateID == "" {
		return nil, errors.New("business: tax_rate_id is required")
	}
	var out TaxRateResponse
	if err := s.t.Do(ctx, http.MethodGet, "tax-rates/"+url.PathEscape(taxRateID), nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateTaxRate update tax rate settings
//
// Docs: https://developer.revolut.com/docs/business/update-tax-rate
func (s *Accounting) UpdateTaxRate(ctx context.Context, taxRateID string, req UpdateTaxRateRequest) error {
	if taxRateID == "" {
		return errors.New("business: tax_rate_id is required")
	}
	return s.t.Do(ctx, http.MethodPatch, "tax-rates/"+url.PathEscape(taxRateID), req, nil)
}

// DeleteTaxRate delete a tax rate
//
// Docs: https://developer.revolut.com/docs/business/delete-tax-rate
func (s *Accounting) DeleteTaxRate(ctx context.Context, taxRateID string) error {
	if taxRateID == "" {
		return errors.New("business: tax_rate_id is required")
	}
	return s.t.Do(ctx, http.MethodDelete, "tax-rates/"+url.PathEscape(taxRateID), nil, nil)
}
