// Code generated by revogen. DO NOT EDIT.

package business

import (
	"context"
	"errors"
	"net/http"

	"github.com/greatliontech/revolut-go/internal/transport"
)

// WebhooksV1Deprecated groups the WebhooksV1Deprecated endpoints.
type WebhooksV1Deprecated struct {
	t *transport.Transport
}

// List retrieve a webhook
//
// Docs: https://developer.revolut.com/docs/business/get-webhook-v1
func (s *WebhooksV1Deprecated) List(ctx context.Context) (*WebhookV1, error) {
	var out WebhookV1
	if err := s.t.Do(ctx, http.MethodGet, "webhook", nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Create set a webhook
//
// Docs: https://developer.revolut.com/docs/business/set-up-webhook
func (s *WebhooksV1Deprecated) Create(ctx context.Context, req WebhookV1) error {
	if req.URL == "" {
		return errors.New("business: WebhookV1.URL is required")
	}
	return s.t.Do(ctx, http.MethodPost, "webhook", req, nil)
}

// Delete delete a webhook
//
// Docs: https://developer.revolut.com/docs/business/delete-webhook-v1
func (s *WebhooksV1Deprecated) Delete(ctx context.Context) error {
	return s.t.Do(ctx, http.MethodDelete, "webhook", nil, nil)
}
