// Code generated by revogen. DO NOT EDIT.

package business

import (
	"context"
	"errors"
	"net/http"
	"net/url"

	"github.com/greatliontech/revolut-go/internal/transport"
)

// TeamMembers groups the TeamMembers endpoints.
type TeamMembers struct {
	t *transport.Transport
}

// ListRoles retrieve team roles
//
// Docs: https://developer.revolut.com/docs/business/get-roles
func (s *TeamMembers) ListRoles(ctx context.Context) ([]Role, error) {
	var out []Role
	if err := s.t.Do(ctx, http.MethodGet, "roles", nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// List retrieve a list of team members
//
// Docs: https://developer.revolut.com/docs/business/get-team-members
func (s *TeamMembers) List(ctx context.Context) ([]TeamMember, error) {
	var out []TeamMember
	if err := s.t.Do(ctx, http.MethodGet, "team-members", nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Create invite a new member to your business
//
// Docs: https://developer.revolut.com/docs/business/invite-team-member
func (s *TeamMembers) Create(ctx context.Context) (*InviteTeamMemberResponse, error) {
	var out InviteTeamMemberResponse
	if err := s.t.Do(ctx, http.MethodPost, "team-members", nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete delete a team member
//
// Docs: https://developer.revolut.com/docs/business/delete-team-member
func (s *TeamMembers) Delete(ctx context.Context, teamMemberID string) error {
	if teamMemberID == "" {
		return errors.New("business: team_member_id is required")
	}
	return s.t.Do(ctx, http.MethodDelete, "team-members/"+url.PathEscape(teamMemberID), nil, nil)
}
