// Code generated by revogen. DO NOT EDIT.

package openbanking

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"net/url"

	"github.com/greatliontech/revolut-go/internal/transport"
)

// DomesticPayment groups the DomesticPayment endpoints.
type DomesticPayment struct {
	t *transport.Transport
}

// CreateConsents create a domestic payment consent
//
// Docs: https://developer.revolut.com/docs/openbanking/create-domestic-payment-consents
// Required scopes: payments
func (s *DomesticPayment) CreateConsents(ctx context.Context, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, authorization string, xIdempotencyKey string, xJWSSignature string, xCustomerUserAgent string, req ObwriteDomesticConsent2) (*ObwriteDomesticConsentResponse2, ResponseMetadata, error) {
	if xFAPIFinancialID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: x-fapi-financial-id is required")
	}
	if authorization == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: Authorization is required")
	}
	if xIdempotencyKey == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: x-idempotency-key is required")
	}
	if xJWSSignature == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: x-jws-signature is required")
	}
	if req.Data.Initiation.CreditorAccount.Identification == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.CreditorAccount.Identification is required")
	}
	if req.Data.Initiation.CreditorAccount.Name == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.CreditorAccount.Name is required")
	}
	if req.Data.Initiation.CreditorAccount.SchemeName == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.CreditorAccount.SchemeName is required")
	}
	if req.Data.Initiation.EndToEndIdentification == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.EndToEndIdentification is required")
	}
	if req.Data.Initiation.InstructedAmount == nil {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.InstructedAmount is required")
	}
	if req.Data.Initiation.InstructedAmount != nil && req.Data.Initiation.InstructedAmount.Amount == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.InstructedAmount.Amount is required")
	}
	if req.Data.Initiation.InstructedAmount != nil && req.Data.Initiation.InstructedAmount.Currency == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.InstructedAmount.Currency is required")
	}
	if req.Data.Initiation.InstructionIdentification == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.InstructionIdentification is required")
	}
	r := transport.RawRequest{
		JSONBody: req,
	}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if xIdempotencyKey != "" {
		r.Headers.Set("x-idempotency-key", xIdempotencyKey)
	}
	if xJWSSignature != "" {
		r.Headers.Set("x-jws-signature", xJWSSignature)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodPost, "domestic-payment-consents", r)
	if err != nil {
		return nil, ResponseMetadata{}, err
	}
	var out ObwriteDomesticConsentResponse2
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, ResponseMetadata{}, err
	}
	return &out, extractResponseMetadata(hdr), nil
}

// CreateConsentsSigned is CreateConsents with the raw response body and ResponseMetadata
// preserved alongside the typed payload. Use it when you need to verify
// the detached x-jws-signature header against the untouched bytes.
func (s *DomesticPayment) CreateConsentsSigned(ctx context.Context, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, authorization string, xIdempotencyKey string, xJWSSignature string, xCustomerUserAgent string, req ObwriteDomesticConsent2) (*Signed[ObwriteDomesticConsentResponse2], error) {
	if xFAPIFinancialID == "" {
		return nil, errors.New("openbanking: x-fapi-financial-id is required")
	}
	if authorization == "" {
		return nil, errors.New("openbanking: Authorization is required")
	}
	if xIdempotencyKey == "" {
		return nil, errors.New("openbanking: x-idempotency-key is required")
	}
	if xJWSSignature == "" {
		return nil, errors.New("openbanking: x-jws-signature is required")
	}
	if req.Data.Initiation.CreditorAccount.Identification == "" {
		return nil, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.CreditorAccount.Identification is required")
	}
	if req.Data.Initiation.CreditorAccount.Name == "" {
		return nil, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.CreditorAccount.Name is required")
	}
	if req.Data.Initiation.CreditorAccount.SchemeName == "" {
		return nil, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.CreditorAccount.SchemeName is required")
	}
	if req.Data.Initiation.EndToEndIdentification == "" {
		return nil, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.EndToEndIdentification is required")
	}
	if req.Data.Initiation.InstructedAmount == nil {
		return nil, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.InstructedAmount is required")
	}
	if req.Data.Initiation.InstructedAmount != nil && req.Data.Initiation.InstructedAmount.Amount == "" {
		return nil, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.InstructedAmount.Amount is required")
	}
	if req.Data.Initiation.InstructedAmount != nil && req.Data.Initiation.InstructedAmount.Currency == "" {
		return nil, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.InstructedAmount.Currency is required")
	}
	if req.Data.Initiation.InstructionIdentification == "" {
		return nil, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.InstructionIdentification is required")
	}
	r := transport.RawRequest{
		JSONBody: req,
	}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if xIdempotencyKey != "" {
		r.Headers.Set("x-idempotency-key", xIdempotencyKey)
	}
	if xJWSSignature != "" {
		r.Headers.Set("x-jws-signature", xJWSSignature)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodPost, "domestic-payment-consents", r)
	if err != nil {
		return nil, err
	}
	var out ObwriteDomesticConsentResponse2
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &Signed[ObwriteDomesticConsentResponse2]{Typed: &out, Raw: body, Metadata: extractResponseMetadata(hdr)}, nil
}

// GetConsentsConsentID retrieve a domestic payment consent
//
// Docs: https://developer.revolut.com/docs/openbanking/get-domestic-payment-consents-consent-id
// Required scopes: payments
func (s *DomesticPayment) GetConsentsConsentID(ctx context.Context, consentID string, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, authorization string, xCustomerUserAgent string) (*ObwriteDomesticConsentResponse2, ResponseMetadata, error) {
	if consentID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ConsentId is required")
	}
	if xFAPIFinancialID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: x-fapi-financial-id is required")
	}
	if authorization == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: Authorization is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodGet, "domestic-payment-consents/"+url.PathEscape(consentID), r)
	if err != nil {
		return nil, ResponseMetadata{}, err
	}
	var out ObwriteDomesticConsentResponse2
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, ResponseMetadata{}, err
	}
	return &out, extractResponseMetadata(hdr), nil
}

// GetConsentsConsentIDSigned is GetConsentsConsentID with the raw response body and ResponseMetadata
// preserved alongside the typed payload. Use it when you need to verify
// the detached x-jws-signature header against the untouched bytes.
func (s *DomesticPayment) GetConsentsConsentIDSigned(ctx context.Context, consentID string, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, authorization string, xCustomerUserAgent string) (*Signed[ObwriteDomesticConsentResponse2], error) {
	if consentID == "" {
		return nil, errors.New("openbanking: ConsentId is required")
	}
	if xFAPIFinancialID == "" {
		return nil, errors.New("openbanking: x-fapi-financial-id is required")
	}
	if authorization == "" {
		return nil, errors.New("openbanking: Authorization is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodGet, "domestic-payment-consents/"+url.PathEscape(consentID), r)
	if err != nil {
		return nil, err
	}
	var out ObwriteDomesticConsentResponse2
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &Signed[ObwriteDomesticConsentResponse2]{Typed: &out, Raw: body, Metadata: extractResponseMetadata(hdr)}, nil
}

// GetConsentsConsentIDFundsConfirmation get funds confirmation for a domestic payment consent
//
// Docs: https://developer.revolut.com/docs/openbanking/get-domestic-payment-consents-consent-id-funds-confirmation
// Required scopes: payments
func (s *DomesticPayment) GetConsentsConsentIDFundsConfirmation(ctx context.Context, consentID string, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, authorization string, xCustomerUserAgent string) (*ObwriteFundsConfirmationResponse1, ResponseMetadata, error) {
	if consentID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ConsentId is required")
	}
	if xFAPIFinancialID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: x-fapi-financial-id is required")
	}
	if authorization == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: Authorization is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodGet, "domestic-payment-consents/"+url.PathEscape(consentID)+"/funds-confirmation", r)
	if err != nil {
		return nil, ResponseMetadata{}, err
	}
	var out ObwriteFundsConfirmationResponse1
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, ResponseMetadata{}, err
	}
	return &out, extractResponseMetadata(hdr), nil
}

// GetConsentsConsentIDFundsConfirmationSigned is GetConsentsConsentIDFundsConfirmation with the raw response body and ResponseMetadata
// preserved alongside the typed payload. Use it when you need to verify
// the detached x-jws-signature header against the untouched bytes.
func (s *DomesticPayment) GetConsentsConsentIDFundsConfirmationSigned(ctx context.Context, consentID string, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, authorization string, xCustomerUserAgent string) (*Signed[ObwriteFundsConfirmationResponse1], error) {
	if consentID == "" {
		return nil, errors.New("openbanking: ConsentId is required")
	}
	if xFAPIFinancialID == "" {
		return nil, errors.New("openbanking: x-fapi-financial-id is required")
	}
	if authorization == "" {
		return nil, errors.New("openbanking: Authorization is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodGet, "domestic-payment-consents/"+url.PathEscape(consentID)+"/funds-confirmation", r)
	if err != nil {
		return nil, err
	}
	var out ObwriteFundsConfirmationResponse1
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &Signed[ObwriteFundsConfirmationResponse1]{Typed: &out, Raw: body, Metadata: extractResponseMetadata(hdr)}, nil
}

// Create create a domestic payment
//
// Docs: https://developer.revolut.com/docs/openbanking/create-domestic-payments
// Required scopes: payments
func (s *DomesticPayment) Create(ctx context.Context, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, authorization string, xIdempotencyKey string, xJWSSignature string, xCustomerUserAgent string, req ObwriteDomestic2) (*ObwriteDomesticResponse2, ResponseMetadata, error) {
	if xFAPIFinancialID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: x-fapi-financial-id is required")
	}
	if authorization == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: Authorization is required")
	}
	if xIdempotencyKey == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: x-idempotency-key is required")
	}
	if xJWSSignature == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: x-jws-signature is required")
	}
	if req.Data.ConsentID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomestic2.Data.ConsentId is required")
	}
	if req.Data.Initiation.CreditorAccount.Identification == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.CreditorAccount.Identification is required")
	}
	if req.Data.Initiation.CreditorAccount.Name == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.CreditorAccount.Name is required")
	}
	if req.Data.Initiation.CreditorAccount.SchemeName == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.CreditorAccount.SchemeName is required")
	}
	if req.Data.Initiation.EndToEndIdentification == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.EndToEndIdentification is required")
	}
	if req.Data.Initiation.InstructedAmount == nil {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.InstructedAmount is required")
	}
	if req.Data.Initiation.InstructedAmount != nil && req.Data.Initiation.InstructedAmount.Amount == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.InstructedAmount.Amount is required")
	}
	if req.Data.Initiation.InstructedAmount != nil && req.Data.Initiation.InstructedAmount.Currency == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.InstructedAmount.Currency is required")
	}
	if req.Data.Initiation.InstructionIdentification == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.InstructionIdentification is required")
	}
	r := transport.RawRequest{
		JSONBody: req,
	}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if xIdempotencyKey != "" {
		r.Headers.Set("x-idempotency-key", xIdempotencyKey)
	}
	if xJWSSignature != "" {
		r.Headers.Set("x-jws-signature", xJWSSignature)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodPost, "domestic-payments", r)
	if err != nil {
		return nil, ResponseMetadata{}, err
	}
	var out ObwriteDomesticResponse2
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, ResponseMetadata{}, err
	}
	return &out, extractResponseMetadata(hdr), nil
}

// CreateSigned is Create with the raw response body and ResponseMetadata
// preserved alongside the typed payload. Use it when you need to verify
// the detached x-jws-signature header against the untouched bytes.
func (s *DomesticPayment) CreateSigned(ctx context.Context, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, authorization string, xIdempotencyKey string, xJWSSignature string, xCustomerUserAgent string, req ObwriteDomestic2) (*Signed[ObwriteDomesticResponse2], error) {
	if xFAPIFinancialID == "" {
		return nil, errors.New("openbanking: x-fapi-financial-id is required")
	}
	if authorization == "" {
		return nil, errors.New("openbanking: Authorization is required")
	}
	if xIdempotencyKey == "" {
		return nil, errors.New("openbanking: x-idempotency-key is required")
	}
	if xJWSSignature == "" {
		return nil, errors.New("openbanking: x-jws-signature is required")
	}
	if req.Data.ConsentID == "" {
		return nil, errors.New("openbanking: ObwriteDomestic2.Data.ConsentId is required")
	}
	if req.Data.Initiation.CreditorAccount.Identification == "" {
		return nil, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.CreditorAccount.Identification is required")
	}
	if req.Data.Initiation.CreditorAccount.Name == "" {
		return nil, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.CreditorAccount.Name is required")
	}
	if req.Data.Initiation.CreditorAccount.SchemeName == "" {
		return nil, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.CreditorAccount.SchemeName is required")
	}
	if req.Data.Initiation.EndToEndIdentification == "" {
		return nil, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.EndToEndIdentification is required")
	}
	if req.Data.Initiation.InstructedAmount == nil {
		return nil, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.InstructedAmount is required")
	}
	if req.Data.Initiation.InstructedAmount != nil && req.Data.Initiation.InstructedAmount.Amount == "" {
		return nil, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.InstructedAmount.Amount is required")
	}
	if req.Data.Initiation.InstructedAmount != nil && req.Data.Initiation.InstructedAmount.Currency == "" {
		return nil, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.InstructedAmount.Currency is required")
	}
	if req.Data.Initiation.InstructionIdentification == "" {
		return nil, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.InstructionIdentification is required")
	}
	r := transport.RawRequest{
		JSONBody: req,
	}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if xIdempotencyKey != "" {
		r.Headers.Set("x-idempotency-key", xIdempotencyKey)
	}
	if xJWSSignature != "" {
		r.Headers.Set("x-jws-signature", xJWSSignature)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodPost, "domestic-payments", r)
	if err != nil {
		return nil, err
	}
	var out ObwriteDomesticResponse2
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &Signed[ObwriteDomesticResponse2]{Typed: &out, Raw: body, Metadata: extractResponseMetadata(hdr)}, nil
}

// GetDomesticPaymentID retrieve a domestic payment
//
// Docs: https://developer.revolut.com/docs/openbanking/get-domestic-payments-domestic-payment-id
// Required scopes: payments
func (s *DomesticPayment) GetDomesticPaymentID(ctx context.Context, domesticPaymentID string, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, authorization string, xCustomerUserAgent string) (*ObwriteDomesticResponse2, ResponseMetadata, error) {
	if domesticPaymentID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: DomesticPaymentId is required")
	}
	if xFAPIFinancialID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: x-fapi-financial-id is required")
	}
	if authorization == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: Authorization is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodGet, "domestic-payments/"+url.PathEscape(domesticPaymentID), r)
	if err != nil {
		return nil, ResponseMetadata{}, err
	}
	var out ObwriteDomesticResponse2
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, ResponseMetadata{}, err
	}
	return &out, extractResponseMetadata(hdr), nil
}

// GetDomesticPaymentIDSigned is GetDomesticPaymentID with the raw response body and ResponseMetadata
// preserved alongside the typed payload. Use it when you need to verify
// the detached x-jws-signature header against the untouched bytes.
func (s *DomesticPayment) GetDomesticPaymentIDSigned(ctx context.Context, domesticPaymentID string, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, authorization string, xCustomerUserAgent string) (*Signed[ObwriteDomesticResponse2], error) {
	if domesticPaymentID == "" {
		return nil, errors.New("openbanking: DomesticPaymentId is required")
	}
	if xFAPIFinancialID == "" {
		return nil, errors.New("openbanking: x-fapi-financial-id is required")
	}
	if authorization == "" {
		return nil, errors.New("openbanking: Authorization is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodGet, "domestic-payments/"+url.PathEscape(domesticPaymentID), r)
	if err != nil {
		return nil, err
	}
	var out ObwriteDomesticResponse2
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &Signed[ObwriteDomesticResponse2]{Typed: &out, Raw: body, Metadata: extractResponseMetadata(hdr)}, nil
}
