// Code generated by revogen. DO NOT EDIT.

package openbanking

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"net/url"

	"github.com/greatliontech/revolut-go/internal/transport"
	"github.com/greatliontech/revolut-go/internal/validate"
)

// DomesticPayment groups the DomesticPayment endpoints.
type DomesticPayment struct {
	t *transport.Transport
}

// CreateConsents create a domestic payment consent
//
// Create a domestic payment consent described in the [Open Banking API documentation: Account and Transaction API Specification](https://openbanking.atlassian.net/wiki/spaces/DZ/pages/999622968/Account+and+Transaction+API+Specification+-+v3.1.1).
//
// Use domestic payments for local payments in the local currency of the user.
//
// :::note
// Revolut supports only GBP as local in the UK and EUR in Single Euro Payments Area (SEPA) countries.
// :::
//
// Because Revolut Business users can have multiple accounts in the same currency, they can choose which account they want to be charged in the consent authorization UI.
//
// When you make the API call, ensure that you pass the corresponding JSON Web Signature (JWS) in the `x-jws-signature` request header. Note:
//
// - The JWS is generated from the request body with the [TPP](https://developer.revolut.com/docs/guides/build-banking-apps/glossary) signing key that is specified in the JWS header.
//
// - The JWS consists of a header and a signature in the `<jws_header>..<jws_signature>` format.
//
// To see how to create a JWS, see the guide: [Work with JSON Web Signatures](https://developer.revolut.com/docs/guides/build-banking-apps/tutorials/work-with-json-web-signatures).
//
// See also [Tutorials: Initiate your first payment](https://developer.revolut.com/docs/guides/build-banking-apps/tutorials/initiate-your-first-payment#2-create-a-domestic-payment-consent).
//
// Docs: https://developer.revolut.com/docs/openbanking/create-domestic-payment-consents
// Required scopes: payments
func (s *DomesticPayment) CreateConsents(ctx context.Context, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, xIdempotencyKey string, xJWSSignature string, xCustomerUserAgent string, req ObwriteDomesticConsent2) (*ObwriteDomesticConsentResponse2, ResponseMetadata, error) {
	if xFAPIFinancialID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: x-fapi-financial-id is required")
	}
	if xIdempotencyKey == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: x-idempotency-key is required")
	}
	if xJWSSignature == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: x-jws-signature is required")
	}
	if req.Data.Initiation.CreditorAccount.Identification == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.CreditorAccount.Identification is required")
	}
	if len(req.Data.Initiation.CreditorAccount.Identification) < 1 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.CreditorAccount.Identification must be at least 1 characters")
	}
	if len(req.Data.Initiation.CreditorAccount.Identification) > 256 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.CreditorAccount.Identification must be at most 256 characters")
	}
	if req.Data.Initiation.CreditorAccount.Name == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.CreditorAccount.Name is required")
	}
	if len(req.Data.Initiation.CreditorAccount.Name) < 1 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.CreditorAccount.Name must be at least 1 characters")
	}
	if len(req.Data.Initiation.CreditorAccount.Name) > 70 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.CreditorAccount.Name must be at most 70 characters")
	}
	if req.Data.Initiation.CreditorAccount.SchemeName == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.CreditorAccount.SchemeName is required")
	}
	if req.Data.Initiation.CreditorAccount.SecondaryIdentification != "" && len(req.Data.Initiation.CreditorAccount.SecondaryIdentification) < 1 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.CreditorAccount.SecondaryIdentification must be at least 1 characters")
	}
	if req.Data.Initiation.CreditorAccount.SecondaryIdentification != "" && len(req.Data.Initiation.CreditorAccount.SecondaryIdentification) > 34 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.CreditorAccount.SecondaryIdentification must be at most 34 characters")
	}
	if req.Data.Initiation.EndToEndIdentification == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.EndToEndIdentification is required")
	}
	if len(req.Data.Initiation.EndToEndIdentification) < 1 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.EndToEndIdentification must be at least 1 characters")
	}
	if len(req.Data.Initiation.EndToEndIdentification) > 35 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.EndToEndIdentification must be at most 35 characters")
	}
	if req.Data.Initiation.InstructedAmount == nil {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.InstructedAmount is required")
	}
	if req.Data.Initiation.InstructedAmount != nil && req.Data.Initiation.InstructedAmount.Amount == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.InstructedAmount.Amount is required")
	}
	if req.Data.Initiation.InstructedAmount != nil && !validate.MatchPattern("^\\d{1,13}\\.\\d{1,5}$", string(req.Data.Initiation.InstructedAmount.Amount)) {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.InstructedAmount.Amount must match pattern ^\\d{1,13}\\.\\d{1,5}$")
	}
	if req.Data.Initiation.InstructedAmount != nil && req.Data.Initiation.InstructedAmount.Currency == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.InstructedAmount.Currency is required")
	}
	if req.Data.Initiation.InstructedAmount != nil && !validate.MatchPattern("^[A-Z]{3,3}$", req.Data.Initiation.InstructedAmount.Currency) {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.InstructedAmount.Currency must match pattern ^[A-Z]{3,3}$")
	}
	if req.Data.Initiation.InstructionIdentification == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.InstructionIdentification is required")
	}
	if len(req.Data.Initiation.InstructionIdentification) < 1 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.InstructionIdentification must be at least 1 characters")
	}
	if len(req.Data.Initiation.InstructionIdentification) > 35 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.InstructionIdentification must be at most 35 characters")
	}
	r := transport.RawRequest{
		JSONBody: req,
	}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if xIdempotencyKey != "" {
		r.Headers.Set("x-idempotency-key", xIdempotencyKey)
	}
	if xJWSSignature != "" {
		r.Headers.Set("x-jws-signature", xJWSSignature)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodPost, "domestic-payment-consents", r)
	if err != nil {
		return nil, ResponseMetadata{}, err
	}
	var out ObwriteDomesticConsentResponse2
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, ResponseMetadata{}, err
		}
	}
	return &out, extractResponseMetadata(hdr), nil
}

// CreateConsentsSigned is CreateConsents with the raw response body and ResponseMetadata
// preserved alongside the typed payload. Use it when you need to verify
// the detached x-jws-signature header against the untouched bytes.
func (s *DomesticPayment) CreateConsentsSigned(ctx context.Context, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, xIdempotencyKey string, xJWSSignature string, xCustomerUserAgent string, req ObwriteDomesticConsent2) (*Signed[ObwriteDomesticConsentResponse2], error) {
	if xFAPIFinancialID == "" {
		return nil, errors.New("openbanking: x-fapi-financial-id is required")
	}
	if xIdempotencyKey == "" {
		return nil, errors.New("openbanking: x-idempotency-key is required")
	}
	if xJWSSignature == "" {
		return nil, errors.New("openbanking: x-jws-signature is required")
	}
	if req.Data.Initiation.CreditorAccount.Identification == "" {
		return nil, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.CreditorAccount.Identification is required")
	}
	if len(req.Data.Initiation.CreditorAccount.Identification) < 1 {
		return nil, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.CreditorAccount.Identification must be at least 1 characters")
	}
	if len(req.Data.Initiation.CreditorAccount.Identification) > 256 {
		return nil, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.CreditorAccount.Identification must be at most 256 characters")
	}
	if req.Data.Initiation.CreditorAccount.Name == "" {
		return nil, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.CreditorAccount.Name is required")
	}
	if len(req.Data.Initiation.CreditorAccount.Name) < 1 {
		return nil, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.CreditorAccount.Name must be at least 1 characters")
	}
	if len(req.Data.Initiation.CreditorAccount.Name) > 70 {
		return nil, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.CreditorAccount.Name must be at most 70 characters")
	}
	if req.Data.Initiation.CreditorAccount.SchemeName == "" {
		return nil, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.CreditorAccount.SchemeName is required")
	}
	if req.Data.Initiation.CreditorAccount.SecondaryIdentification != "" && len(req.Data.Initiation.CreditorAccount.SecondaryIdentification) < 1 {
		return nil, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.CreditorAccount.SecondaryIdentification must be at least 1 characters")
	}
	if req.Data.Initiation.CreditorAccount.SecondaryIdentification != "" && len(req.Data.Initiation.CreditorAccount.SecondaryIdentification) > 34 {
		return nil, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.CreditorAccount.SecondaryIdentification must be at most 34 characters")
	}
	if req.Data.Initiation.EndToEndIdentification == "" {
		return nil, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.EndToEndIdentification is required")
	}
	if len(req.Data.Initiation.EndToEndIdentification) < 1 {
		return nil, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.EndToEndIdentification must be at least 1 characters")
	}
	if len(req.Data.Initiation.EndToEndIdentification) > 35 {
		return nil, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.EndToEndIdentification must be at most 35 characters")
	}
	if req.Data.Initiation.InstructedAmount == nil {
		return nil, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.InstructedAmount is required")
	}
	if req.Data.Initiation.InstructedAmount != nil && req.Data.Initiation.InstructedAmount.Amount == "" {
		return nil, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.InstructedAmount.Amount is required")
	}
	if req.Data.Initiation.InstructedAmount != nil && !validate.MatchPattern("^\\d{1,13}\\.\\d{1,5}$", string(req.Data.Initiation.InstructedAmount.Amount)) {
		return nil, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.InstructedAmount.Amount must match pattern ^\\d{1,13}\\.\\d{1,5}$")
	}
	if req.Data.Initiation.InstructedAmount != nil && req.Data.Initiation.InstructedAmount.Currency == "" {
		return nil, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.InstructedAmount.Currency is required")
	}
	if req.Data.Initiation.InstructedAmount != nil && !validate.MatchPattern("^[A-Z]{3,3}$", req.Data.Initiation.InstructedAmount.Currency) {
		return nil, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.InstructedAmount.Currency must match pattern ^[A-Z]{3,3}$")
	}
	if req.Data.Initiation.InstructionIdentification == "" {
		return nil, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.InstructionIdentification is required")
	}
	if len(req.Data.Initiation.InstructionIdentification) < 1 {
		return nil, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.InstructionIdentification must be at least 1 characters")
	}
	if len(req.Data.Initiation.InstructionIdentification) > 35 {
		return nil, errors.New("openbanking: ObwriteDomesticConsent2.Data.Initiation.InstructionIdentification must be at most 35 characters")
	}
	r := transport.RawRequest{
		JSONBody: req,
	}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if xIdempotencyKey != "" {
		r.Headers.Set("x-idempotency-key", xIdempotencyKey)
	}
	if xJWSSignature != "" {
		r.Headers.Set("x-jws-signature", xJWSSignature)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodPost, "domestic-payment-consents", r)
	if err != nil {
		return nil, err
	}
	var out ObwriteDomesticConsentResponse2
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, err
		}
	}
	return &Signed[ObwriteDomesticConsentResponse2]{Typed: &out, Raw: body, Metadata: extractResponseMetadata(hdr)}, nil
}

// GetConsentsConsentID retrieve a domestic payment consent
//
// Get the details of a domestic payment consent.
//
// See also [Tutorials: Initiate your first payment](https://developer.revolut.com/docs/guides/build-banking-apps/tutorials/initiate-your-first-payment).
//
// Docs: https://developer.revolut.com/docs/openbanking/get-domestic-payment-consents-consent-id
// Required scopes: payments
func (s *DomesticPayment) GetConsentsConsentID(ctx context.Context, consentID string, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, xCustomerUserAgent string) (*ObwriteDomesticConsentResponse2, ResponseMetadata, error) {
	if consentID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ConsentId is required")
	}
	if xFAPIFinancialID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: x-fapi-financial-id is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodGet, "domestic-payment-consents/"+url.PathEscape(consentID), r)
	if err != nil {
		return nil, ResponseMetadata{}, err
	}
	var out ObwriteDomesticConsentResponse2
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, ResponseMetadata{}, err
		}
	}
	return &out, extractResponseMetadata(hdr), nil
}

// GetConsentsConsentIDSigned is GetConsentsConsentID with the raw response body and ResponseMetadata
// preserved alongside the typed payload. Use it when you need to verify
// the detached x-jws-signature header against the untouched bytes.
func (s *DomesticPayment) GetConsentsConsentIDSigned(ctx context.Context, consentID string, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, xCustomerUserAgent string) (*Signed[ObwriteDomesticConsentResponse2], error) {
	if consentID == "" {
		return nil, errors.New("openbanking: ConsentId is required")
	}
	if xFAPIFinancialID == "" {
		return nil, errors.New("openbanking: x-fapi-financial-id is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodGet, "domestic-payment-consents/"+url.PathEscape(consentID), r)
	if err != nil {
		return nil, err
	}
	var out ObwriteDomesticConsentResponse2
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, err
		}
	}
	return &Signed[ObwriteDomesticConsentResponse2]{Typed: &out, Raw: body, Metadata: extractResponseMetadata(hdr)}, nil
}

// GetConsentsConsentIDFundsConfirmation get funds confirmation for a domestic payment consent
//
// Check the funds for a domestic payment with the given consent.
// You can get the information only if the user has authorized the related consent.
//
// See also [Tutorials: Initiate your first payment](https://developer.revolut.com/docs/guides/build-banking-apps/tutorials/initiate-your-first-payment).
//
// Docs: https://developer.revolut.com/docs/openbanking/get-domestic-payment-consents-consent-id-funds-confirmation
// Required scopes: payments
func (s *DomesticPayment) GetConsentsConsentIDFundsConfirmation(ctx context.Context, consentID string, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, xCustomerUserAgent string) (*ObwriteFundsConfirmationResponse1, ResponseMetadata, error) {
	if consentID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ConsentId is required")
	}
	if xFAPIFinancialID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: x-fapi-financial-id is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodGet, "domestic-payment-consents/"+url.PathEscape(consentID)+"/funds-confirmation", r)
	if err != nil {
		return nil, ResponseMetadata{}, err
	}
	var out ObwriteFundsConfirmationResponse1
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, ResponseMetadata{}, err
		}
	}
	return &out, extractResponseMetadata(hdr), nil
}

// GetConsentsConsentIDFundsConfirmationSigned is GetConsentsConsentIDFundsConfirmation with the raw response body and ResponseMetadata
// preserved alongside the typed payload. Use it when you need to verify
// the detached x-jws-signature header against the untouched bytes.
func (s *DomesticPayment) GetConsentsConsentIDFundsConfirmationSigned(ctx context.Context, consentID string, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, xCustomerUserAgent string) (*Signed[ObwriteFundsConfirmationResponse1], error) {
	if consentID == "" {
		return nil, errors.New("openbanking: ConsentId is required")
	}
	if xFAPIFinancialID == "" {
		return nil, errors.New("openbanking: x-fapi-financial-id is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodGet, "domestic-payment-consents/"+url.PathEscape(consentID)+"/funds-confirmation", r)
	if err != nil {
		return nil, err
	}
	var out ObwriteFundsConfirmationResponse1
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, err
		}
	}
	return &Signed[ObwriteFundsConfirmationResponse1]{Typed: &out, Raw: body, Metadata: extractResponseMetadata(hdr)}, nil
}

// Create create a domestic payment
//
// Create a domestic payment.
//
// :::note
// As is defined in the Open Banking Specifications, the `/Data/Initiation` and the `/Data/Risk` sections of the request must be an exact match for the related consent passed in `ConsentId`.
// :::
//
// See also [Tutorials: Initiate your first payment](https://developer.revolut.com/docs/guides/build-banking-apps/tutorials/initiate-your-first-payment#6-initiate-the-domestic-payment).
//
// Docs: https://developer.revolut.com/docs/openbanking/create-domestic-payments
// Required scopes: payments
func (s *DomesticPayment) Create(ctx context.Context, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, xIdempotencyKey string, xJWSSignature string, xCustomerUserAgent string, req ObwriteDomestic2) (*ObwriteDomesticResponse2, ResponseMetadata, error) {
	if xFAPIFinancialID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: x-fapi-financial-id is required")
	}
	if xIdempotencyKey == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: x-idempotency-key is required")
	}
	if xJWSSignature == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: x-jws-signature is required")
	}
	if req.Data.ConsentID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomestic2.Data.ConsentId is required")
	}
	if len(req.Data.ConsentID) < 1 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomestic2.Data.ConsentId must be at least 1 characters")
	}
	if len(req.Data.ConsentID) > 128 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomestic2.Data.ConsentId must be at most 128 characters")
	}
	if req.Data.Initiation.CreditorAccount.Identification == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.CreditorAccount.Identification is required")
	}
	if len(req.Data.Initiation.CreditorAccount.Identification) < 1 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.CreditorAccount.Identification must be at least 1 characters")
	}
	if len(req.Data.Initiation.CreditorAccount.Identification) > 256 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.CreditorAccount.Identification must be at most 256 characters")
	}
	if req.Data.Initiation.CreditorAccount.Name == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.CreditorAccount.Name is required")
	}
	if len(req.Data.Initiation.CreditorAccount.Name) < 1 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.CreditorAccount.Name must be at least 1 characters")
	}
	if len(req.Data.Initiation.CreditorAccount.Name) > 70 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.CreditorAccount.Name must be at most 70 characters")
	}
	if req.Data.Initiation.CreditorAccount.SchemeName == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.CreditorAccount.SchemeName is required")
	}
	if req.Data.Initiation.CreditorAccount.SecondaryIdentification != "" && len(req.Data.Initiation.CreditorAccount.SecondaryIdentification) < 1 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.CreditorAccount.SecondaryIdentification must be at least 1 characters")
	}
	if req.Data.Initiation.CreditorAccount.SecondaryIdentification != "" && len(req.Data.Initiation.CreditorAccount.SecondaryIdentification) > 34 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.CreditorAccount.SecondaryIdentification must be at most 34 characters")
	}
	if req.Data.Initiation.EndToEndIdentification == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.EndToEndIdentification is required")
	}
	if len(req.Data.Initiation.EndToEndIdentification) < 1 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.EndToEndIdentification must be at least 1 characters")
	}
	if len(req.Data.Initiation.EndToEndIdentification) > 35 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.EndToEndIdentification must be at most 35 characters")
	}
	if req.Data.Initiation.InstructedAmount == nil {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.InstructedAmount is required")
	}
	if req.Data.Initiation.InstructedAmount != nil && req.Data.Initiation.InstructedAmount.Amount == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.InstructedAmount.Amount is required")
	}
	if req.Data.Initiation.InstructedAmount != nil && !validate.MatchPattern("^\\d{1,13}\\.\\d{1,5}$", string(req.Data.Initiation.InstructedAmount.Amount)) {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.InstructedAmount.Amount must match pattern ^\\d{1,13}\\.\\d{1,5}$")
	}
	if req.Data.Initiation.InstructedAmount != nil && req.Data.Initiation.InstructedAmount.Currency == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.InstructedAmount.Currency is required")
	}
	if req.Data.Initiation.InstructedAmount != nil && !validate.MatchPattern("^[A-Z]{3,3}$", req.Data.Initiation.InstructedAmount.Currency) {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.InstructedAmount.Currency must match pattern ^[A-Z]{3,3}$")
	}
	if req.Data.Initiation.InstructionIdentification == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.InstructionIdentification is required")
	}
	if len(req.Data.Initiation.InstructionIdentification) < 1 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.InstructionIdentification must be at least 1 characters")
	}
	if len(req.Data.Initiation.InstructionIdentification) > 35 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.InstructionIdentification must be at most 35 characters")
	}
	r := transport.RawRequest{
		JSONBody: req,
	}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if xIdempotencyKey != "" {
		r.Headers.Set("x-idempotency-key", xIdempotencyKey)
	}
	if xJWSSignature != "" {
		r.Headers.Set("x-jws-signature", xJWSSignature)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodPost, "domestic-payments", r)
	if err != nil {
		return nil, ResponseMetadata{}, err
	}
	var out ObwriteDomesticResponse2
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, ResponseMetadata{}, err
		}
	}
	return &out, extractResponseMetadata(hdr), nil
}

// CreateSigned is Create with the raw response body and ResponseMetadata
// preserved alongside the typed payload. Use it when you need to verify
// the detached x-jws-signature header against the untouched bytes.
func (s *DomesticPayment) CreateSigned(ctx context.Context, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, xIdempotencyKey string, xJWSSignature string, xCustomerUserAgent string, req ObwriteDomestic2) (*Signed[ObwriteDomesticResponse2], error) {
	if xFAPIFinancialID == "" {
		return nil, errors.New("openbanking: x-fapi-financial-id is required")
	}
	if xIdempotencyKey == "" {
		return nil, errors.New("openbanking: x-idempotency-key is required")
	}
	if xJWSSignature == "" {
		return nil, errors.New("openbanking: x-jws-signature is required")
	}
	if req.Data.ConsentID == "" {
		return nil, errors.New("openbanking: ObwriteDomestic2.Data.ConsentId is required")
	}
	if len(req.Data.ConsentID) < 1 {
		return nil, errors.New("openbanking: ObwriteDomestic2.Data.ConsentId must be at least 1 characters")
	}
	if len(req.Data.ConsentID) > 128 {
		return nil, errors.New("openbanking: ObwriteDomestic2.Data.ConsentId must be at most 128 characters")
	}
	if req.Data.Initiation.CreditorAccount.Identification == "" {
		return nil, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.CreditorAccount.Identification is required")
	}
	if len(req.Data.Initiation.CreditorAccount.Identification) < 1 {
		return nil, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.CreditorAccount.Identification must be at least 1 characters")
	}
	if len(req.Data.Initiation.CreditorAccount.Identification) > 256 {
		return nil, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.CreditorAccount.Identification must be at most 256 characters")
	}
	if req.Data.Initiation.CreditorAccount.Name == "" {
		return nil, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.CreditorAccount.Name is required")
	}
	if len(req.Data.Initiation.CreditorAccount.Name) < 1 {
		return nil, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.CreditorAccount.Name must be at least 1 characters")
	}
	if len(req.Data.Initiation.CreditorAccount.Name) > 70 {
		return nil, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.CreditorAccount.Name must be at most 70 characters")
	}
	if req.Data.Initiation.CreditorAccount.SchemeName == "" {
		return nil, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.CreditorAccount.SchemeName is required")
	}
	if req.Data.Initiation.CreditorAccount.SecondaryIdentification != "" && len(req.Data.Initiation.CreditorAccount.SecondaryIdentification) < 1 {
		return nil, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.CreditorAccount.SecondaryIdentification must be at least 1 characters")
	}
	if req.Data.Initiation.CreditorAccount.SecondaryIdentification != "" && len(req.Data.Initiation.CreditorAccount.SecondaryIdentification) > 34 {
		return nil, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.CreditorAccount.SecondaryIdentification must be at most 34 characters")
	}
	if req.Data.Initiation.EndToEndIdentification == "" {
		return nil, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.EndToEndIdentification is required")
	}
	if len(req.Data.Initiation.EndToEndIdentification) < 1 {
		return nil, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.EndToEndIdentification must be at least 1 characters")
	}
	if len(req.Data.Initiation.EndToEndIdentification) > 35 {
		return nil, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.EndToEndIdentification must be at most 35 characters")
	}
	if req.Data.Initiation.InstructedAmount == nil {
		return nil, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.InstructedAmount is required")
	}
	if req.Data.Initiation.InstructedAmount != nil && req.Data.Initiation.InstructedAmount.Amount == "" {
		return nil, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.InstructedAmount.Amount is required")
	}
	if req.Data.Initiation.InstructedAmount != nil && !validate.MatchPattern("^\\d{1,13}\\.\\d{1,5}$", string(req.Data.Initiation.InstructedAmount.Amount)) {
		return nil, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.InstructedAmount.Amount must match pattern ^\\d{1,13}\\.\\d{1,5}$")
	}
	if req.Data.Initiation.InstructedAmount != nil && req.Data.Initiation.InstructedAmount.Currency == "" {
		return nil, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.InstructedAmount.Currency is required")
	}
	if req.Data.Initiation.InstructedAmount != nil && !validate.MatchPattern("^[A-Z]{3,3}$", req.Data.Initiation.InstructedAmount.Currency) {
		return nil, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.InstructedAmount.Currency must match pattern ^[A-Z]{3,3}$")
	}
	if req.Data.Initiation.InstructionIdentification == "" {
		return nil, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.InstructionIdentification is required")
	}
	if len(req.Data.Initiation.InstructionIdentification) < 1 {
		return nil, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.InstructionIdentification must be at least 1 characters")
	}
	if len(req.Data.Initiation.InstructionIdentification) > 35 {
		return nil, errors.New("openbanking: ObwriteDomestic2.Data.Initiation.InstructionIdentification must be at most 35 characters")
	}
	r := transport.RawRequest{
		JSONBody: req,
	}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if xIdempotencyKey != "" {
		r.Headers.Set("x-idempotency-key", xIdempotencyKey)
	}
	if xJWSSignature != "" {
		r.Headers.Set("x-jws-signature", xJWSSignature)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodPost, "domestic-payments", r)
	if err != nil {
		return nil, err
	}
	var out ObwriteDomesticResponse2
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, err
		}
	}
	return &Signed[ObwriteDomesticResponse2]{Typed: &out, Raw: body, Metadata: extractResponseMetadata(hdr)}, nil
}

// GetDomesticPaymentID retrieve a domestic payment
//
// Get the status of a domestic payment.
//
// See also [Tutorials: Initiate your first payment](https://developer.revolut.com/docs/guides/build-banking-apps/tutorials/initiate-your-first-payment#7-check-the-status-of-the-payment).
//
// Docs: https://developer.revolut.com/docs/openbanking/get-domestic-payments-domestic-payment-id
// Required scopes: payments
func (s *DomesticPayment) GetDomesticPaymentID(ctx context.Context, domesticPaymentID string, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, xCustomerUserAgent string) (*ObwriteDomesticResponse2, ResponseMetadata, error) {
	if domesticPaymentID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: DomesticPaymentId is required")
	}
	if xFAPIFinancialID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: x-fapi-financial-id is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodGet, "domestic-payments/"+url.PathEscape(domesticPaymentID), r)
	if err != nil {
		return nil, ResponseMetadata{}, err
	}
	var out ObwriteDomesticResponse2
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, ResponseMetadata{}, err
		}
	}
	return &out, extractResponseMetadata(hdr), nil
}

// GetDomesticPaymentIDSigned is GetDomesticPaymentID with the raw response body and ResponseMetadata
// preserved alongside the typed payload. Use it when you need to verify
// the detached x-jws-signature header against the untouched bytes.
func (s *DomesticPayment) GetDomesticPaymentIDSigned(ctx context.Context, domesticPaymentID string, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, xCustomerUserAgent string) (*Signed[ObwriteDomesticResponse2], error) {
	if domesticPaymentID == "" {
		return nil, errors.New("openbanking: DomesticPaymentId is required")
	}
	if xFAPIFinancialID == "" {
		return nil, errors.New("openbanking: x-fapi-financial-id is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodGet, "domestic-payments/"+url.PathEscape(domesticPaymentID), r)
	if err != nil {
		return nil, err
	}
	var out ObwriteDomesticResponse2
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, err
		}
	}
	return &Signed[ObwriteDomesticResponse2]{Typed: &out, Raw: body, Metadata: extractResponseMetadata(hdr)}, nil
}
