// Code generated by revogen. DO NOT EDIT.

package openbanking

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"net/url"

	"github.com/greatliontech/revolut-go/internal/transport"
)

// FilePayment groups the FilePayment endpoints.
type FilePayment struct {
	t *transport.Transport
}

// CreateConsents create a file payment consent
//
// Docs: https://developer.revolut.com/docs/openbanking/create-file-payment-consents
// Required scopes: payments
func (s *FilePayment) CreateConsents(ctx context.Context, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, authorization string, xIdempotencyKey string, xJWSSignature string, xCustomerUserAgent string, req ObwriteFileConsent2) (*ObwriteFileConsentResponse2, error) {
	if req.Data.Initiation.FileHash == "" {
		return nil, errors.New("openbanking: ObwriteFileConsent2.Data.Initiation.FileHash is required")
	}
	if req.Data.Initiation.FileType == "" {
		return nil, errors.New("openbanking: ObwriteFileConsent2.Data.Initiation.FileType is required")
	}
	r := transport.RawRequest{
		JSONBody: req,
	}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if xIdempotencyKey != "" {
		r.Headers.Set("x-idempotency-key", xIdempotencyKey)
	}
	if xJWSSignature != "" {
		r.Headers.Set("x-jws-signature", xJWSSignature)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodPost, "file-payment-consents", r)
	if err != nil {
		return nil, err
	}
	var out ObwriteFileConsentResponse2
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetConsentsConsentID retrieve a file payment consent
//
// Docs: https://developer.revolut.com/docs/openbanking/get-file-payment-consents-consent-id
// Required scopes: payments
func (s *FilePayment) GetConsentsConsentID(ctx context.Context, consentID string, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, authorization string, xCustomerUserAgent string) (*ObwriteFileConsentResponse2, error) {
	if consentID == "" {
		return nil, errors.New("openbanking: ConsentId is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodGet, "file-payment-consents/"+url.PathEscape(consentID), r)
	if err != nil {
		return nil, err
	}
	var out ObwriteFileConsentResponse2
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetConsentsConsentIDFile retrieve an uploaded payment file
//
// Docs: https://developer.revolut.com/docs/openbanking/get-file-payment-consents-consent-id-file
// Required scopes: payments
func (s *FilePayment) GetConsentsConsentIDFile(ctx context.Context, consentID string, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, authorization string, xCustomerUserAgent string) ([]byte, error) {
	if consentID == "" {
		return nil, errors.New("openbanking: ConsentId is required")
	}
	r := transport.RawRequest{
		Accept: "text/csv",
	}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodGet, "file-payment-consents/"+url.PathEscape(consentID)+"/file", r)
	if err != nil {
		return nil, err
	}
	return body, nil
}

// CreateConsentsConsentIDFile upload a payment file
//
// Docs: https://developer.revolut.com/docs/openbanking/create-file-payment-consents-consent-id-file
// Required scopes: payments
func (s *FilePayment) CreateConsentsConsentIDFile(ctx context.Context, consentID string, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, authorization string, xIdempotencyKey string, xJWSSignature string, xCustomerUserAgent string) (*EmptyBody, error) {
	if consentID == "" {
		return nil, errors.New("openbanking: ConsentId is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if xIdempotencyKey != "" {
		r.Headers.Set("x-idempotency-key", xIdempotencyKey)
	}
	if xJWSSignature != "" {
		r.Headers.Set("x-jws-signature", xJWSSignature)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodPost, "file-payment-consents/"+url.PathEscape(consentID)+"/file", r)
	if err != nil {
		return nil, err
	}
	var out EmptyBody
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Create create a file payment
//
// Docs: https://developer.revolut.com/docs/openbanking/create-file-payments
// Required scopes: payments
func (s *FilePayment) Create(ctx context.Context, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, authorization string, xIdempotencyKey string, xJWSSignature string, xCustomerUserAgent string, req ObwriteFile2) (*ObwriteFileResponse2, error) {
	if req.Data.ConsentID == "" {
		return nil, errors.New("openbanking: ObwriteFile2.Data.ConsentId is required")
	}
	if req.Data.Initiation.FileHash == "" {
		return nil, errors.New("openbanking: ObwriteFile2.Data.Initiation.FileHash is required")
	}
	if req.Data.Initiation.FileType == "" {
		return nil, errors.New("openbanking: ObwriteFile2.Data.Initiation.FileType is required")
	}
	r := transport.RawRequest{
		JSONBody: req,
	}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if xIdempotencyKey != "" {
		r.Headers.Set("x-idempotency-key", xIdempotencyKey)
	}
	if xJWSSignature != "" {
		r.Headers.Set("x-jws-signature", xJWSSignature)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodPost, "file-payments", r)
	if err != nil {
		return nil, err
	}
	var out ObwriteFileResponse2
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetFilePaymentID retrieve a file payment
//
// Docs: https://developer.revolut.com/docs/openbanking/get-file-payments-file-payment-id
// Required scopes: payments
func (s *FilePayment) GetFilePaymentID(ctx context.Context, filePaymentID string, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, authorization string, xCustomerUserAgent string) (*ObwriteFileResponse2, error) {
	if filePaymentID == "" {
		return nil, errors.New("openbanking: FilePaymentId is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodGet, "file-payments/"+url.PathEscape(filePaymentID), r)
	if err != nil {
		return nil, err
	}
	var out ObwriteFileResponse2
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetFilePaymentIDReportFile retrieve all payments of a file payment
//
// Docs: https://developer.revolut.com/docs/openbanking/get-file-payments-file-payment-id-report-file
// Required scopes: payments
func (s *FilePayment) GetFilePaymentIDReportFile(ctx context.Context, filePaymentID string, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, authorization string, xCustomerUserAgent string) (*ObreportFileResponse, error) {
	if filePaymentID == "" {
		return nil, errors.New("openbanking: FilePaymentId is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodGet, "file-payments/"+url.PathEscape(filePaymentID)+"/report-file", r)
	if err != nil {
		return nil, err
	}
	var out ObreportFileResponse
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
