// Code generated by revogen. DO NOT EDIT.

package openbanking

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"net/url"

	"github.com/greatliontech/revolut-go/internal/transport"
)

// Transactions groups the Transactions endpoints.
type Transactions struct {
	t *transport.Transport
}

// GetAccountsAccountIDDirectDebits retrieve all account's direct debits
//
// Get a list of all the direct debits for a specific user account.
//
// :::note
// In compliance with PSD2 SCA regulations, access to this endpoint is only allowed within the first 5 minutes after the Revolut user has authorised the consent.
// After those 5 minutes, access to this endpoint is denied, and an HTTP `403` error is returned.
// :::
//
// See also [Tutorials: Get account and transaction information](https://developer.revolut.com/docs/guides/build-banking-apps/tutorials/get-account-and-transaction-information).
//
// Docs: https://developer.revolut.com/docs/openbanking/get-accounts-account-id-direct-debits
// Required scopes: accounts
func (s *Transactions) GetAccountsAccountIDDirectDebits(ctx context.Context, accountID string, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, xCustomerUserAgent string) (*ObreadDirectDebit1, ResponseMetadata, error) {
	if accountID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: AccountId is required")
	}
	if xFAPIFinancialID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: x-fapi-financial-id is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodGet, "accounts/"+url.PathEscape(accountID)+"/direct-debits", r)
	if err != nil {
		return nil, ResponseMetadata{}, err
	}
	var out ObreadDirectDebit1
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, ResponseMetadata{}, err
		}
	}
	return &out, extractResponseMetadata(hdr), nil
}

// GetAccountsAccountIDStandingOrders retrieve all account's standing orders
//
// Get a list of all the standing orders for a specific user account.
//
// :::note
// In compliance with PSD2 SCA regulations, access to this endpoint is only allowed within the first 5 minutes after the Revolut user has authorised the consent.
// After those 5 minutes, access to this endpoint is denied, and an HTTP `403` error is returned.
// :::
//
// See also [Tutorials: Get account and transaction information](https://developer.revolut.com/docs/guides/build-banking-apps/tutorials/get-account-and-transaction-information).
//
// Docs: https://developer.revolut.com/docs/openbanking/get-accounts-account-id-standing-orders
// Required scopes: accounts
func (s *Transactions) GetAccountsAccountIDStandingOrders(ctx context.Context, accountID string, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, xCustomerUserAgent string) (*ObreadStandingOrder4, ResponseMetadata, error) {
	if accountID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: AccountId is required")
	}
	if xFAPIFinancialID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: x-fapi-financial-id is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodGet, "accounts/"+url.PathEscape(accountID)+"/standing-orders", r)
	if err != nil {
		return nil, ResponseMetadata{}, err
	}
	var out ObreadStandingOrder4
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, ResponseMetadata{}, err
		}
	}
	return &out, extractResponseMetadata(hdr), nil
}

// GetAccountsAccountIDTransactions retrieve all transactions
//
// Get all the recent transactions for an account.
//
// :::note
// In compliance with PSD2 SCA regulations, full transaction history can only be accessed within the first 5 minutes after the Revolut user has authorised the consent.
// After those 5 minutes, transaction history is restricted to the last 90 days counting from the moment the API request is made, and older transactions are not returned.
//
// Additionally, after those 5 minutes, unless the user is present and actively requesting data, you should not retrieve transaction data of an individual account more than 4 times within a 24-hour period.
// :::
//
// See also [Tutorials: Get account and transaction information](https://developer.revolut.com/docs/guides/build-banking-apps/tutorials/get-account-and-transaction-information).
//
// Docs: https://developer.revolut.com/docs/openbanking/get-accounts-account-id-transactions
// Required scopes: accounts
func (s *Transactions) GetAccountsAccountIDTransactions(ctx context.Context, accountID string, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, xCustomerUserAgent string, opts *GetAccountsAccountIDTransactionsParams) (*ObreadTransaction4, ResponseMetadata, error) {
	if accountID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: AccountId is required")
	}
	if xFAPIFinancialID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: x-fapi-financial-id is required")
	}
	path := "accounts/" + url.PathEscape(accountID) + "/transactions"
	if q := opts.encode().Encode(); q != "" {
		path += "?" + q
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodGet, path, r)
	if err != nil {
		return nil, ResponseMetadata{}, err
	}
	var out ObreadTransaction4
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, ResponseMetadata{}, err
		}
	}
	return &out, extractResponseMetadata(hdr), nil
}
