// Code generated by revogen. DO NOT EDIT.

package openbanking

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"net/url"

	"github.com/greatliontech/revolut-go/internal/transport"
)

// Accounts groups the Accounts endpoints.
type Accounts struct {
	t *transport.Transport
}

// CreateAccessConsents create an account access consent
//
// Before you can access any data from a Revolut user, you must create an access consent to read data from the user's profile.
//
// :::note
// When you create an account access consent, you must include a specific permission that follows the rules in the table below; otherwise, you get a `400 Bad request` error.
// :::
//
// **Request Permissions**
//
// | PERMISSIONS | DEPENDENCIES |
// |--|--|
// | ReadAccountsBasic | None |
// | ReadAccountsDetail |None|
// | ReadBalances |None|
// | ReadBeneficiariesBasic |None|
// | ReadBeneficiariesDetail |None|
// | ReadDirectDebits |None|
// | ReadScheduledPaymentsBasic |None|
// | ReadScheduledPaymentsDetail |None|
// | ReadStandingOrdersBasic |None|
// | ReadStandingOrdersDetail |None|
// | ReadTransactionsBasic |None|
// | ReadTransactionsCredits |ReadTransactionsBasic OR ReadTransactionsDetail|
// |ReadTransactionsDebits |ReadTransactionsBasic OR ReadTransactionsDetail|
// | ReadTransactionsDetail | None |
//
// See also [Tutorials: Get account and transaction information](https://developer.revolut.com/docs/guides/build-banking-apps/tutorials/get-account-and-transaction-information#2-create-an-account-access-consent).
//
// Docs: https://developer.revolut.com/docs/openbanking/create-account-access-consents
// Required scopes: accounts
func (s *Accounts) CreateAccessConsents(ctx context.Context, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, xCustomerUserAgent string, req ObreadConsent1) (*ObreadConsentResponse1, ResponseMetadata, error) {
	if xFAPIFinancialID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: x-fapi-financial-id is required")
	}
	if len(req.Data.Permissions) == 0 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObreadConsent1.Data.Permissions is required")
	}
	if len(req.Data.Permissions) > 0 && uint64(len(req.Data.Permissions)) < 1 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObreadConsent1.Data.Permissions must contain at least 1 items")
	}
	if uint64(len(req.Data.Permissions)) < 1 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObreadConsent1.Data.Permissions must contain at least 1 items")
	}
	r := transport.RawRequest{
		JSONBody: req,
	}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodPost, "account-access-consents", r)
	if err != nil {
		return nil, ResponseMetadata{}, err
	}
	var out ObreadConsentResponse1
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, ResponseMetadata{}, err
		}
	}
	return &out, extractResponseMetadata(hdr), nil
}

// GetAccessConsentsConsentID retrieve an account access consent
//
// Get the details of the account access consent as described in the Open Banking [official documentation](https://openbanking.atlassian.net/wiki/spaces/DZ/pages/999622968/Account+and+Transaction+API+Specification+-+v3.1.1).
//
// See also [Tutorials: Get account and transaction information](https://developer.revolut.com/docs/guides/build-banking-apps/tutorials/get-account-and-transaction-information).
//
// Docs: https://developer.revolut.com/docs/openbanking/get-account-access-consents-consent-id
// Required scopes: accounts
func (s *Accounts) GetAccessConsentsConsentID(ctx context.Context, consentID string, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, xCustomerUserAgent string) (*ObreadConsentResponse1, ResponseMetadata, error) {
	if consentID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ConsentId is required")
	}
	if xFAPIFinancialID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: x-fapi-financial-id is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodGet, "account-access-consents/"+url.PathEscape(consentID), r)
	if err != nil {
		return nil, ResponseMetadata{}, err
	}
	var out ObreadConsentResponse1
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, ResponseMetadata{}, err
		}
	}
	return &out, extractResponseMetadata(hdr), nil
}

// DeleteAccessConsentsConsentID delete an account access consent
//
// Use this endpoint to:
//
// - Reject a consent if it is in the `AwaitingAuthorisation` state or any error occurs while the consent is being authorised.
//
// - Revoke a consent if it is in the `Authorised` state.
//
// See also [Tutorials: Get account and transaction information](https://developer.revolut.com/docs/guides/build-banking-apps/tutorials/get-account-and-transaction-information).
//
// Docs: https://developer.revolut.com/docs/openbanking/delete-account-access-consents-consent-id
// Required scopes: accounts
func (s *Accounts) DeleteAccessConsentsConsentID(ctx context.Context, consentID string, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, xCustomerUserAgent string) (ResponseMetadata, error) {
	if consentID == "" {
		return ResponseMetadata{}, errors.New("openbanking: ConsentId is required")
	}
	if xFAPIFinancialID == "" {
		return ResponseMetadata{}, errors.New("openbanking: x-fapi-financial-id is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodDelete, "account-access-consents/"+url.PathEscape(consentID), r)
	if err != nil {
		return ResponseMetadata{}, err
	}
	_ = body
	return extractResponseMetadata(hdr), nil
}

// List retrieve all accounts
//
// Get a list of user accounts.
//
// See also [Tutorials: Get account and transaction information](https://developer.revolut.com/docs/guides/build-banking-apps/tutorials/get-account-and-transaction-information#6-get-the-list-of-accounts).
//
// Docs: https://developer.revolut.com/docs/openbanking/get-accounts
// Required scopes: accounts
func (s *Accounts) List(ctx context.Context, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, xCustomerUserAgent string) (*ObreadAccount3, ResponseMetadata, error) {
	if xFAPIFinancialID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: x-fapi-financial-id is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodGet, "accounts", r)
	if err != nil {
		return nil, ResponseMetadata{}, err
	}
	var out ObreadAccount3
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, ResponseMetadata{}, err
		}
	}
	return &out, extractResponseMetadata(hdr), nil
}

// GetAccountID retrieve an account
//
// Get the information about a specific account by ID.
//
// :::note
// In compliance with PSD2 SCA regulations, access to this endpoint is only allowed within the first 5 minutes after the Revolut user has authorised the consent.
// After those 5 minutes, access to this endpoint is denied, and an HTTP `403` error is returned.
// :::
//
// See also [Tutorials: Get account and transaction information](https://developer.revolut.com/docs/guides/build-banking-apps/tutorials/get-account-and-transaction-information).
//
// Docs: https://developer.revolut.com/docs/openbanking/get-accounts-account-id
// Required scopes: accounts
func (s *Accounts) GetAccountID(ctx context.Context, accountID string, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, xCustomerUserAgent string) (*ObreadAccount3, ResponseMetadata, error) {
	if accountID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: AccountId is required")
	}
	if xFAPIFinancialID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: x-fapi-financial-id is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodGet, "accounts/"+url.PathEscape(accountID), r)
	if err != nil {
		return nil, ResponseMetadata{}, err
	}
	var out ObreadAccount3
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, ResponseMetadata{}, err
		}
	}
	return &out, extractResponseMetadata(hdr), nil
}

// GetAccountIDBalances retrieve an account balance
//
// Get the balance of an account.
//
// See also [Tutorials: Get account and transaction information](https://developer.revolut.com/docs/guides/build-banking-apps/tutorials/get-account-and-transaction-information).
//
// Docs: https://developer.revolut.com/docs/openbanking/get-accounts-account-id-balances
// Required scopes: accounts
func (s *Accounts) GetAccountIDBalances(ctx context.Context, accountID string, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, xCustomerUserAgent string) (*ObreadBalance1, ResponseMetadata, error) {
	if accountID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: AccountId is required")
	}
	if xFAPIFinancialID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: x-fapi-financial-id is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodGet, "accounts/"+url.PathEscape(accountID)+"/balances", r)
	if err != nil {
		return nil, ResponseMetadata{}, err
	}
	var out ObreadBalance1
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, ResponseMetadata{}, err
		}
	}
	return &out, extractResponseMetadata(hdr), nil
}

// GetAccountIDBeneficiaries retrieve all account's beneficiaries
//
// Get all the beneficiaries of a specific user account.
//
// :::note
// In compliance with PSD2 SCA regulations, access to this endpoint is only allowed within the first 5 minutes after the Revolut user has authorised the consent.
// After those 5 minutes, access to this endpoint is denied, and an HTTP `403` error is returned.
// :::
//
// See also [Tutorials: Get account and transaction information](https://developer.revolut.com/docs/guides/build-banking-apps/tutorials/get-account-and-transaction-information).
//
// Docs: https://developer.revolut.com/docs/openbanking/get-accounts-account-id-beneficiaries
// Required scopes: accounts
func (s *Accounts) GetAccountIDBeneficiaries(ctx context.Context, accountID string, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, xCustomerUserAgent string) (*ObreadBeneficiary3, ResponseMetadata, error) {
	if accountID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: AccountId is required")
	}
	if xFAPIFinancialID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: x-fapi-financial-id is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodGet, "accounts/"+url.PathEscape(accountID)+"/beneficiaries", r)
	if err != nil {
		return nil, ResponseMetadata{}, err
	}
	var out ObreadBeneficiary3
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, ResponseMetadata{}, err
		}
	}
	return &out, extractResponseMetadata(hdr), nil
}
