// Code generated by revogen. DO NOT EDIT.

package openbanking

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"net/url"

	"github.com/greatliontech/revolut-go/internal/transport"
)

// DomesticStandingOrder groups the DomesticStandingOrder endpoints.
type DomesticStandingOrder struct {
	t *transport.Transport
}

// CreateConsents create a domestic standing order consent
//
// Docs: https://developer.revolut.com/docs/openbanking/create-domestic-standing-order-consents
// Required scopes: payments
func (s *DomesticStandingOrder) CreateConsents(ctx context.Context, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, xIdempotencyKey string, xJWSSignature string, xCustomerUserAgent string, req ObwriteDomesticStandingOrderConsent2) (*ObwriteDomesticStandingOrderConsentResponse2, ResponseMetadata, error) {
	if xFAPIFinancialID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: x-fapi-financial-id is required")
	}
	if xIdempotencyKey == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: x-idempotency-key is required")
	}
	if xJWSSignature == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: x-jws-signature is required")
	}
	if req.Data.Initiation.CreditorAccount.Identification == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.CreditorAccount.Identification is required")
	}
	if len(req.Data.Initiation.CreditorAccount.Identification) < 1 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.CreditorAccount.Identification must be at least 1 characters")
	}
	if len(req.Data.Initiation.CreditorAccount.Identification) > 256 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.CreditorAccount.Identification must be at most 256 characters")
	}
	if req.Data.Initiation.CreditorAccount.Name == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.CreditorAccount.Name is required")
	}
	if len(req.Data.Initiation.CreditorAccount.Name) < 1 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.CreditorAccount.Name must be at least 1 characters")
	}
	if len(req.Data.Initiation.CreditorAccount.Name) > 70 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.CreditorAccount.Name must be at most 70 characters")
	}
	if req.Data.Initiation.CreditorAccount.SchemeName == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.CreditorAccount.SchemeName is required")
	}
	if req.Data.Initiation.CreditorAccount.SecondaryIdentification != "" && len(req.Data.Initiation.CreditorAccount.SecondaryIdentification) < 1 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.CreditorAccount.SecondaryIdentification must be at least 1 characters")
	}
	if req.Data.Initiation.CreditorAccount.SecondaryIdentification != "" && len(req.Data.Initiation.CreditorAccount.SecondaryIdentification) > 34 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.CreditorAccount.SecondaryIdentification must be at most 34 characters")
	}
	if req.Data.Initiation.FirstPaymentAmount == nil {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.FirstPaymentAmount is required")
	}
	if req.Data.Initiation.FirstPaymentAmount != nil && req.Data.Initiation.FirstPaymentAmount.Amount == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.FirstPaymentAmount.Amount is required")
	}
	if req.Data.Initiation.FirstPaymentAmount != nil && !mustMatchPattern("^\\d{1,13}\\.\\d{1,5}$", string(req.Data.Initiation.FirstPaymentAmount.Amount)) {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.FirstPaymentAmount.Amount must match pattern ^\\d{1,13}\\.\\d{1,5}$")
	}
	if req.Data.Initiation.FirstPaymentAmount != nil && req.Data.Initiation.FirstPaymentAmount.Currency == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.FirstPaymentAmount.Currency is required")
	}
	if req.Data.Initiation.FirstPaymentAmount != nil && !mustMatchPattern("^[A-Z]{3,3}$", req.Data.Initiation.FirstPaymentAmount.Currency) {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.FirstPaymentAmount.Currency must match pattern ^[A-Z]{3,3}$")
	}
	if req.Data.Initiation.FirstPaymentDateTime.IsZero() {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.FirstPaymentDateTime is required")
	}
	if req.Data.Initiation.Frequency == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.Frequency is required")
	}
	if len(req.Data.Initiation.Frequency) < 1 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.Frequency must be at least 1 characters")
	}
	if len(req.Data.Initiation.Frequency) > 35 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.Frequency must be at most 35 characters")
	}
	if req.Data.Initiation.NumberOfPayments != "" && len(req.Data.Initiation.NumberOfPayments) < 1 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.NumberOfPayments must be at least 1 characters")
	}
	if req.Data.Initiation.NumberOfPayments != "" && len(req.Data.Initiation.NumberOfPayments) > 35 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.NumberOfPayments must be at most 35 characters")
	}
	if req.Data.Initiation.Reference != "" && len(req.Data.Initiation.Reference) < 1 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.Reference must be at least 1 characters")
	}
	if req.Data.Initiation.Reference != "" && len(req.Data.Initiation.Reference) > 35 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.Reference must be at most 35 characters")
	}
	if req.Data.Permission == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Permission is required")
	}
	r := transport.RawRequest{
		JSONBody: req,
	}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if xIdempotencyKey != "" {
		r.Headers.Set("x-idempotency-key", xIdempotencyKey)
	}
	if xJWSSignature != "" {
		r.Headers.Set("x-jws-signature", xJWSSignature)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodPost, "domestic-standing-order-consents", r)
	if err != nil {
		return nil, ResponseMetadata{}, err
	}
	var out ObwriteDomesticStandingOrderConsentResponse2
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, ResponseMetadata{}, err
		}
	}
	return &out, extractResponseMetadata(hdr), nil
}

// CreateConsentsSigned is CreateConsents with the raw response body and ResponseMetadata
// preserved alongside the typed payload. Use it when you need to verify
// the detached x-jws-signature header against the untouched bytes.
func (s *DomesticStandingOrder) CreateConsentsSigned(ctx context.Context, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, xIdempotencyKey string, xJWSSignature string, xCustomerUserAgent string, req ObwriteDomesticStandingOrderConsent2) (*Signed[ObwriteDomesticStandingOrderConsentResponse2], error) {
	if xFAPIFinancialID == "" {
		return nil, errors.New("openbanking: x-fapi-financial-id is required")
	}
	if xIdempotencyKey == "" {
		return nil, errors.New("openbanking: x-idempotency-key is required")
	}
	if xJWSSignature == "" {
		return nil, errors.New("openbanking: x-jws-signature is required")
	}
	if req.Data.Initiation.CreditorAccount.Identification == "" {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.CreditorAccount.Identification is required")
	}
	if len(req.Data.Initiation.CreditorAccount.Identification) < 1 {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.CreditorAccount.Identification must be at least 1 characters")
	}
	if len(req.Data.Initiation.CreditorAccount.Identification) > 256 {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.CreditorAccount.Identification must be at most 256 characters")
	}
	if req.Data.Initiation.CreditorAccount.Name == "" {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.CreditorAccount.Name is required")
	}
	if len(req.Data.Initiation.CreditorAccount.Name) < 1 {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.CreditorAccount.Name must be at least 1 characters")
	}
	if len(req.Data.Initiation.CreditorAccount.Name) > 70 {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.CreditorAccount.Name must be at most 70 characters")
	}
	if req.Data.Initiation.CreditorAccount.SchemeName == "" {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.CreditorAccount.SchemeName is required")
	}
	if req.Data.Initiation.CreditorAccount.SecondaryIdentification != "" && len(req.Data.Initiation.CreditorAccount.SecondaryIdentification) < 1 {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.CreditorAccount.SecondaryIdentification must be at least 1 characters")
	}
	if req.Data.Initiation.CreditorAccount.SecondaryIdentification != "" && len(req.Data.Initiation.CreditorAccount.SecondaryIdentification) > 34 {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.CreditorAccount.SecondaryIdentification must be at most 34 characters")
	}
	if req.Data.Initiation.FirstPaymentAmount == nil {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.FirstPaymentAmount is required")
	}
	if req.Data.Initiation.FirstPaymentAmount != nil && req.Data.Initiation.FirstPaymentAmount.Amount == "" {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.FirstPaymentAmount.Amount is required")
	}
	if req.Data.Initiation.FirstPaymentAmount != nil && !mustMatchPattern("^\\d{1,13}\\.\\d{1,5}$", string(req.Data.Initiation.FirstPaymentAmount.Amount)) {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.FirstPaymentAmount.Amount must match pattern ^\\d{1,13}\\.\\d{1,5}$")
	}
	if req.Data.Initiation.FirstPaymentAmount != nil && req.Data.Initiation.FirstPaymentAmount.Currency == "" {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.FirstPaymentAmount.Currency is required")
	}
	if req.Data.Initiation.FirstPaymentAmount != nil && !mustMatchPattern("^[A-Z]{3,3}$", req.Data.Initiation.FirstPaymentAmount.Currency) {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.FirstPaymentAmount.Currency must match pattern ^[A-Z]{3,3}$")
	}
	if req.Data.Initiation.FirstPaymentDateTime.IsZero() {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.FirstPaymentDateTime is required")
	}
	if req.Data.Initiation.Frequency == "" {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.Frequency is required")
	}
	if len(req.Data.Initiation.Frequency) < 1 {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.Frequency must be at least 1 characters")
	}
	if len(req.Data.Initiation.Frequency) > 35 {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.Frequency must be at most 35 characters")
	}
	if req.Data.Initiation.NumberOfPayments != "" && len(req.Data.Initiation.NumberOfPayments) < 1 {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.NumberOfPayments must be at least 1 characters")
	}
	if req.Data.Initiation.NumberOfPayments != "" && len(req.Data.Initiation.NumberOfPayments) > 35 {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.NumberOfPayments must be at most 35 characters")
	}
	if req.Data.Initiation.Reference != "" && len(req.Data.Initiation.Reference) < 1 {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.Reference must be at least 1 characters")
	}
	if req.Data.Initiation.Reference != "" && len(req.Data.Initiation.Reference) > 35 {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Initiation.Reference must be at most 35 characters")
	}
	if req.Data.Permission == "" {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrderConsent2.Data.Permission is required")
	}
	r := transport.RawRequest{
		JSONBody: req,
	}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if xIdempotencyKey != "" {
		r.Headers.Set("x-idempotency-key", xIdempotencyKey)
	}
	if xJWSSignature != "" {
		r.Headers.Set("x-jws-signature", xJWSSignature)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodPost, "domestic-standing-order-consents", r)
	if err != nil {
		return nil, err
	}
	var out ObwriteDomesticStandingOrderConsentResponse2
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, err
		}
	}
	return &Signed[ObwriteDomesticStandingOrderConsentResponse2]{Typed: &out, Raw: body, Metadata: extractResponseMetadata(hdr)}, nil
}

// GetConsentsConsentID retrieve a domestic standing order consent
//
// Docs: https://developer.revolut.com/docs/openbanking/get-domestic-standing-order-consents-consent-id
// Required scopes: payments
func (s *DomesticStandingOrder) GetConsentsConsentID(ctx context.Context, consentID string, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, xCustomerUserAgent string) (*ObwriteDomesticStandingOrderConsentResponse2, ResponseMetadata, error) {
	if consentID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ConsentId is required")
	}
	if xFAPIFinancialID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: x-fapi-financial-id is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodGet, "domestic-standing-order-consents/"+url.PathEscape(consentID), r)
	if err != nil {
		return nil, ResponseMetadata{}, err
	}
	var out ObwriteDomesticStandingOrderConsentResponse2
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, ResponseMetadata{}, err
		}
	}
	return &out, extractResponseMetadata(hdr), nil
}

// GetConsentsConsentIDSigned is GetConsentsConsentID with the raw response body and ResponseMetadata
// preserved alongside the typed payload. Use it when you need to verify
// the detached x-jws-signature header against the untouched bytes.
func (s *DomesticStandingOrder) GetConsentsConsentIDSigned(ctx context.Context, consentID string, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, xCustomerUserAgent string) (*Signed[ObwriteDomesticStandingOrderConsentResponse2], error) {
	if consentID == "" {
		return nil, errors.New("openbanking: ConsentId is required")
	}
	if xFAPIFinancialID == "" {
		return nil, errors.New("openbanking: x-fapi-financial-id is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodGet, "domestic-standing-order-consents/"+url.PathEscape(consentID), r)
	if err != nil {
		return nil, err
	}
	var out ObwriteDomesticStandingOrderConsentResponse2
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, err
		}
	}
	return &Signed[ObwriteDomesticStandingOrderConsentResponse2]{Typed: &out, Raw: body, Metadata: extractResponseMetadata(hdr)}, nil
}

// Create create a domestic standing order
//
// Docs: https://developer.revolut.com/docs/openbanking/create-domestic-standing-orders
// Required scopes: payments
func (s *DomesticStandingOrder) Create(ctx context.Context, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, xIdempotencyKey string, xJWSSignature string, xCustomerUserAgent string, req ObwriteDomesticStandingOrder2) (*ObwriteDomesticStandingOrderResponse2, ResponseMetadata, error) {
	if xFAPIFinancialID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: x-fapi-financial-id is required")
	}
	if xIdempotencyKey == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: x-idempotency-key is required")
	}
	if xJWSSignature == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: x-jws-signature is required")
	}
	if req.Data.ConsentID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.ConsentId is required")
	}
	if len(req.Data.ConsentID) < 1 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.ConsentId must be at least 1 characters")
	}
	if len(req.Data.ConsentID) > 128 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.ConsentId must be at most 128 characters")
	}
	if req.Data.Initiation.CreditorAccount.Identification == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.CreditorAccount.Identification is required")
	}
	if len(req.Data.Initiation.CreditorAccount.Identification) < 1 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.CreditorAccount.Identification must be at least 1 characters")
	}
	if len(req.Data.Initiation.CreditorAccount.Identification) > 256 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.CreditorAccount.Identification must be at most 256 characters")
	}
	if req.Data.Initiation.CreditorAccount.Name == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.CreditorAccount.Name is required")
	}
	if len(req.Data.Initiation.CreditorAccount.Name) < 1 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.CreditorAccount.Name must be at least 1 characters")
	}
	if len(req.Data.Initiation.CreditorAccount.Name) > 70 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.CreditorAccount.Name must be at most 70 characters")
	}
	if req.Data.Initiation.CreditorAccount.SchemeName == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.CreditorAccount.SchemeName is required")
	}
	if req.Data.Initiation.CreditorAccount.SecondaryIdentification != "" && len(req.Data.Initiation.CreditorAccount.SecondaryIdentification) < 1 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.CreditorAccount.SecondaryIdentification must be at least 1 characters")
	}
	if req.Data.Initiation.CreditorAccount.SecondaryIdentification != "" && len(req.Data.Initiation.CreditorAccount.SecondaryIdentification) > 34 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.CreditorAccount.SecondaryIdentification must be at most 34 characters")
	}
	if req.Data.Initiation.FirstPaymentAmount == nil {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.FirstPaymentAmount is required")
	}
	if req.Data.Initiation.FirstPaymentAmount != nil && req.Data.Initiation.FirstPaymentAmount.Amount == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.FirstPaymentAmount.Amount is required")
	}
	if req.Data.Initiation.FirstPaymentAmount != nil && !mustMatchPattern("^\\d{1,13}\\.\\d{1,5}$", string(req.Data.Initiation.FirstPaymentAmount.Amount)) {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.FirstPaymentAmount.Amount must match pattern ^\\d{1,13}\\.\\d{1,5}$")
	}
	if req.Data.Initiation.FirstPaymentAmount != nil && req.Data.Initiation.FirstPaymentAmount.Currency == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.FirstPaymentAmount.Currency is required")
	}
	if req.Data.Initiation.FirstPaymentAmount != nil && !mustMatchPattern("^[A-Z]{3,3}$", req.Data.Initiation.FirstPaymentAmount.Currency) {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.FirstPaymentAmount.Currency must match pattern ^[A-Z]{3,3}$")
	}
	if req.Data.Initiation.FirstPaymentDateTime.IsZero() {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.FirstPaymentDateTime is required")
	}
	if req.Data.Initiation.Frequency == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.Frequency is required")
	}
	if len(req.Data.Initiation.Frequency) < 1 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.Frequency must be at least 1 characters")
	}
	if len(req.Data.Initiation.Frequency) > 35 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.Frequency must be at most 35 characters")
	}
	if req.Data.Initiation.NumberOfPayments != "" && len(req.Data.Initiation.NumberOfPayments) < 1 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.NumberOfPayments must be at least 1 characters")
	}
	if req.Data.Initiation.NumberOfPayments != "" && len(req.Data.Initiation.NumberOfPayments) > 35 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.NumberOfPayments must be at most 35 characters")
	}
	if req.Data.Initiation.Reference != "" && len(req.Data.Initiation.Reference) < 1 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.Reference must be at least 1 characters")
	}
	if req.Data.Initiation.Reference != "" && len(req.Data.Initiation.Reference) > 35 {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.Reference must be at most 35 characters")
	}
	r := transport.RawRequest{
		JSONBody: req,
	}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if xIdempotencyKey != "" {
		r.Headers.Set("x-idempotency-key", xIdempotencyKey)
	}
	if xJWSSignature != "" {
		r.Headers.Set("x-jws-signature", xJWSSignature)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodPost, "domestic-standing-orders", r)
	if err != nil {
		return nil, ResponseMetadata{}, err
	}
	var out ObwriteDomesticStandingOrderResponse2
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, ResponseMetadata{}, err
		}
	}
	return &out, extractResponseMetadata(hdr), nil
}

// CreateSigned is Create with the raw response body and ResponseMetadata
// preserved alongside the typed payload. Use it when you need to verify
// the detached x-jws-signature header against the untouched bytes.
func (s *DomesticStandingOrder) CreateSigned(ctx context.Context, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, xIdempotencyKey string, xJWSSignature string, xCustomerUserAgent string, req ObwriteDomesticStandingOrder2) (*Signed[ObwriteDomesticStandingOrderResponse2], error) {
	if xFAPIFinancialID == "" {
		return nil, errors.New("openbanking: x-fapi-financial-id is required")
	}
	if xIdempotencyKey == "" {
		return nil, errors.New("openbanking: x-idempotency-key is required")
	}
	if xJWSSignature == "" {
		return nil, errors.New("openbanking: x-jws-signature is required")
	}
	if req.Data.ConsentID == "" {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.ConsentId is required")
	}
	if len(req.Data.ConsentID) < 1 {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.ConsentId must be at least 1 characters")
	}
	if len(req.Data.ConsentID) > 128 {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.ConsentId must be at most 128 characters")
	}
	if req.Data.Initiation.CreditorAccount.Identification == "" {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.CreditorAccount.Identification is required")
	}
	if len(req.Data.Initiation.CreditorAccount.Identification) < 1 {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.CreditorAccount.Identification must be at least 1 characters")
	}
	if len(req.Data.Initiation.CreditorAccount.Identification) > 256 {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.CreditorAccount.Identification must be at most 256 characters")
	}
	if req.Data.Initiation.CreditorAccount.Name == "" {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.CreditorAccount.Name is required")
	}
	if len(req.Data.Initiation.CreditorAccount.Name) < 1 {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.CreditorAccount.Name must be at least 1 characters")
	}
	if len(req.Data.Initiation.CreditorAccount.Name) > 70 {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.CreditorAccount.Name must be at most 70 characters")
	}
	if req.Data.Initiation.CreditorAccount.SchemeName == "" {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.CreditorAccount.SchemeName is required")
	}
	if req.Data.Initiation.CreditorAccount.SecondaryIdentification != "" && len(req.Data.Initiation.CreditorAccount.SecondaryIdentification) < 1 {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.CreditorAccount.SecondaryIdentification must be at least 1 characters")
	}
	if req.Data.Initiation.CreditorAccount.SecondaryIdentification != "" && len(req.Data.Initiation.CreditorAccount.SecondaryIdentification) > 34 {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.CreditorAccount.SecondaryIdentification must be at most 34 characters")
	}
	if req.Data.Initiation.FirstPaymentAmount == nil {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.FirstPaymentAmount is required")
	}
	if req.Data.Initiation.FirstPaymentAmount != nil && req.Data.Initiation.FirstPaymentAmount.Amount == "" {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.FirstPaymentAmount.Amount is required")
	}
	if req.Data.Initiation.FirstPaymentAmount != nil && !mustMatchPattern("^\\d{1,13}\\.\\d{1,5}$", string(req.Data.Initiation.FirstPaymentAmount.Amount)) {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.FirstPaymentAmount.Amount must match pattern ^\\d{1,13}\\.\\d{1,5}$")
	}
	if req.Data.Initiation.FirstPaymentAmount != nil && req.Data.Initiation.FirstPaymentAmount.Currency == "" {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.FirstPaymentAmount.Currency is required")
	}
	if req.Data.Initiation.FirstPaymentAmount != nil && !mustMatchPattern("^[A-Z]{3,3}$", req.Data.Initiation.FirstPaymentAmount.Currency) {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.FirstPaymentAmount.Currency must match pattern ^[A-Z]{3,3}$")
	}
	if req.Data.Initiation.FirstPaymentDateTime.IsZero() {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.FirstPaymentDateTime is required")
	}
	if req.Data.Initiation.Frequency == "" {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.Frequency is required")
	}
	if len(req.Data.Initiation.Frequency) < 1 {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.Frequency must be at least 1 characters")
	}
	if len(req.Data.Initiation.Frequency) > 35 {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.Frequency must be at most 35 characters")
	}
	if req.Data.Initiation.NumberOfPayments != "" && len(req.Data.Initiation.NumberOfPayments) < 1 {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.NumberOfPayments must be at least 1 characters")
	}
	if req.Data.Initiation.NumberOfPayments != "" && len(req.Data.Initiation.NumberOfPayments) > 35 {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.NumberOfPayments must be at most 35 characters")
	}
	if req.Data.Initiation.Reference != "" && len(req.Data.Initiation.Reference) < 1 {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.Reference must be at least 1 characters")
	}
	if req.Data.Initiation.Reference != "" && len(req.Data.Initiation.Reference) > 35 {
		return nil, errors.New("openbanking: ObwriteDomesticStandingOrder2.Data.Initiation.Reference must be at most 35 characters")
	}
	r := transport.RawRequest{
		JSONBody: req,
	}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if xIdempotencyKey != "" {
		r.Headers.Set("x-idempotency-key", xIdempotencyKey)
	}
	if xJWSSignature != "" {
		r.Headers.Set("x-jws-signature", xJWSSignature)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodPost, "domestic-standing-orders", r)
	if err != nil {
		return nil, err
	}
	var out ObwriteDomesticStandingOrderResponse2
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, err
		}
	}
	return &Signed[ObwriteDomesticStandingOrderResponse2]{Typed: &out, Raw: body, Metadata: extractResponseMetadata(hdr)}, nil
}

// GetDomesticStandingOrderID retrieve a domestic standing order
//
// Docs: https://developer.revolut.com/docs/openbanking/get-domestic-standing-orders-domestic-standing-order-id
// Required scopes: payments
func (s *DomesticStandingOrder) GetDomesticStandingOrderID(ctx context.Context, domesticStandingOrderID string, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, xCustomerUserAgent string) (*ObwriteDomesticStandingOrderResponse2, ResponseMetadata, error) {
	if domesticStandingOrderID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: DomesticStandingOrderId is required")
	}
	if xFAPIFinancialID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: x-fapi-financial-id is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodGet, "domestic-standing-orders/"+url.PathEscape(domesticStandingOrderID), r)
	if err != nil {
		return nil, ResponseMetadata{}, err
	}
	var out ObwriteDomesticStandingOrderResponse2
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, ResponseMetadata{}, err
		}
	}
	return &out, extractResponseMetadata(hdr), nil
}

// GetDomesticStandingOrderIDSigned is GetDomesticStandingOrderID with the raw response body and ResponseMetadata
// preserved alongside the typed payload. Use it when you need to verify
// the detached x-jws-signature header against the untouched bytes.
func (s *DomesticStandingOrder) GetDomesticStandingOrderIDSigned(ctx context.Context, domesticStandingOrderID string, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, xCustomerUserAgent string) (*Signed[ObwriteDomesticStandingOrderResponse2], error) {
	if domesticStandingOrderID == "" {
		return nil, errors.New("openbanking: DomesticStandingOrderId is required")
	}
	if xFAPIFinancialID == "" {
		return nil, errors.New("openbanking: x-fapi-financial-id is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodGet, "domestic-standing-orders/"+url.PathEscape(domesticStandingOrderID), r)
	if err != nil {
		return nil, err
	}
	var out ObwriteDomesticStandingOrderResponse2
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, err
		}
	}
	return &Signed[ObwriteDomesticStandingOrderResponse2]{Typed: &out, Raw: body, Metadata: extractResponseMetadata(hdr)}, nil
}
