// Code generated by revogen. DO NOT EDIT.

package openbanking

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"net/url"

	"github.com/greatliontech/revolut-go/internal/transport"
)

// InternationalPayment groups the InternationalPayment endpoints.
type InternationalPayment struct {
	t *transport.Transport
}

// CreateConsents create an international payment consent
//
// Docs: https://developer.revolut.com/docs/openbanking/create-international-payment-consents
// Required scopes: payments
func (s *InternationalPayment) CreateConsents(ctx context.Context, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, authorization string, xIdempotencyKey string, xJWSSignature string, xCustomerUserAgent string, req ObwriteInternationalConsent2) (*ObwriteInternationalConsentResponse2, ResponseMetadata, error) {
	if req.Data.Initiation.CreditorAccount.Identification == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteInternationalConsent2.Data.Initiation.CreditorAccount.Identification is required")
	}
	if req.Data.Initiation.CreditorAccount.Name == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteInternationalConsent2.Data.Initiation.CreditorAccount.Name is required")
	}
	if req.Data.Initiation.CreditorAccount.SchemeName == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteInternationalConsent2.Data.Initiation.CreditorAccount.SchemeName is required")
	}
	if req.Data.Initiation.CurrencyOfTransfer == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteInternationalConsent2.Data.Initiation.CurrencyOfTransfer is required")
	}
	if req.Data.Initiation.EndToEndIdentification == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteInternationalConsent2.Data.Initiation.EndToEndIdentification is required")
	}
	if req.Data.Initiation.InstructedAmount == nil {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteInternationalConsent2.Data.Initiation.InstructedAmount is required")
	}
	if req.Data.Initiation.InstructedAmount != nil && req.Data.Initiation.InstructedAmount.Amount == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteInternationalConsent2.Data.Initiation.InstructedAmount.Amount is required")
	}
	if req.Data.Initiation.InstructedAmount != nil && req.Data.Initiation.InstructedAmount.Currency == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteInternationalConsent2.Data.Initiation.InstructedAmount.Currency is required")
	}
	if req.Data.Initiation.InstructionIdentification == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteInternationalConsent2.Data.Initiation.InstructionIdentification is required")
	}
	r := transport.RawRequest{
		JSONBody: req,
	}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if xIdempotencyKey != "" {
		r.Headers.Set("x-idempotency-key", xIdempotencyKey)
	}
	if xJWSSignature != "" {
		r.Headers.Set("x-jws-signature", xJWSSignature)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodPost, "international-payment-consents", r)
	if err != nil {
		return nil, ResponseMetadata{}, err
	}
	var out ObwriteInternationalConsentResponse2
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, ResponseMetadata{}, err
	}
	return &out, extractResponseMetadata(hdr), nil
}

// CreateConsentsSigned is CreateConsents with the raw response body and ResponseMetadata
// preserved alongside the typed payload. Use it when you need to verify
// the detached x-jws-signature header against the untouched bytes.
func (s *InternationalPayment) CreateConsentsSigned(ctx context.Context, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, authorization string, xIdempotencyKey string, xJWSSignature string, xCustomerUserAgent string, req ObwriteInternationalConsent2) (*Signed[ObwriteInternationalConsentResponse2], error) {
	if req.Data.Initiation.CreditorAccount.Identification == "" {
		return nil, errors.New("openbanking: ObwriteInternationalConsent2.Data.Initiation.CreditorAccount.Identification is required")
	}
	if req.Data.Initiation.CreditorAccount.Name == "" {
		return nil, errors.New("openbanking: ObwriteInternationalConsent2.Data.Initiation.CreditorAccount.Name is required")
	}
	if req.Data.Initiation.CreditorAccount.SchemeName == "" {
		return nil, errors.New("openbanking: ObwriteInternationalConsent2.Data.Initiation.CreditorAccount.SchemeName is required")
	}
	if req.Data.Initiation.CurrencyOfTransfer == "" {
		return nil, errors.New("openbanking: ObwriteInternationalConsent2.Data.Initiation.CurrencyOfTransfer is required")
	}
	if req.Data.Initiation.EndToEndIdentification == "" {
		return nil, errors.New("openbanking: ObwriteInternationalConsent2.Data.Initiation.EndToEndIdentification is required")
	}
	if req.Data.Initiation.InstructedAmount == nil {
		return nil, errors.New("openbanking: ObwriteInternationalConsent2.Data.Initiation.InstructedAmount is required")
	}
	if req.Data.Initiation.InstructedAmount != nil && req.Data.Initiation.InstructedAmount.Amount == "" {
		return nil, errors.New("openbanking: ObwriteInternationalConsent2.Data.Initiation.InstructedAmount.Amount is required")
	}
	if req.Data.Initiation.InstructedAmount != nil && req.Data.Initiation.InstructedAmount.Currency == "" {
		return nil, errors.New("openbanking: ObwriteInternationalConsent2.Data.Initiation.InstructedAmount.Currency is required")
	}
	if req.Data.Initiation.InstructionIdentification == "" {
		return nil, errors.New("openbanking: ObwriteInternationalConsent2.Data.Initiation.InstructionIdentification is required")
	}
	r := transport.RawRequest{
		JSONBody: req,
	}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if xIdempotencyKey != "" {
		r.Headers.Set("x-idempotency-key", xIdempotencyKey)
	}
	if xJWSSignature != "" {
		r.Headers.Set("x-jws-signature", xJWSSignature)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodPost, "international-payment-consents", r)
	if err != nil {
		return nil, err
	}
	var out ObwriteInternationalConsentResponse2
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &Signed[ObwriteInternationalConsentResponse2]{Typed: &out, Raw: body, Metadata: extractResponseMetadata(hdr)}, nil
}

// GetConsentsConsentID retrieve an international payment consent
//
// Docs: https://developer.revolut.com/docs/openbanking/get-international-payment-consents-consent-id
// Required scopes: payments
func (s *InternationalPayment) GetConsentsConsentID(ctx context.Context, consentID string, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, authorization string, xCustomerUserAgent string) (*ObwriteInternationalConsentResponse2, ResponseMetadata, error) {
	if consentID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ConsentId is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodGet, "international-payment-consents/"+url.PathEscape(consentID), r)
	if err != nil {
		return nil, ResponseMetadata{}, err
	}
	var out ObwriteInternationalConsentResponse2
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, ResponseMetadata{}, err
	}
	return &out, extractResponseMetadata(hdr), nil
}

// GetConsentsConsentIDSigned is GetConsentsConsentID with the raw response body and ResponseMetadata
// preserved alongside the typed payload. Use it when you need to verify
// the detached x-jws-signature header against the untouched bytes.
func (s *InternationalPayment) GetConsentsConsentIDSigned(ctx context.Context, consentID string, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, authorization string, xCustomerUserAgent string) (*Signed[ObwriteInternationalConsentResponse2], error) {
	if consentID == "" {
		return nil, errors.New("openbanking: ConsentId is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodGet, "international-payment-consents/"+url.PathEscape(consentID), r)
	if err != nil {
		return nil, err
	}
	var out ObwriteInternationalConsentResponse2
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &Signed[ObwriteInternationalConsentResponse2]{Typed: &out, Raw: body, Metadata: extractResponseMetadata(hdr)}, nil
}

// GetConsentsConsentIDFundsConfirmation get funds confirmation for an international payment consent
//
// Docs: https://developer.revolut.com/docs/openbanking/get-international-payment-consents-consent-id-funds-confirmation
// Required scopes: payments
func (s *InternationalPayment) GetConsentsConsentIDFundsConfirmation(ctx context.Context, consentID string, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, authorization string, xCustomerUserAgent string) (*ObwriteFundsConfirmationResponse1, ResponseMetadata, error) {
	if consentID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ConsentId is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodGet, "international-payment-consents/"+url.PathEscape(consentID)+"/funds-confirmation", r)
	if err != nil {
		return nil, ResponseMetadata{}, err
	}
	var out ObwriteFundsConfirmationResponse1
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, ResponseMetadata{}, err
	}
	return &out, extractResponseMetadata(hdr), nil
}

// GetConsentsConsentIDFundsConfirmationSigned is GetConsentsConsentIDFundsConfirmation with the raw response body and ResponseMetadata
// preserved alongside the typed payload. Use it when you need to verify
// the detached x-jws-signature header against the untouched bytes.
func (s *InternationalPayment) GetConsentsConsentIDFundsConfirmationSigned(ctx context.Context, consentID string, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, authorization string, xCustomerUserAgent string) (*Signed[ObwriteFundsConfirmationResponse1], error) {
	if consentID == "" {
		return nil, errors.New("openbanking: ConsentId is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodGet, "international-payment-consents/"+url.PathEscape(consentID)+"/funds-confirmation", r)
	if err != nil {
		return nil, err
	}
	var out ObwriteFundsConfirmationResponse1
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &Signed[ObwriteFundsConfirmationResponse1]{Typed: &out, Raw: body, Metadata: extractResponseMetadata(hdr)}, nil
}

// Create create an international payment
//
// Docs: https://developer.revolut.com/docs/openbanking/create-international-payments
// Required scopes: payments
func (s *InternationalPayment) Create(ctx context.Context, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, authorization string, xIdempotencyKey string, xJWSSignature string, xCustomerUserAgent string, req ObwriteInternational2) (*ObwriteInternationalResponse2, ResponseMetadata, error) {
	if req.Data.ConsentID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteInternational2.Data.ConsentId is required")
	}
	if req.Data.Initiation.CreditorAccount.Identification == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteInternational2.Data.Initiation.CreditorAccount.Identification is required")
	}
	if req.Data.Initiation.CreditorAccount.Name == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteInternational2.Data.Initiation.CreditorAccount.Name is required")
	}
	if req.Data.Initiation.CreditorAccount.SchemeName == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteInternational2.Data.Initiation.CreditorAccount.SchemeName is required")
	}
	if req.Data.Initiation.CurrencyOfTransfer == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteInternational2.Data.Initiation.CurrencyOfTransfer is required")
	}
	if req.Data.Initiation.EndToEndIdentification == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteInternational2.Data.Initiation.EndToEndIdentification is required")
	}
	if req.Data.Initiation.InstructedAmount == nil {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteInternational2.Data.Initiation.InstructedAmount is required")
	}
	if req.Data.Initiation.InstructedAmount != nil && req.Data.Initiation.InstructedAmount.Amount == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteInternational2.Data.Initiation.InstructedAmount.Amount is required")
	}
	if req.Data.Initiation.InstructedAmount != nil && req.Data.Initiation.InstructedAmount.Currency == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteInternational2.Data.Initiation.InstructedAmount.Currency is required")
	}
	if req.Data.Initiation.InstructionIdentification == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: ObwriteInternational2.Data.Initiation.InstructionIdentification is required")
	}
	r := transport.RawRequest{
		JSONBody: req,
	}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if xIdempotencyKey != "" {
		r.Headers.Set("x-idempotency-key", xIdempotencyKey)
	}
	if xJWSSignature != "" {
		r.Headers.Set("x-jws-signature", xJWSSignature)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodPost, "international-payments", r)
	if err != nil {
		return nil, ResponseMetadata{}, err
	}
	var out ObwriteInternationalResponse2
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, ResponseMetadata{}, err
	}
	return &out, extractResponseMetadata(hdr), nil
}

// CreateSigned is Create with the raw response body and ResponseMetadata
// preserved alongside the typed payload. Use it when you need to verify
// the detached x-jws-signature header against the untouched bytes.
func (s *InternationalPayment) CreateSigned(ctx context.Context, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, authorization string, xIdempotencyKey string, xJWSSignature string, xCustomerUserAgent string, req ObwriteInternational2) (*Signed[ObwriteInternationalResponse2], error) {
	if req.Data.ConsentID == "" {
		return nil, errors.New("openbanking: ObwriteInternational2.Data.ConsentId is required")
	}
	if req.Data.Initiation.CreditorAccount.Identification == "" {
		return nil, errors.New("openbanking: ObwriteInternational2.Data.Initiation.CreditorAccount.Identification is required")
	}
	if req.Data.Initiation.CreditorAccount.Name == "" {
		return nil, errors.New("openbanking: ObwriteInternational2.Data.Initiation.CreditorAccount.Name is required")
	}
	if req.Data.Initiation.CreditorAccount.SchemeName == "" {
		return nil, errors.New("openbanking: ObwriteInternational2.Data.Initiation.CreditorAccount.SchemeName is required")
	}
	if req.Data.Initiation.CurrencyOfTransfer == "" {
		return nil, errors.New("openbanking: ObwriteInternational2.Data.Initiation.CurrencyOfTransfer is required")
	}
	if req.Data.Initiation.EndToEndIdentification == "" {
		return nil, errors.New("openbanking: ObwriteInternational2.Data.Initiation.EndToEndIdentification is required")
	}
	if req.Data.Initiation.InstructedAmount == nil {
		return nil, errors.New("openbanking: ObwriteInternational2.Data.Initiation.InstructedAmount is required")
	}
	if req.Data.Initiation.InstructedAmount != nil && req.Data.Initiation.InstructedAmount.Amount == "" {
		return nil, errors.New("openbanking: ObwriteInternational2.Data.Initiation.InstructedAmount.Amount is required")
	}
	if req.Data.Initiation.InstructedAmount != nil && req.Data.Initiation.InstructedAmount.Currency == "" {
		return nil, errors.New("openbanking: ObwriteInternational2.Data.Initiation.InstructedAmount.Currency is required")
	}
	if req.Data.Initiation.InstructionIdentification == "" {
		return nil, errors.New("openbanking: ObwriteInternational2.Data.Initiation.InstructionIdentification is required")
	}
	r := transport.RawRequest{
		JSONBody: req,
	}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if xIdempotencyKey != "" {
		r.Headers.Set("x-idempotency-key", xIdempotencyKey)
	}
	if xJWSSignature != "" {
		r.Headers.Set("x-jws-signature", xJWSSignature)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodPost, "international-payments", r)
	if err != nil {
		return nil, err
	}
	var out ObwriteInternationalResponse2
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &Signed[ObwriteInternationalResponse2]{Typed: &out, Raw: body, Metadata: extractResponseMetadata(hdr)}, nil
}

// GetInternationalPaymentID retrieve an international payment
//
// Docs: https://developer.revolut.com/docs/openbanking/get-international-payments-international-payment-id
// Required scopes: payments
func (s *InternationalPayment) GetInternationalPaymentID(ctx context.Context, internationalPaymentID string, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, authorization string, xCustomerUserAgent string) (*ObwriteInternationalResponse2, ResponseMetadata, error) {
	if internationalPaymentID == "" {
		return nil, ResponseMetadata{}, errors.New("openbanking: InternationalPaymentId is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodGet, "international-payments/"+url.PathEscape(internationalPaymentID), r)
	if err != nil {
		return nil, ResponseMetadata{}, err
	}
	var out ObwriteInternationalResponse2
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, ResponseMetadata{}, err
	}
	return &out, extractResponseMetadata(hdr), nil
}

// GetInternationalPaymentIDSigned is GetInternationalPaymentID with the raw response body and ResponseMetadata
// preserved alongside the typed payload. Use it when you need to verify
// the detached x-jws-signature header against the untouched bytes.
func (s *InternationalPayment) GetInternationalPaymentIDSigned(ctx context.Context, internationalPaymentID string, xFAPIFinancialID string, xFAPICustomerLastLoggedTime string, xFAPICustomerIPAddress string, xFAPIInteractionID string, authorization string, xCustomerUserAgent string) (*Signed[ObwriteInternationalResponse2], error) {
	if internationalPaymentID == "" {
		return nil, errors.New("openbanking: InternationalPaymentId is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xFAPIFinancialID != "" {
		r.Headers.Set("x-fapi-financial-id", xFAPIFinancialID)
	}
	if xFAPICustomerLastLoggedTime != "" {
		r.Headers.Set("x-fapi-customer-last-logged-time", xFAPICustomerLastLoggedTime)
	}
	if xFAPICustomerIPAddress != "" {
		r.Headers.Set("x-fapi-customer-ip-address", xFAPICustomerIPAddress)
	}
	if xFAPIInteractionID != "" {
		r.Headers.Set("x-fapi-interaction-id", xFAPIInteractionID)
	}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if xCustomerUserAgent != "" {
		r.Headers.Set("x-customer-user-agent", xCustomerUserAgent)
	}
	body, hdr, err := s.t.DoRaw(ctx, http.MethodGet, "international-payments/"+url.PathEscape(internationalPaymentID), r)
	if err != nil {
		return nil, err
	}
	var out ObwriteInternationalResponse2
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &Signed[ObwriteInternationalResponse2]{Typed: &out, Raw: body, Metadata: extractResponseMetadata(hdr)}, nil
}
