package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

// emit writes the generated Go source files for spec into outDir.
func emit(spec *Spec, outDir string) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}

	// gen_types.go: every named type.
	typesPath := filepath.Join(outDir, "gen_types.go")
	if err := writeFormatted(typesPath, emitTypes(spec)); err != nil {
		return fmt.Errorf("emit types: %w", err)
	}

	// gen_<resource>.go: resource struct + methods.
	for _, r := range spec.Resources {
		name := "gen_" + strings.ToLower(r.GoName) + ".go"
		path := filepath.Join(outDir, name)
		if err := writeFormatted(path, emitResource(spec, r)); err != nil {
			return fmt.Errorf("emit %s: %w", r.GoName, err)
		}
	}

	// gen_client.go: the Client struct and New wiring.
	clientPath := filepath.Join(outDir, "gen_client.go")
	if err := writeFormatted(clientPath, emitClient(spec)); err != nil {
		return fmt.Errorf("emit client: %w", err)
	}

	return nil
}

// emitClient produces gen_client.go: the Client struct with a field per
// resource plus the New constructor wiring them.
func emitClient(spec *Spec) string {
	var buf bytes.Buffer
	buf.WriteString(genHeader)
	fmt.Fprintf(&buf, "package %s\n\n", spec.PackageName)
	buf.WriteString("import \"github.com/greatliontech/revolut-go/internal/transport\"\n\n")
	buf.WriteString("// Client is the generated Revolut API client. Resource fields group\n")
	buf.WriteString("// endpoints by their Revolut API path prefix.\n")
	buf.WriteString("type Client struct {\n")
	buf.WriteString("\ttransport *transport.Transport\n\n")
	for _, r := range spec.Resources {
		fmt.Fprintf(&buf, "\t// %s groups the related endpoints.\n", r.GoName)
		fmt.Fprintf(&buf, "\t%s *%s\n", r.GoName, r.GoName)
	}
	buf.WriteString("}\n\n")
	buf.WriteString("// New wraps an HTTP transport in a Client.\n")
	buf.WriteString("func New(t *transport.Transport) *Client {\n")
	buf.WriteString("\tc := &Client{transport: t}\n")
	for _, r := range spec.Resources {
		fmt.Fprintf(&buf, "\tc.%s = &%s{t: t}\n", r.GoName, r.GoName)
	}
	buf.WriteString("\treturn c\n}\n")
	return buf.String()
}

const genHeader = "// Code generated by revogen. DO NOT EDIT.\n\n"

// emitTypes produces the gen_types.go source.
func emitTypes(spec *Spec) string {
	var buf bytes.Buffer
	buf.WriteString(genHeader)
	fmt.Fprintf(&buf, "package %s\n\n", spec.PackageName)

	needsJSON := false
	needsTime := false
	needsCore := false
	for _, t := range spec.Types {
		if t.Kind == KindAlias && strings.HasPrefix(t.AliasTarget, "core.") {
			needsCore = true
		}
		for _, f := range t.Fields {
			if strings.Contains(f.GoType, "json.Number") {
				needsJSON = true
			}
			if strings.Contains(f.GoType, "time.Time") {
				needsTime = true
			}
			if strings.Contains(f.GoType, "core.") {
				needsCore = true
			}
		}
	}

	buf.WriteString("import (\n")
	if needsJSON {
		buf.WriteString("\t\"encoding/json\"\n")
	}
	if needsTime {
		buf.WriteString("\t\"time\"\n")
	}
	if needsCore {
		if needsJSON || needsTime {
			buf.WriteString("\n")
		}
		buf.WriteString("\t\"github.com/greatliontech/revolut-go/internal/core\"\n")
	}
	buf.WriteString(")\n\n")

	for _, t := range spec.Types {
		writeType(&buf, t)
	}
	return buf.String()
}

func writeType(buf *bytes.Buffer, t *NamedType) {
	if t.Doc != "" {
		writeDoc(buf, t.Doc, t.GoName)
	}
	switch t.Kind {
	case KindAlias:
		fmt.Fprintf(buf, "type %s = %s\n\n", t.GoName, t.AliasTarget)
	case KindEnum:
		fmt.Fprintf(buf, "type %s %s\n\n", t.GoName, t.EnumBase)
		if len(t.EnumValues) > 0 {
			buf.WriteString("const (\n")
			for _, v := range t.EnumValues {
				if v.Doc != "" {
					fmt.Fprintf(buf, "\t// %s.\n", v.Doc)
				}
				fmt.Fprintf(buf, "\t%s %s = %q\n", v.GoName, t.GoName, v.Value)
			}
			buf.WriteString(")\n\n")
		}
	case KindStruct:
		fmt.Fprintf(buf, "type %s struct {\n", t.GoName)
		for _, f := range t.Fields {
			if f.Doc != "" {
				fmt.Fprintf(buf, "\t// %s\n", f.Doc)
			}
			fmt.Fprintf(buf, "\t%s %s `json:\"%s\"`\n", f.GoName, f.GoType, jsonTag(f))
		}
		buf.WriteString("}\n\n")
	}
}

// emitResource produces gen_<resource>.go.
func emitResource(spec *Spec, r *Resource) string {
	var buf bytes.Buffer
	buf.WriteString(genHeader)
	fmt.Fprintf(&buf, "package %s\n\n", spec.PackageName)

	// Imports — compute from what the methods reference.
	imports := resourceImports(r)

	buf.WriteString("import (\n")
	buf.WriteString("\t\"context\"\n")
	if imports.errors {
		buf.WriteString("\t\"errors\"\n")
	}
	buf.WriteString("\t\"net/http\"\n")
	if imports.url {
		buf.WriteString("\t\"net/url\"\n")
	}
	if imports.strconv {
		buf.WriteString("\t\"strconv\"\n")
	}
	if imports.time {
		buf.WriteString("\t\"time\"\n")
	}
	if imports.json {
		buf.WriteString("\t\"encoding/json\"\n")
	}
	buf.WriteString("\n\t\"github.com/greatliontech/revolut-go/internal/transport\"\n")
	buf.WriteString(")\n\n")

	fmt.Fprintf(&buf, "// %s groups the %s endpoints.\n", r.GoName, r.GoName)
	fmt.Fprintf(&buf, "type %s struct {\n", r.GoName)
	buf.WriteString("\tt *transport.Transport\n")
	buf.WriteString("}\n\n")

	for _, op := range r.Ops {
		if op.ParamsStruct != nil {
			writeType(&buf, op.ParamsStruct)
			writeParamsEncode(&buf, op)
		}
		writeMethod(&buf, r, op)
	}
	return buf.String()
}

type resourceImportSet struct {
	errors  bool
	url     bool
	strconv bool
	time    bool
	json    bool
}

func resourceImports(r *Resource) resourceImportSet {
	var s resourceImportSet
	for _, op := range r.Ops {
		if len(op.PathParams) > 0 {
			s.url = true
			s.errors = true
		}
		if len(op.Validate) > 0 {
			s.errors = true
		}
		if op.ParamsStruct != nil {
			s.url = true
			for _, f := range op.ParamsStruct.Fields {
				switch {
				case f.GoType == "int", f.GoType == "int64", f.GoType == "bool":
					s.strconv = true
				case f.GoType == "time.Time":
					s.time = true
				case f.GoType == "json.Number":
					s.json = true
				case strings.HasPrefix(f.GoType, "[]"):
					// Encoded as repeated values; no extra import.
				}
			}
		}
	}
	return s
}

// writeParamsEncode emits an `encode` method for a params struct that
// produces a url.Values with only the non-zero fields set, so callers
// pay nothing for params they don't fill in.
func writeParamsEncode(buf *bytes.Buffer, op *Operation) {
	t := op.ParamsStruct
	fmt.Fprintf(buf, "func (p *%s) encode() url.Values {\n", t.GoName)
	buf.WriteString("\tif p == nil {\n\t\treturn nil\n\t}\n")
	buf.WriteString("\tq := url.Values{}\n")
	for i, f := range t.Fields {
		qp := op.QueryParams[i]
		emitQueryField(buf, f, qp.Name)
	}
	buf.WriteString("\treturn q\n}\n\n")
}

// emitQueryField writes the "if field has a value, q.Set(...)" for one
// params-struct field.
func emitQueryField(buf *bytes.Buffer, f *StructField, wireName string) {
	expr := "p." + f.GoName
	if strings.HasPrefix(f.GoType, "[]") {
		// Repeated query parameter: emit one ?name=v per element.
		inner := strings.TrimPrefix(f.GoType, "[]")
		valueExpr := "v"
		switch inner {
		case "string":
			// keep v as-is.
		case "int", "int64":
			valueExpr = "strconv.FormatInt(int64(v), 10)"
		case "bool":
			valueExpr = "strconv.FormatBool(v)"
		case "time.Time":
			valueExpr = "v.UTC().Format(time.RFC3339)"
		default:
			valueExpr = "string(v)"
		}
		fmt.Fprintf(buf, "\tfor _, v := range %s {\n\t\tq.Add(%q, %s)\n\t}\n", expr, wireName, valueExpr)
		return
	}
	switch f.GoType {
	case "string":
		fmt.Fprintf(buf, "\tif %s != \"\" {\n\t\tq.Set(%q, %s)\n\t}\n", expr, wireName, expr)
	case "int", "int64":
		fmt.Fprintf(buf, "\tif %s != 0 {\n\t\tq.Set(%q, strconv.FormatInt(int64(%s), 10))\n\t}\n", expr, wireName, expr)
	case "bool":
		fmt.Fprintf(buf, "\tif %s {\n\t\tq.Set(%q, strconv.FormatBool(%s))\n\t}\n", expr, wireName, expr)
	case "time.Time":
		fmt.Fprintf(buf, "\tif !%s.IsZero() {\n\t\tq.Set(%q, %s.UTC().Format(time.RFC3339))\n\t}\n", expr, wireName, expr)
	case "json.Number":
		fmt.Fprintf(buf, "\tif %s != \"\" {\n\t\tq.Set(%q, string(%s))\n\t}\n", expr, wireName, expr)
	default:
		// Enum types (string-backed) and named aliases.
		fmt.Fprintf(buf, "\tif %s != \"\" {\n\t\tq.Set(%q, string(%s))\n\t}\n", expr, wireName, expr)
	}
}

func writeMethod(buf *bytes.Buffer, r *Resource, op *Operation) {
	// godoc
	if op.Summary != "" {
		fmt.Fprintf(buf, "// %s %s\n", op.GoMethod, lower1(op.Summary))
	} else {
		fmt.Fprintf(buf, "// %s performs the %s operation.\n", op.GoMethod, op.GoMethod)
	}
	if op.DocURL != "" {
		buf.WriteString("//\n")
		fmt.Fprintf(buf, "// Docs: %s\n", op.DocURL)
	}

	// Signature.
	params := []string{"ctx context.Context"}
	for _, p := range op.PathParams {
		params = append(params, p.GoName+" "+p.GoType)
	}
	if op.RequestType != "" {
		params = append(params, "req "+op.RequestType)
	}
	if op.ParamsType != "" {
		params = append(params, "opts *"+op.ParamsType)
	}

	retType := "error"
	switch {
	case op.ResponseType == "":
		// void
	case strings.HasPrefix(op.ResponseType, "[]"):
		retType = op.ResponseType + ", error"
	default:
		retType = "*" + op.ResponseType + ", error"
	}

	fmt.Fprintf(buf, "func (s *%s) %s(%s) (%s) {\n", r.GoName, op.GoMethod, strings.Join(params, ", "), retType)

	// Path-param validation.
	zero := zeroValueForReturn(op.ResponseType)
	for _, p := range op.PathParams {
		fmt.Fprintf(buf, "\tif %s == \"\" {\n", p.GoName)
		fmt.Fprintf(buf, "\t\treturn %serrors.New(\"business: %s is required\")\n", ifZero(zero), p.Name)
		buf.WriteString("\t}\n")
	}
	// Body-field validation.
	for _, v := range op.Validate {
		fmt.Fprintf(buf, "\tif %s == \"\" {\n", v.GoExpr)
		fmt.Fprintf(buf, "\t\treturn %serrors.New(%q)\n", ifZero(zero), v.Message)
		buf.WriteString("\t}\n")
	}

	// HTTP call.
	pathExpr := renderPathExpr(op.PathTemplate, op.PathParams)
	if op.ParamsType != "" {
		fmt.Fprintf(buf, "\tpath := %s\n", pathExpr)
		buf.WriteString("\tif q := opts.encode().Encode(); q != \"\" {\n")
		buf.WriteString("\t\tpath += \"?\" + q\n")
		buf.WriteString("\t}\n")
		pathExpr = "path"
	}
	bodyArg := "nil"
	if op.RequestType != "" {
		bodyArg = "req"
	}
	httpMethod := "http.Method" + strings.ToUpper(op.HTTPMethod[:1]) + strings.ToLower(op.HTTPMethod[1:])

	if op.ResponseType == "" {
		fmt.Fprintf(buf, "\treturn s.t.Do(ctx, %s, %s, %s, nil)\n", httpMethod, pathExpr, bodyArg)
	} else {
		fmt.Fprintf(buf, "\tvar out %s\n", op.ResponseType)
		fmt.Fprintf(buf, "\tif err := s.t.Do(ctx, %s, %s, %s, &out); err != nil {\n", httpMethod, pathExpr, bodyArg)
		fmt.Fprintf(buf, "\t\treturn %serr\n", ifZero(zero))
		buf.WriteString("\t}\n")
		if strings.HasPrefix(op.ResponseType, "[]") {
			buf.WriteString("\treturn out, nil\n")
		} else {
			buf.WriteString("\treturn &out, nil\n")
		}
	}
	buf.WriteString("}\n\n")
}

// renderPathExpr produces the Go expression for the concrete request
// path, url.PathEscape-ing path parameters.
func renderPathExpr(tmpl string, params []*PathParam) string {
	// Drop the leading "/", since the transport resolves relative paths
	// against the base URL that already has a trailing slash.
	tmpl = strings.TrimPrefix(tmpl, "/")
	paramByName := map[string]*PathParam{}
	for _, p := range params {
		paramByName[p.Name] = p
	}

	var parts []string
	rest := tmpl
	for {
		i := strings.Index(rest, "{")
		if i < 0 {
			if rest != "" {
				parts = append(parts, fmt.Sprintf("%q", rest))
			}
			break
		}
		j := strings.Index(rest, "}")
		if j < 0 {
			parts = append(parts, fmt.Sprintf("%q", rest))
			break
		}
		literal := rest[:i]
		name := rest[i+1 : j]
		if literal != "" {
			parts = append(parts, fmt.Sprintf("%q", literal))
		}
		p, ok := paramByName[name]
		if !ok {
			parts = append(parts, fmt.Sprintf("%q", "{"+name+"}"))
		} else {
			parts = append(parts, fmt.Sprintf("url.PathEscape(%s)", p.GoName))
		}
		rest = rest[j+1:]
	}
	if len(parts) == 0 {
		return `""`
	}
	return strings.Join(parts, " + ")
}

func zeroValueForReturn(responseType string) string {
	switch {
	case responseType == "":
		return ""
	case strings.HasPrefix(responseType, "[]"):
		return "nil"
	default:
		return "nil"
	}
}

func ifZero(zero string) string {
	if zero == "" {
		return ""
	}
	return zero + ", "
}

func jsonTag(f *StructField) string {
	if f.Required {
		return f.JSONName
	}
	return f.JSONName + ",omitempty"
}

func writeDoc(buf *bytes.Buffer, doc, name string) {
	doc = strings.TrimSpace(doc)
	if doc == "" {
		return
	}
	lines := strings.Split(doc, "\n")
	for i, line := range lines {
		if i == 0 {
			fmt.Fprintf(buf, "// %s %s\n", name, lower1(line))
			continue
		}
		if line == "" {
			buf.WriteString("//\n")
			continue
		}
		fmt.Fprintf(buf, "// %s\n", line)
	}
}

func lower1(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	r[0] = lowerRune(r[0])
	return string(r)
}

func lowerRune(r rune) rune {
	if r >= 'A' && r <= 'Z' {
		return r + ('a' - 'A')
	}
	return r
}

func writeFormatted(path, source string) error {
	formatted, err := format.Source([]byte(source))
	if err != nil {
		// On format failure, still write unformatted source with .bad
		// suffix so we can inspect.
		bad := path + ".bad"
		_ = os.WriteFile(bad, []byte(source), 0o644)
		return fmt.Errorf("gofmt %s: %w (unformatted source written to %s)", path, err, bad)
	}
	return os.WriteFile(path, formatted, 0o644)
}
