package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

// emit writes the generated Go source files for spec into outDir.
func emit(spec *Spec, outDir string) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}

	// gen_types.go: every named type.
	typesPath := filepath.Join(outDir, "gen_types.go")
	if err := writeFormatted(typesPath, emitTypes(spec)); err != nil {
		return fmt.Errorf("emit types: %w", err)
	}

	// gen_<resource>.go: resource struct + methods.
	for _, r := range spec.Resources {
		name := "gen_" + strings.ToLower(r.GoName) + ".go"
		path := filepath.Join(outDir, name)
		if err := writeFormatted(path, emitResource(spec, r)); err != nil {
			return fmt.Errorf("emit %s: %w", r.GoName, err)
		}
	}

	return nil
}

const genHeader = "// Code generated by revogen. DO NOT EDIT.\n\n"

// emitTypes produces the gen_types.go source.
func emitTypes(spec *Spec) string {
	var buf bytes.Buffer
	buf.WriteString(genHeader)
	fmt.Fprintf(&buf, "package %s\n\n", spec.PackageName)

	needsJSON := false
	needsTime := false
	needsCore := false
	for _, t := range spec.Types {
		if t.Kind == KindAlias && strings.HasPrefix(t.AliasTarget, "core.") {
			needsCore = true
		}
		for _, f := range t.Fields {
			if strings.Contains(f.GoType, "json.Number") {
				needsJSON = true
			}
			if strings.Contains(f.GoType, "time.Time") {
				needsTime = true
			}
			if strings.Contains(f.GoType, "core.") {
				needsCore = true
			}
		}
	}

	buf.WriteString("import (\n")
	if needsJSON {
		buf.WriteString("\t\"encoding/json\"\n")
	}
	if needsTime {
		buf.WriteString("\t\"time\"\n")
	}
	if needsCore {
		if needsJSON || needsTime {
			buf.WriteString("\n")
		}
		buf.WriteString("\t\"github.com/greatliontech/revolut-go/internal/core\"\n")
	}
	buf.WriteString(")\n\n")

	for _, t := range spec.Types {
		writeType(&buf, t)
	}
	return buf.String()
}

func writeType(buf *bytes.Buffer, t *NamedType) {
	if t.Doc != "" {
		writeDoc(buf, t.Doc, t.GoName)
	}
	switch t.Kind {
	case KindAlias:
		fmt.Fprintf(buf, "type %s = %s\n\n", t.GoName, t.AliasTarget)
	case KindEnum:
		fmt.Fprintf(buf, "type %s %s\n\n", t.GoName, t.EnumBase)
		if len(t.EnumValues) > 0 {
			buf.WriteString("const (\n")
			for _, v := range t.EnumValues {
				if v.Doc != "" {
					fmt.Fprintf(buf, "\t// %s.\n", v.Doc)
				}
				fmt.Fprintf(buf, "\t%s %s = %q\n", v.GoName, t.GoName, v.Value)
			}
			buf.WriteString(")\n\n")
		}
	case KindStruct:
		fmt.Fprintf(buf, "type %s struct {\n", t.GoName)
		for _, f := range t.Fields {
			if f.Doc != "" {
				fmt.Fprintf(buf, "\t// %s\n", f.Doc)
			}
			fmt.Fprintf(buf, "\t%s %s `json:\"%s\"`\n", f.GoName, f.GoType, jsonTag(f))
		}
		buf.WriteString("}\n\n")
	}
}

// emitResource produces gen_<resource>.go.
func emitResource(spec *Spec, r *Resource) string {
	var buf bytes.Buffer
	buf.WriteString(genHeader)
	fmt.Fprintf(&buf, "package %s\n\n", spec.PackageName)

	// Imports — compute from what the methods reference.
	needsErrors := false
	needsURL := false
	for _, op := range r.Ops {
		if len(op.PathParams) > 0 {
			needsURL = true
			needsErrors = true
		}
		if len(op.Validate) > 0 {
			needsErrors = true
		}
	}

	buf.WriteString("import (\n")
	buf.WriteString("\t\"context\"\n")
	if needsErrors {
		buf.WriteString("\t\"errors\"\n")
	}
	buf.WriteString("\t\"net/http\"\n")
	if needsURL {
		buf.WriteString("\t\"net/url\"\n")
	}
	buf.WriteString("\n\t\"github.com/greatliontech/revolut-go/internal/transport\"\n")
	buf.WriteString(")\n\n")

	fmt.Fprintf(&buf, "// %s groups the %s endpoints.\n", r.GoName, r.GoName)
	fmt.Fprintf(&buf, "type %s struct {\n", r.GoName)
	buf.WriteString("\tt *transport.Transport\n")
	buf.WriteString("}\n\n")

	for _, op := range r.Ops {
		writeMethod(&buf, r, op)
	}
	return buf.String()
}

func writeMethod(buf *bytes.Buffer, r *Resource, op *Operation) {
	// godoc
	if op.Summary != "" {
		fmt.Fprintf(buf, "// %s %s\n", op.GoMethod, lower1(op.Summary))
	} else {
		fmt.Fprintf(buf, "// %s performs the %s operation.\n", op.GoMethod, op.GoMethod)
	}
	if op.DocURL != "" {
		buf.WriteString("//\n")
		fmt.Fprintf(buf, "// Docs: %s\n", op.DocURL)
	}

	// Signature.
	params := []string{"ctx context.Context"}
	for _, p := range op.PathParams {
		params = append(params, p.GoName+" "+p.GoType)
	}
	if op.RequestType != "" {
		params = append(params, "req "+op.RequestType)
	}

	retType := "error"
	switch {
	case op.ResponseType == "":
		// void
	case strings.HasPrefix(op.ResponseType, "[]"):
		retType = op.ResponseType + ", error"
	default:
		retType = "*" + op.ResponseType + ", error"
	}

	fmt.Fprintf(buf, "func (s *%s) %s(%s) (%s) {\n", r.GoName, op.GoMethod, strings.Join(params, ", "), retType)

	// Path-param validation.
	zero := zeroValueForReturn(op.ResponseType)
	for _, p := range op.PathParams {
		fmt.Fprintf(buf, "\tif %s == \"\" {\n", p.GoName)
		fmt.Fprintf(buf, "\t\treturn %serrors.New(\"business: %s is required\")\n", ifZero(zero), p.Name)
		buf.WriteString("\t}\n")
	}
	// Body-field validation.
	for _, v := range op.Validate {
		fmt.Fprintf(buf, "\tif %s == \"\" {\n", v.GoExpr)
		fmt.Fprintf(buf, "\t\treturn %serrors.New(%q)\n", ifZero(zero), v.Message)
		buf.WriteString("\t}\n")
	}

	// HTTP call.
	pathExpr := renderPathExpr(op.PathTemplate, op.PathParams)
	bodyArg := "nil"
	if op.RequestType != "" {
		bodyArg = "req"
	}
	httpMethod := "http.Method" + strings.ToUpper(op.HTTPMethod[:1]) + strings.ToLower(op.HTTPMethod[1:])

	if op.ResponseType == "" {
		fmt.Fprintf(buf, "\treturn s.t.Do(ctx, %s, %s, %s, nil)\n", httpMethod, pathExpr, bodyArg)
	} else {
		fmt.Fprintf(buf, "\tvar out %s\n", op.ResponseType)
		fmt.Fprintf(buf, "\tif err := s.t.Do(ctx, %s, %s, %s, &out); err != nil {\n", httpMethod, pathExpr, bodyArg)
		fmt.Fprintf(buf, "\t\treturn %serr\n", ifZero(zero))
		buf.WriteString("\t}\n")
		if strings.HasPrefix(op.ResponseType, "[]") {
			buf.WriteString("\treturn out, nil\n")
		} else {
			buf.WriteString("\treturn &out, nil\n")
		}
	}
	buf.WriteString("}\n\n")
}

// renderPathExpr produces the Go expression for the concrete request
// path, url.PathEscape-ing path parameters.
func renderPathExpr(tmpl string, params []*PathParam) string {
	// Drop the leading "/", since the transport resolves relative paths
	// against the base URL that already has a trailing slash.
	tmpl = strings.TrimPrefix(tmpl, "/")
	paramByName := map[string]*PathParam{}
	for _, p := range params {
		paramByName[p.Name] = p
	}

	var parts []string
	rest := tmpl
	for {
		i := strings.Index(rest, "{")
		if i < 0 {
			if rest != "" {
				parts = append(parts, fmt.Sprintf("%q", rest))
			}
			break
		}
		j := strings.Index(rest, "}")
		if j < 0 {
			parts = append(parts, fmt.Sprintf("%q", rest))
			break
		}
		literal := rest[:i]
		name := rest[i+1 : j]
		if literal != "" {
			parts = append(parts, fmt.Sprintf("%q", literal))
		}
		p, ok := paramByName[name]
		if !ok {
			parts = append(parts, fmt.Sprintf("%q", "{"+name+"}"))
		} else {
			parts = append(parts, fmt.Sprintf("url.PathEscape(%s)", p.GoName))
		}
		rest = rest[j+1:]
	}
	if len(parts) == 0 {
		return `""`
	}
	return strings.Join(parts, " + ")
}

func zeroValueForReturn(responseType string) string {
	switch {
	case responseType == "":
		return ""
	case strings.HasPrefix(responseType, "[]"):
		return "nil"
	default:
		return "nil"
	}
}

func ifZero(zero string) string {
	if zero == "" {
		return ""
	}
	return zero + ", "
}

func jsonTag(f *StructField) string {
	if f.Required {
		return f.JSONName
	}
	return f.JSONName + ",omitempty"
}

func writeDoc(buf *bytes.Buffer, doc, name string) {
	doc = strings.TrimSpace(doc)
	if doc == "" {
		return
	}
	lines := strings.Split(doc, "\n")
	for i, line := range lines {
		if i == 0 {
			fmt.Fprintf(buf, "// %s %s\n", name, lower1(line))
			continue
		}
		if line == "" {
			buf.WriteString("//\n")
			continue
		}
		fmt.Fprintf(buf, "// %s\n", line)
	}
}

func lower1(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	r[0] = lowerRune(r[0])
	return string(r)
}

func lowerRune(r rune) rune {
	if r >= 'A' && r <= 'Z' {
		return r + ('a' - 'A')
	}
	return r
}

func writeFormatted(path, source string) error {
	formatted, err := format.Source([]byte(source))
	if err != nil {
		// On format failure, still write unformatted source with .bad
		// suffix so we can inspect.
		bad := path + ".bad"
		_ = os.WriteFile(bad, []byte(source), 0o644)
		return fmt.Errorf("gofmt %s: %w (unformatted source written to %s)", path, err, bad)
	}
	return os.WriteFile(path, formatted, 0o644)
}
