// Code generated by revogen. DO NOT EDIT.

package revolutx

import (
	"context"
	"encoding/json"
	"net/http"
	"strconv"

	"github.com/greatliontech/revolut-go/internal/transport"
)

// Configuration groups the Configuration endpoints.
type Configuration struct {
	t *transport.Transport
}

// GetAllCurrencies get all currencies
//
// Docs: https://developer.revolut.com/docs/revolutx/get-all-currencies
func (s *Configuration) GetAllCurrencies(ctx context.Context, xRevxTimestamp int, xRevxSignature string) (*CurrenciesResponse, error) {
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	r.Headers.Set("X-Revx-Timestamp", strconv.Itoa(int(xRevxTimestamp)))
	if xRevxSignature != "" {
		r.Headers.Set("X-Revx-Signature", xRevxSignature)
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodGet, "configuration/currencies", r)
	if err != nil {
		return nil, err
	}
	var out CurrenciesResponse
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetAllCurrencyPairs get all currency pairs
//
// Docs: https://developer.revolut.com/docs/revolutx/get-all-currency-pairs
func (s *Configuration) GetAllCurrencyPairs(ctx context.Context, xRevxTimestamp int, xRevxSignature string) (*CurrencyPairsResponse, error) {
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	r.Headers.Set("X-Revx-Timestamp", strconv.Itoa(int(xRevxTimestamp)))
	if xRevxSignature != "" {
		r.Headers.Set("X-Revx-Signature", xRevxSignature)
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodGet, "configuration/pairs", r)
	if err != nil {
		return nil, err
	}
	var out CurrencyPairsResponse
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
