// Code generated by revogen. DO NOT EDIT.

package revolutx

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"strconv"

	"github.com/greatliontech/revolut-go/internal/transport"
)

// Balance groups the Balance endpoints.
type Balance struct {
	t *transport.Transport
}

// GetAllBalances get all balances
//
// Get crypto exchange account balances for the requesting user.
// The user is resolved by the provided API key.
//
// Docs: https://developer.revolut.com/docs/revolutx/get-all-balances
func (s *Balance) GetAllBalances(ctx context.Context, xRevxTimestamp int, xRevxSignature string) ([]AccountBalanceEntry, error) {
	if xRevxSignature == "" {
		return nil, errors.New("revolutx: X-Revx-Signature is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	r.Headers.Set("X-Revx-Timestamp", strconv.Itoa(int(xRevxTimestamp)))
	if xRevxSignature != "" {
		r.Headers.Set("X-Revx-Signature", xRevxSignature)
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodGet, "balances", r)
	if err != nil {
		return nil, err
	}
	var out []AccountBalanceEntry
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, err
		}
	}
	return out, nil
}
