// Code generated by revogen. DO NOT EDIT.

package revolutx

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"net/url"
	"strconv"

	"github.com/greatliontech/revolut-go/internal/transport"
)

// Trades groups the Trades endpoints.
type Trades struct {
	t *transport.Transport
}

// GetAllTrades get all public trades (market history)
//
// Docs: https://developer.revolut.com/docs/revolutx/get-all-trades
func (s *Trades) GetAllTrades(ctx context.Context, symbol string, xRevxTimestamp int, xRevxSignature string, opts *GetAllTradesParams) (*AllTradesPaginatedResponse, error) {
	if symbol == "" {
		return nil, errors.New("revolutx: symbol is required")
	}
	path := "trades/all/" + url.PathEscape(symbol)
	if q := opts.encode().Encode(); q != "" {
		path += "?" + q
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	r.Headers.Set("X-Revx-Timestamp", strconv.Itoa(int(xRevxTimestamp)))
	if xRevxSignature != "" {
		r.Headers.Set("X-Revx-Signature", xRevxSignature)
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodGet, path, r)
	if err != nil {
		return nil, err
	}
	var out AllTradesPaginatedResponse
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetPrivateTrades get client trades (associated with the provided API key)
//
// Docs: https://developer.revolut.com/docs/revolutx/get-private-trades
func (s *Trades) GetPrivateTrades(ctx context.Context, symbol string, xRevxTimestamp int, xRevxSignature string, opts *GetPrivateTradesParams) (*PrivateTradesPaginatedResponse, error) {
	if symbol == "" {
		return nil, errors.New("revolutx: symbol is required")
	}
	path := "trades/private/" + url.PathEscape(symbol)
	if q := opts.encode().Encode(); q != "" {
		path += "?" + q
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	r.Headers.Set("X-Revx-Timestamp", strconv.Itoa(int(xRevxTimestamp)))
	if xRevxSignature != "" {
		r.Headers.Set("X-Revx-Signature", xRevxSignature)
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodGet, path, r)
	if err != nil {
		return nil, err
	}
	var out PrivateTradesPaginatedResponse
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
