// Code generated by revogen. DO NOT EDIT.

package revolutx

import (
	"context"
	"encoding/json"
	"errors"
	"iter"
	"net/http"
	"net/url"
	"strconv"

	"github.com/greatliontech/revolut-go/internal/transport"
)

// Orders groups the Orders endpoints.
type Orders struct {
	t *transport.Transport
}

// PlaceOrder place order
//
// Docs: https://developer.revolut.com/docs/revolutx/place-order
func (s *Orders) PlaceOrder(ctx context.Context, xRevxTimestamp int, xRevxSignature string, req OrderPlacementRequest) (*OrderPlacementResponse, error) {
	if xRevxSignature == "" {
		return nil, errors.New("revolutx: X-Revx-Signature is required")
	}
	if req.ClientOrderID == "" {
		return nil, errors.New("revolutx: OrderPlacementRequest.client_order_id is required")
	}
	if req.OrderConfiguration == nil {
		return nil, errors.New("revolutx: OrderPlacementRequest.order_configuration is required")
	}
	if req.Side == "" {
		return nil, errors.New("revolutx: OrderPlacementRequest.side is required")
	}
	if req.Symbol == "" {
		return nil, errors.New("revolutx: OrderPlacementRequest.symbol is required")
	}
	r := transport.RawRequest{
		JSONBody: req,
	}
	r.Headers = http.Header{}
	r.Headers.Set("X-Revx-Timestamp", strconv.Itoa(int(xRevxTimestamp)))
	if xRevxSignature != "" {
		r.Headers.Set("X-Revx-Signature", xRevxSignature)
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodPost, "orders", r)
	if err != nil {
		return nil, err
	}
	var out OrderPlacementResponse
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// CancelAllOrders cancel all active orders
//
// Docs: https://developer.revolut.com/docs/revolutx/cancel-all-orders
func (s *Orders) CancelAllOrders(ctx context.Context, xRevxTimestamp int, xRevxSignature string) error {
	if xRevxSignature == "" {
		return errors.New("revolutx: X-Revx-Signature is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	r.Headers.Set("X-Revx-Timestamp", strconv.Itoa(int(xRevxTimestamp)))
	if xRevxSignature != "" {
		r.Headers.Set("X-Revx-Signature", xRevxSignature)
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodDelete, "orders", r)
	if err != nil {
		return err
	}
	_ = body
	return nil
}

// GetActiveOrders get active orders
//
// Docs: https://developer.revolut.com/docs/revolutx/get-active-orders
func (s *Orders) GetActiveOrders(ctx context.Context, xRevxTimestamp int, xRevxSignature string, opts *GetActiveOrdersParams) (*ActiveOrdersPaginatedResponse, error) {
	if xRevxSignature == "" {
		return nil, errors.New("revolutx: X-Revx-Signature is required")
	}
	path := "orders/active"
	if q := opts.encode().Encode(); q != "" {
		path += "?" + q
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	r.Headers.Set("X-Revx-Timestamp", strconv.Itoa(int(xRevxTimestamp)))
	if xRevxSignature != "" {
		r.Headers.Set("X-Revx-Signature", xRevxSignature)
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodGet, path, r)
	if err != nil {
		return nil, err
	}
	var out ActiveOrdersPaginatedResponse
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// GetActiveOrdersAll iterates every page of GetActiveOrders, yielding one Order per
// step. Break out of the loop to stop early.
func (s *Orders) GetActiveOrdersAll(ctx context.Context, xRevxTimestamp int, xRevxSignature string, opts *GetActiveOrdersParams) iter.Seq2[Order, error] {
	return func(yield func(Order, error) bool) {
		var p GetActiveOrdersParams
		if opts != nil {
			p = *opts
		}
		for {
			if err := ctx.Err(); err != nil {
				var zero Order
				yield(zero, err)
				return
			}
			resp, err := s.GetActiveOrders(ctx, xRevxTimestamp, xRevxSignature, &p)
			if err != nil {
				var zero Order
				yield(zero, err)
				return
			}
			for _, item := range resp.Data {
				if !yield(item, nil) {
					return
				}
			}
			if resp.Metadata == nil {
				return
			}
			if resp.Metadata.NextCursor == "" {
				return
			}
			nextTok := resp.Metadata.NextCursor
			if nextTok == p.Cursor {
				return
			}
			p.Cursor = nextTok
		}
	}
}

// GetFills get fills of order by ID
//
// Docs: https://developer.revolut.com/docs/revolutx/get-order-fills
func (s *Orders) GetFills(ctx context.Context, venueOrderID string, xRevxTimestamp int, xRevxSignature string) (*GetOrderFillsResponse, error) {
	if venueOrderID == "" {
		return nil, errors.New("revolutx: venue_order_id is required")
	}
	if !isUUID(venueOrderID) {
		return nil, errors.New("revolutx: venue_order_id must be a valid UUID")
	}
	if xRevxSignature == "" {
		return nil, errors.New("revolutx: X-Revx-Signature is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	r.Headers.Set("X-Revx-Timestamp", strconv.Itoa(int(xRevxTimestamp)))
	if xRevxSignature != "" {
		r.Headers.Set("X-Revx-Signature", xRevxSignature)
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodGet, "orders/fills/"+url.PathEscape(venueOrderID), r)
	if err != nil {
		return nil, err
	}
	var out GetOrderFillsResponse
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// GetHistoricalOrders get historical orders
//
// Docs: https://developer.revolut.com/docs/revolutx/get-historical-orders
func (s *Orders) GetHistoricalOrders(ctx context.Context, xRevxTimestamp int, xRevxSignature string, opts *GetHistoricalOrdersParams) (*HistoricalOrdersPaginatedResponse, error) {
	if xRevxSignature == "" {
		return nil, errors.New("revolutx: X-Revx-Signature is required")
	}
	path := "orders/historical"
	if q := opts.encode().Encode(); q != "" {
		path += "?" + q
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	r.Headers.Set("X-Revx-Timestamp", strconv.Itoa(int(xRevxTimestamp)))
	if xRevxSignature != "" {
		r.Headers.Set("X-Revx-Signature", xRevxSignature)
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodGet, path, r)
	if err != nil {
		return nil, err
	}
	var out HistoricalOrdersPaginatedResponse
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// GetHistoricalOrdersAll iterates every page of GetHistoricalOrders, yielding one Order per
// step. Break out of the loop to stop early.
func (s *Orders) GetHistoricalOrdersAll(ctx context.Context, xRevxTimestamp int, xRevxSignature string, opts *GetHistoricalOrdersParams) iter.Seq2[Order, error] {
	return func(yield func(Order, error) bool) {
		var p GetHistoricalOrdersParams
		if opts != nil {
			p = *opts
		}
		for {
			if err := ctx.Err(); err != nil {
				var zero Order
				yield(zero, err)
				return
			}
			resp, err := s.GetHistoricalOrders(ctx, xRevxTimestamp, xRevxSignature, &p)
			if err != nil {
				var zero Order
				yield(zero, err)
				return
			}
			for _, item := range resp.Data {
				if !yield(item, nil) {
					return
				}
			}
			if resp.Metadata == nil {
				return
			}
			if resp.Metadata.NextCursor == "" {
				return
			}
			nextTok := resp.Metadata.NextCursor
			if nextTok == p.Cursor {
				return
			}
			p.Cursor = nextTok
		}
	}
}

// Get get order by ID
//
// Docs: https://developer.revolut.com/docs/revolutx/get-order
func (s *Orders) Get(ctx context.Context, venueOrderID string, xRevxTimestamp int, xRevxSignature string) (*GetOrderResponse, error) {
	if venueOrderID == "" {
		return nil, errors.New("revolutx: venue_order_id is required")
	}
	if !isUUID(venueOrderID) {
		return nil, errors.New("revolutx: venue_order_id must be a valid UUID")
	}
	if xRevxSignature == "" {
		return nil, errors.New("revolutx: X-Revx-Signature is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	r.Headers.Set("X-Revx-Timestamp", strconv.Itoa(int(xRevxTimestamp)))
	if xRevxSignature != "" {
		r.Headers.Set("X-Revx-Signature", xRevxSignature)
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodGet, "orders/"+url.PathEscape(venueOrderID), r)
	if err != nil {
		return nil, err
	}
	var out GetOrderResponse
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// CancelOrder cancel order by ID
//
// Docs: https://developer.revolut.com/docs/revolutx/cancel-order
func (s *Orders) CancelOrder(ctx context.Context, venueOrderID string, xRevxTimestamp int, xRevxSignature string) error {
	if venueOrderID == "" {
		return errors.New("revolutx: venue_order_id is required")
	}
	if !isUUID(venueOrderID) {
		return errors.New("revolutx: venue_order_id must be a valid UUID")
	}
	if xRevxSignature == "" {
		return errors.New("revolutx: X-Revx-Signature is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	r.Headers.Set("X-Revx-Timestamp", strconv.Itoa(int(xRevxTimestamp)))
	if xRevxSignature != "" {
		r.Headers.Set("X-Revx-Signature", xRevxSignature)
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodDelete, "orders/"+url.PathEscape(venueOrderID), r)
	if err != nil {
		return err
	}
	_ = body
	return nil
}
