// Code generated by revogen. DO NOT EDIT.

package cryptoramp

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"net/url"

	"github.com/greatliontech/revolut-go/internal/transport"
)

// Webhooks groups the Webhooks endpoints.
type Webhooks struct {
	t *transport.Transport
}

// List retrieve a list of webhooks
func (s *Webhooks) List(ctx context.Context, xAPIKey string) ([]Webhook, error) {
	if xAPIKey == "" {
		return nil, errors.New("cryptoramp: X-API-KEY is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xAPIKey != "" {
		r.Headers.Set("X-API-KEY", xAPIKey)
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodGet, "https://ramp-partners.revolut.com/partners/api/1.0/"+"webhooks", r)
	if err != nil {
		return nil, err
	}
	var out []Webhook
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Create create a webhook
func (s *Webhooks) Create(ctx context.Context, xAPIKey string, req WebhookCreateRequest) (*Webhook, error) {
	if xAPIKey == "" {
		return nil, errors.New("cryptoramp: X-API-KEY is required")
	}
	if len(req.Events) == 0 {
		return nil, errors.New("cryptoramp: WebhookCreateRequest.events is required")
	}
	if req.URL == "" {
		return nil, errors.New("cryptoramp: WebhookCreateRequest.url is required")
	}
	r := transport.RawRequest{
		JSONBody: req,
	}
	r.Headers = http.Header{}
	if xAPIKey != "" {
		r.Headers.Set("X-API-KEY", xAPIKey)
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodPost, "https://ramp-partners.revolut.com/partners/api/1.0/"+"webhooks", r)
	if err != nil {
		return nil, err
	}
	var out Webhook
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Get retrieve a webhook
func (s *Webhooks) Get(ctx context.Context, webhookID string, xAPIKey string) (*Webhook, error) {
	if webhookID == "" {
		return nil, errors.New("cryptoramp: webhook_id is required")
	}
	if !isUUID(webhookID) {
		return nil, errors.New("cryptoramp: webhook_id must be a valid UUID")
	}
	if xAPIKey == "" {
		return nil, errors.New("cryptoramp: X-API-KEY is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xAPIKey != "" {
		r.Headers.Set("X-API-KEY", xAPIKey)
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodGet, "https://ramp-partners.revolut.com/partners/api/1.0/"+"webhooks/"+url.PathEscape(webhookID), r)
	if err != nil {
		return nil, err
	}
	var out Webhook
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update update a webhook
func (s *Webhooks) Update(ctx context.Context, webhookID string, xAPIKey string, req WebhookUpdateRequest) (*Webhook, error) {
	if webhookID == "" {
		return nil, errors.New("cryptoramp: webhook_id is required")
	}
	if !isUUID(webhookID) {
		return nil, errors.New("cryptoramp: webhook_id must be a valid UUID")
	}
	if xAPIKey == "" {
		return nil, errors.New("cryptoramp: X-API-KEY is required")
	}
	r := transport.RawRequest{
		JSONBody: req,
	}
	r.Headers = http.Header{}
	if xAPIKey != "" {
		r.Headers.Set("X-API-KEY", xAPIKey)
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodPatch, "https://ramp-partners.revolut.com/partners/api/1.0/"+"webhooks/"+url.PathEscape(webhookID), r)
	if err != nil {
		return nil, err
	}
	var out Webhook
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete delete a webhook
func (s *Webhooks) Delete(ctx context.Context, webhookID string, xAPIKey string) error {
	if webhookID == "" {
		return errors.New("cryptoramp: webhook_id is required")
	}
	if !isUUID(webhookID) {
		return errors.New("cryptoramp: webhook_id must be a valid UUID")
	}
	if xAPIKey == "" {
		return errors.New("cryptoramp: X-API-KEY is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if xAPIKey != "" {
		r.Headers.Set("X-API-KEY", xAPIKey)
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodDelete, "https://ramp-partners.revolut.com/partners/api/1.0/"+"webhooks/"+url.PathEscape(webhookID), r)
	if err != nil {
		return err
	}
	_ = body
	return nil
}
