// Code generated by revogen. DO NOT EDIT.

package merchant

import (
	"context"
	"encoding/json"
	"errors"
	"iter"
	"net/http"
	"net/url"

	"github.com/greatliontech/revolut-go/internal/transport"
)

// Payouts groups the Payouts endpoints.
type Payouts struct {
	t *transport.Transport
}

// GetList retrieve a payout list
//
// Docs: https://developer.revolut.com/docs/merchant/retrieve-payout-list
func (s *Payouts) GetList(ctx context.Context, authorization string, revolutAPIVersion PayoutsRevolutAPIVersion, opts *RetrievePayoutListParams) ([]Payout, error) {
	if authorization == "" {
		return nil, errors.New("merchant: Authorization is required")
	}
	if revolutAPIVersion == "" {
		return nil, errors.New("merchant: Revolut-Api-Version is required")
	}
	path := "api/payouts"
	if q := opts.encode().Encode(); q != "" {
		path += "?" + q
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if revolutAPIVersion != "" {
		r.Headers.Set("Revolut-Api-Version", string(revolutAPIVersion))
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodGet, path, r)
	if err != nil {
		return nil, err
	}
	var out []Payout
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// GetListAll iterates every page of GetList, yielding one Payout per
// step. Break out of the loop to stop early.
func (s *Payouts) GetListAll(ctx context.Context, authorization string, revolutAPIVersion PayoutsRevolutAPIVersion, opts *RetrievePayoutListParams) iter.Seq2[Payout, error] {
	return func(yield func(Payout, error) bool) {
		var p RetrievePayoutListParams
		if opts != nil {
			p = *opts
		}
		for {
			resp, err := s.GetList(ctx, authorization, revolutAPIVersion, &p)
			if err != nil {
				var zero Payout
				yield(zero, err)
				return
			}
			if len(resp) == 0 {
				return
			}
			for _, item := range resp {
				if !yield(item, nil) {
					return
				}
			}
			if p.Limit == 0 || int64(len(resp)) < int64(p.Limit) {
				return
			}
		}
	}
}

// Get retrieve a payout
//
// Docs: https://developer.revolut.com/docs/merchant/retrieve-payout
func (s *Payouts) Get(ctx context.Context, payoutID string, authorization string, revolutAPIVersion PayoutsRevolutAPIVersion) (*Payout, error) {
	if payoutID == "" {
		return nil, errors.New("merchant: payout_id is required")
	}
	if !isUUID(payoutID) {
		return nil, errors.New("merchant: payout_id must be a valid UUID")
	}
	if authorization == "" {
		return nil, errors.New("merchant: Authorization is required")
	}
	if revolutAPIVersion == "" {
		return nil, errors.New("merchant: Revolut-Api-Version is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if revolutAPIVersion != "" {
		r.Headers.Set("Revolut-Api-Version", string(revolutAPIVersion))
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodGet, "api/payouts/"+url.PathEscape(payoutID), r)
	if err != nil {
		return nil, err
	}
	var out Payout
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
