// Code generated by revogen. DO NOT EDIT.

package merchant

import (
	"context"
	"errors"
	"io"
	"net/http"
	"net/url"

	"github.com/greatliontech/revolut-go/internal/transport"
)

// ReportRuns groups the ReportRuns endpoints.
type ReportRuns struct {
	t *transport.Transport
}

// Create create a new report run
//
// Docs: https://developer.revolut.com/docs/merchant/create-report-run
func (s *ReportRuns) Create(ctx context.Context) (*ReportRunDetails, error) {
	var out ReportRunDetails
	if err := s.t.Do(ctx, http.MethodPost, "api/report-runs", nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetDetails retrieve report run details
//
// Docs: https://developer.revolut.com/docs/merchant/retrieve-report-run-details
func (s *ReportRuns) GetDetails(ctx context.Context, reportRunID string) (*ReportRunDetails, error) {
	if reportRunID == "" {
		return nil, errors.New("merchant: report_run_id is required")
	}
	if !isUUID(reportRunID) {
		return nil, errors.New("merchant: report_run_id must be a valid UUID")
	}
	var out ReportRunDetails
	if err := s.t.Do(ctx, http.MethodGet, "api/report-runs/"+url.PathEscape(reportRunID), nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// DownloadReportFile download report file
//
// Docs: https://developer.revolut.com/docs/merchant/download-report-file
func (s *ReportRuns) DownloadReportFile(ctx context.Context, reportRunID string) (io.ReadCloser, error) {
	if reportRunID == "" {
		return nil, errors.New("merchant: report_run_id is required")
	}
	if !isUUID(reportRunID) {
		return nil, errors.New("merchant: report_run_id must be a valid UUID")
	}
	r := transport.RawRequest{
		Accept: "text/csv",
	}
	stream, _, err := s.t.DoRawStream(ctx, http.MethodGet, "api/report-runs/"+url.PathEscape(reportRunID)+"/file", r)
	if err != nil {
		return nil, err
	}
	return stream, nil
}
