// Code generated by revogen. DO NOT EDIT.

package merchant

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"

	"github.com/greatliontech/revolut-go/internal/transport"
)

// Terminals groups the Terminals endpoints.
type Terminals struct {
	t *transport.Transport
}

// GetList retrieve terminal list
//
// Docs: https://developer.revolut.com/docs/merchant/retrieve-terminal-list
func (s *Terminals) GetList(ctx context.Context, authorization string, revolutAPIVersion TerminalsRevolutAPIVersion, opts *RetrieveTerminalListParams) (*TerminalsResponse, error) {
	if authorization == "" {
		return nil, errors.New("merchant: Authorization is required")
	}
	path := "api/terminals"
	if q := opts.encode().Encode(); q != "" {
		path += "?" + q
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if revolutAPIVersion != "" {
		r.Headers.Set("Revolut-Api-Version", string(revolutAPIVersion))
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodGet, path, r)
	if err != nil {
		return nil, err
	}
	var out TerminalsResponse
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
