// Code generated by revogen. DO NOT EDIT.

package merchant

import (
	"context"
	"encoding/json"
	"errors"
	"iter"
	"net/http"
	"net/url"

	"github.com/greatliontech/revolut-go/internal/transport"
)

// Customers groups the Customers endpoints.
type Customers struct {
	t *transport.Transport
}

// GetList retrieve a customer list
//
// Docs: https://developer.revolut.com/docs/merchant/retrieve-customer-list
func (s *Customers) GetList(ctx context.Context, authorization string, revolutAPIVersion CustomersRevolutAPIVersion, opts *RetrieveCustomerListParams) (*CustomersResponse, error) {
	if authorization == "" {
		return nil, errors.New("merchant: Authorization is required")
	}
	if revolutAPIVersion == "" {
		return nil, errors.New("merchant: Revolut-Api-Version is required")
	}
	path := "api/customers"
	if q := opts.encode().Encode(); q != "" {
		path += "?" + q
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if revolutAPIVersion != "" {
		r.Headers.Set("Revolut-Api-Version", string(revolutAPIVersion))
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodGet, path, r)
	if err != nil {
		return nil, err
	}
	var out CustomersResponse
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetListAll iterates every page of GetList, yielding one CustomerSimplified per
// step. Break out of the loop to stop early.
func (s *Customers) GetListAll(ctx context.Context, authorization string, revolutAPIVersion CustomersRevolutAPIVersion, opts *RetrieveCustomerListParams) iter.Seq2[CustomerSimplified, error] {
	return func(yield func(CustomerSimplified, error) bool) {
		var p RetrieveCustomerListParams
		if opts != nil {
			p = *opts
		}
		for {
			resp, err := s.GetList(ctx, authorization, revolutAPIVersion, &p)
			if err != nil {
				var zero CustomerSimplified
				yield(zero, err)
				return
			}
			for _, item := range resp.Customers {
				if !yield(item, nil) {
					return
				}
			}
			if resp.NextPageToken == nil || *resp.NextPageToken == "" {
				return
			}
			p.PageToken = string(*resp.NextPageToken)
		}
	}
}

// Create create a customer
//
// Docs: https://developer.revolut.com/docs/merchant/create-customer
func (s *Customers) Create(ctx context.Context, authorization string, revolutAPIVersion CustomersRevolutAPIVersion, req CustomerCreationV2) (*CustomerCreated, error) {
	if authorization == "" {
		return nil, errors.New("merchant: Authorization is required")
	}
	if revolutAPIVersion == "" {
		return nil, errors.New("merchant: Revolut-Api-Version is required")
	}
	if req.Email == "" {
		return nil, errors.New("merchant: CustomerCreationV2.email is required")
	}
	r := transport.RawRequest{
		JSONBody: req,
	}
	r.Headers = http.Header{}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if revolutAPIVersion != "" {
		r.Headers.Set("Revolut-Api-Version", string(revolutAPIVersion))
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodPost, "api/customers", r)
	if err != nil {
		return nil, err
	}
	var out CustomerCreated
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Get retrieve a customer
//
// Docs: https://developer.revolut.com/docs/merchant/retrieve-customer
func (s *Customers) Get(ctx context.Context, customerID string, authorization string, revolutAPIVersion CustomersRevolutAPIVersion) (*CustomerV3, error) {
	if customerID == "" {
		return nil, errors.New("merchant: customer_id is required")
	}
	if !isUUID(customerID) {
		return nil, errors.New("merchant: customer_id must be a valid UUID")
	}
	if authorization == "" {
		return nil, errors.New("merchant: Authorization is required")
	}
	if revolutAPIVersion == "" {
		return nil, errors.New("merchant: Revolut-Api-Version is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if revolutAPIVersion != "" {
		r.Headers.Set("Revolut-Api-Version", string(revolutAPIVersion))
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodGet, "api/customers/"+url.PathEscape(customerID), r)
	if err != nil {
		return nil, err
	}
	var out CustomerV3
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update update a customer
//
// Docs: https://developer.revolut.com/docs/merchant/update-customer
func (s *Customers) Update(ctx context.Context, customerID string, authorization string, revolutAPIVersion CustomersRevolutAPIVersion, req CustomerUpdateV2) (*CustomerV3, error) {
	if customerID == "" {
		return nil, errors.New("merchant: customer_id is required")
	}
	if !isUUID(customerID) {
		return nil, errors.New("merchant: customer_id must be a valid UUID")
	}
	if authorization == "" {
		return nil, errors.New("merchant: Authorization is required")
	}
	if revolutAPIVersion == "" {
		return nil, errors.New("merchant: Revolut-Api-Version is required")
	}
	r := transport.RawRequest{
		JSONBody: req,
	}
	r.Headers = http.Header{}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if revolutAPIVersion != "" {
		r.Headers.Set("Revolut-Api-Version", string(revolutAPIVersion))
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodPatch, "api/customers/"+url.PathEscape(customerID), r)
	if err != nil {
		return nil, err
	}
	var out CustomerV3
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete delete a customer
//
// Docs: https://developer.revolut.com/docs/merchant/delete-customer
func (s *Customers) Delete(ctx context.Context, customerID string, authorization string, revolutAPIVersion CustomersRevolutAPIVersion) error {
	if customerID == "" {
		return errors.New("merchant: customer_id is required")
	}
	if !isUUID(customerID) {
		return errors.New("merchant: customer_id must be a valid UUID")
	}
	if authorization == "" {
		return errors.New("merchant: Authorization is required")
	}
	if revolutAPIVersion == "" {
		return errors.New("merchant: Revolut-Api-Version is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if revolutAPIVersion != "" {
		r.Headers.Set("Revolut-Api-Version", string(revolutAPIVersion))
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodDelete, "api/customers/"+url.PathEscape(customerID), r)
	if err != nil {
		return err
	}
	_ = body
	return nil
}

// GetPaymentMethodList retrieve payment method list of a customer
//
// Docs: https://developer.revolut.com/docs/merchant/retrieve-payment-method-list
func (s *Customers) GetPaymentMethodList(ctx context.Context, customerID string, authorization string, revolutAPIVersion CustomersRevolutAPIVersion, opts *RetrievePaymentMethodListParams) (*CustomerPaymentMethodsV2, error) {
	if customerID == "" {
		return nil, errors.New("merchant: customer_id is required")
	}
	if !isUUID(customerID) {
		return nil, errors.New("merchant: customer_id must be a valid UUID")
	}
	if authorization == "" {
		return nil, errors.New("merchant: Authorization is required")
	}
	if revolutAPIVersion == "" {
		return nil, errors.New("merchant: Revolut-Api-Version is required")
	}
	path := "api/customers/" + url.PathEscape(customerID) + "/payment-methods"
	if q := opts.encode().Encode(); q != "" {
		path += "?" + q
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if revolutAPIVersion != "" {
		r.Headers.Set("Revolut-Api-Version", string(revolutAPIVersion))
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodGet, path, r)
	if err != nil {
		return nil, err
	}
	var out CustomerPaymentMethodsV2
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetPaymentMethod retrieve a customer's payment method
//
// Docs: https://developer.revolut.com/docs/merchant/retrieve-payment-method
func (s *Customers) GetPaymentMethod(ctx context.Context, customerID string, paymentMethodID string, authorization string, revolutAPIVersion CustomersRevolutAPIVersion) (*PaymentMethodV4, error) {
	if customerID == "" {
		return nil, errors.New("merchant: customer_id is required")
	}
	if !isUUID(customerID) {
		return nil, errors.New("merchant: customer_id must be a valid UUID")
	}
	if paymentMethodID == "" {
		return nil, errors.New("merchant: payment_method_id is required")
	}
	if !isUUID(paymentMethodID) {
		return nil, errors.New("merchant: payment_method_id must be a valid UUID")
	}
	if authorization == "" {
		return nil, errors.New("merchant: Authorization is required")
	}
	if revolutAPIVersion == "" {
		return nil, errors.New("merchant: Revolut-Api-Version is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if revolutAPIVersion != "" {
		r.Headers.Set("Revolut-Api-Version", string(revolutAPIVersion))
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodGet, "api/customers/"+url.PathEscape(customerID)+"/payment-methods/"+url.PathEscape(paymentMethodID), r)
	if err != nil {
		return nil, err
	}
	var out PaymentMethodV4
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdatePaymentMethod update a customer's payment method
//
// Docs: https://developer.revolut.com/docs/merchant/update-payment-method
func (s *Customers) UpdatePaymentMethod(ctx context.Context, customerID string, paymentMethodID string, authorization string, revolutAPIVersion CustomersRevolutAPIVersion, req PaymentMethodUpdate) (*PaymentMethodV4, error) {
	if customerID == "" {
		return nil, errors.New("merchant: customer_id is required")
	}
	if !isUUID(customerID) {
		return nil, errors.New("merchant: customer_id must be a valid UUID")
	}
	if paymentMethodID == "" {
		return nil, errors.New("merchant: payment_method_id is required")
	}
	if !isUUID(paymentMethodID) {
		return nil, errors.New("merchant: payment_method_id must be a valid UUID")
	}
	if authorization == "" {
		return nil, errors.New("merchant: Authorization is required")
	}
	if revolutAPIVersion == "" {
		return nil, errors.New("merchant: Revolut-Api-Version is required")
	}
	r := transport.RawRequest{
		JSONBody: req,
	}
	r.Headers = http.Header{}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if revolutAPIVersion != "" {
		r.Headers.Set("Revolut-Api-Version", string(revolutAPIVersion))
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodPatch, "api/customers/"+url.PathEscape(customerID)+"/payment-methods/"+url.PathEscape(paymentMethodID), r)
	if err != nil {
		return nil, err
	}
	var out PaymentMethodV4
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// DeletePaymentMethod delete a customer's payment method
//
// Docs: https://developer.revolut.com/docs/merchant/delete-payment-method
func (s *Customers) DeletePaymentMethod(ctx context.Context, customerID string, paymentMethodID string, authorization string, revolutAPIVersion CustomersRevolutAPIVersion) error {
	if customerID == "" {
		return errors.New("merchant: customer_id is required")
	}
	if !isUUID(customerID) {
		return errors.New("merchant: customer_id must be a valid UUID")
	}
	if paymentMethodID == "" {
		return errors.New("merchant: payment_method_id is required")
	}
	if !isUUID(paymentMethodID) {
		return errors.New("merchant: payment_method_id must be a valid UUID")
	}
	if authorization == "" {
		return errors.New("merchant: Authorization is required")
	}
	if revolutAPIVersion == "" {
		return errors.New("merchant: Revolut-Api-Version is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if revolutAPIVersion != "" {
		r.Headers.Set("Revolut-Api-Version", string(revolutAPIVersion))
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodDelete, "api/customers/"+url.PathEscape(customerID)+"/payment-methods/"+url.PathEscape(paymentMethodID), r)
	if err != nil {
		return err
	}
	_ = body
	return nil
}
