// Code generated by revogen. DO NOT EDIT.

package merchant

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"net/url"

	"github.com/greatliontech/revolut-go/internal/transport"
)

// Payments groups the Payments endpoints.
type Payments struct {
	t *transport.Transport
}

// GetDetails retrieve payment details
//
// Docs: https://developer.revolut.com/docs/merchant/retrieve-payment-details
func (s *Payments) GetDetails(ctx context.Context, paymentID string, revolutAPIVersion RevolutAPIVersionOptional) (*PaymentRetrievalV2, error) {
	if paymentID == "" {
		return nil, errors.New("merchant: payment_id is required")
	}
	if !isUUID(paymentID) {
		return nil, errors.New("merchant: payment_id must be a valid UUID")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if revolutAPIVersion != "" {
		r.Headers.Set("Revolut-Api-Version", string(revolutAPIVersion))
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodGet, "api/payments/"+url.PathEscape(paymentID), r)
	if err != nil {
		return nil, err
	}
	var out PaymentRetrievalV2
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
