// Code generated by revogen. DO NOT EDIT.

package merchant

import (
	"context"
	"encoding/json"
	"errors"
	"iter"
	"net/http"
	"net/url"

	"github.com/greatliontech/revolut-go/internal/transport"
)

// Disputes groups the Disputes endpoints.
type Disputes struct {
	t *transport.Transport
}

// GetList retrieve a dispute list
//
// Docs: https://developer.revolut.com/docs/merchant/retrieve-dispute-list
func (s *Disputes) GetList(ctx context.Context, authorization string, revolutAPIVersion RevolutAPIVersion, opts *RetrieveDisputeListParams) ([]Dispute, error) {
	if authorization == "" {
		return nil, errors.New("merchant: Authorization is required")
	}
	if revolutAPIVersion == "" {
		return nil, errors.New("merchant: Revolut-Api-Version is required")
	}
	path := "api/disputes"
	if q := opts.encode().Encode(); q != "" {
		path += "?" + q
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if revolutAPIVersion != "" {
		r.Headers.Set("Revolut-Api-Version", string(revolutAPIVersion))
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodGet, path, r)
	if err != nil {
		return nil, err
	}
	var out []Dispute
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// GetListAll iterates every page of GetList, yielding one Dispute per
// step. Break out of the loop to stop early.
func (s *Disputes) GetListAll(ctx context.Context, authorization string, revolutAPIVersion RevolutAPIVersion, opts *RetrieveDisputeListParams) iter.Seq2[Dispute, error] {
	return func(yield func(Dispute, error) bool) {
		var p RetrieveDisputeListParams
		if opts != nil {
			p = *opts
		}
		for {
			resp, err := s.GetList(ctx, authorization, revolutAPIVersion, &p)
			if err != nil {
				var zero Dispute
				yield(zero, err)
				return
			}
			if len(resp) == 0 {
				return
			}
			for _, item := range resp {
				if !yield(item, nil) {
					return
				}
			}
			if p.Limit == 0 || int64(len(resp)) < int64(p.Limit) {
				return
			}
		}
	}
}

// Get retrieve a dispute
//
// Docs: https://developer.revolut.com/docs/merchant/retrieve-dispute
func (s *Disputes) Get(ctx context.Context, disputeID string, authorization string, revolutAPIVersion RevolutAPIVersion) (*Dispute, error) {
	if disputeID == "" {
		return nil, errors.New("merchant: dispute_id is required")
	}
	if !isUUID(disputeID) {
		return nil, errors.New("merchant: dispute_id must be a valid UUID")
	}
	if authorization == "" {
		return nil, errors.New("merchant: Authorization is required")
	}
	if revolutAPIVersion == "" {
		return nil, errors.New("merchant: Revolut-Api-Version is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if revolutAPIVersion != "" {
		r.Headers.Set("Revolut-Api-Version", string(revolutAPIVersion))
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodGet, "api/disputes/"+url.PathEscape(disputeID), r)
	if err != nil {
		return nil, err
	}
	var out Dispute
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// AcceptDispute accept a dispute
//
// Docs: https://developer.revolut.com/docs/merchant/accept-dispute
func (s *Disputes) AcceptDispute(ctx context.Context, disputeID string, authorization string, revolutAPIVersion RevolutAPIVersion) error {
	if disputeID == "" {
		return errors.New("merchant: dispute_id is required")
	}
	if !isUUID(disputeID) {
		return errors.New("merchant: dispute_id must be a valid UUID")
	}
	if authorization == "" {
		return errors.New("merchant: Authorization is required")
	}
	if revolutAPIVersion == "" {
		return errors.New("merchant: Revolut-Api-Version is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if revolutAPIVersion != "" {
		r.Headers.Set("Revolut-Api-Version", string(revolutAPIVersion))
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodPost, "api/disputes/"+url.PathEscape(disputeID)+"/accept", r)
	if err != nil {
		return err
	}
	_ = body
	return nil
}

// ChallengeDispute challenge a dispute
//
// Docs: https://developer.revolut.com/docs/merchant/challenge-dispute
func (s *Disputes) ChallengeDispute(ctx context.Context, disputeID string, authorization string, revolutAPIVersion RevolutAPIVersion, req DisputeChallenge) error {
	if disputeID == "" {
		return errors.New("merchant: dispute_id is required")
	}
	if !isUUID(disputeID) {
		return errors.New("merchant: dispute_id must be a valid UUID")
	}
	if authorization == "" {
		return errors.New("merchant: Authorization is required")
	}
	if revolutAPIVersion == "" {
		return errors.New("merchant: Revolut-Api-Version is required")
	}
	if len(req.Evidences) == 0 {
		return errors.New("merchant: DisputeChallenge.evidences is required")
	}
	if req.Reason == "" {
		return errors.New("merchant: DisputeChallenge.reason is required")
	}
	r := transport.RawRequest{
		JSONBody: req,
	}
	r.Headers = http.Header{}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if revolutAPIVersion != "" {
		r.Headers.Set("Revolut-Api-Version", string(revolutAPIVersion))
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodPost, "api/disputes/"+url.PathEscape(disputeID)+"/challenge", r)
	if err != nil {
		return err
	}
	_ = body
	return nil
}

// UploadDisputeEvidence upload evidence for a dispute
//
// Docs: https://developer.revolut.com/docs/merchant/upload-dispute-evidence
func (s *Disputes) UploadDisputeEvidence(ctx context.Context, disputeID string, authorization string, revolutAPIVersion RevolutAPIVersion, contentType string, req DisputeEvidenceCreation) (*DisputeEvidence, error) {
	if disputeID == "" {
		return nil, errors.New("merchant: dispute_id is required")
	}
	if !isUUID(disputeID) {
		return nil, errors.New("merchant: dispute_id must be a valid UUID")
	}
	if authorization == "" {
		return nil, errors.New("merchant: Authorization is required")
	}
	if revolutAPIVersion == "" {
		return nil, errors.New("merchant: Revolut-Api-Version is required")
	}
	if contentType == "" {
		return nil, errors.New("merchant: Content-Type is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if revolutAPIVersion != "" {
		r.Headers.Set("Revolut-Api-Version", string(revolutAPIVersion))
	}
	if contentType != "" {
		r.Headers.Set("Content-Type", contentType)
	}
	mpBody, mpCT, err := req.encodeMultipart()
	if err != nil {
		return nil, err
	}
	r.RawBody = mpBody
	r.RawContentType = mpCT
	body, _, err := s.t.DoRaw(ctx, http.MethodPost, "api/disputes/"+url.PathEscape(disputeID)+"/evidences", r)
	if err != nil {
		return nil, err
	}
	var out DisputeEvidence
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
