// Code generated by revogen. DO NOT EDIT.

package merchant

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"net/url"

	"github.com/greatliontech/revolut-go/internal/transport"
)

// PaymentIntents groups the PaymentIntents endpoints.
type PaymentIntents struct {
	t *transport.Transport
}

// Create create a payment intent
//
// Create a payment intent to push a payment request to a specific Revolut Terminal device.
//
// This endpoint is used in push payments to Revolut Terminal integration, where a POS system sends payment requests to physical terminal devices. The terminal must be in Pay at Counter mode and assigned to the same location as the order.
//
// **Requirements:**
// - Order must be created with `channel: "pos"` and include a `location_id`
// - Terminal must be online, in `pos` operation mode, and assigned to the same location
// - Amount must match the order amount
//
// **What happens next:**
// - The payment request appears on the Revolut Terminal screen
// - Customer presents their card or device to complete payment
// - You should poll the payment intent status until it reaches a final state (`completed`, `cancelled`, or `failed`)
// - When the payment intent reaches `completed` state, use the returned `payment_id` to retrieve the final payment status
//
// :::info
// For the complete push payments flow, see: [Push payments to Revolut Terminal](https://developer.revolut.com/docs/guides/in-person-payments/revolut-terminal/push-payments).
// :::
//
// Docs: https://developer.revolut.com/docs/merchant/create-payment-intent
func (s *PaymentIntents) Create(ctx context.Context, orderID string, revolutAPIVersion RevolutAPIVersionOptional, req PaymentIntentCreation) (*PaymentIntent, error) {
	if orderID == "" {
		return nil, errors.New("merchant: order_id is required")
	}
	if !isUUID(orderID) {
		return nil, errors.New("merchant: order_id must be a valid UUID")
	}
	if req.Amount == 0 {
		return nil, errors.New("merchant: PaymentIntentCreation.amount is required")
	}
	if req.TerminalID == "" {
		return nil, errors.New("merchant: PaymentIntentCreation.terminal_id is required")
	}
	r := transport.RawRequest{
		JSONBody: req,
	}
	r.Headers = http.Header{}
	if revolutAPIVersion != "" {
		r.Headers.Set("Revolut-Api-Version", string(revolutAPIVersion))
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodPost, "api/orders/"+url.PathEscape(orderID)+"/payment-intents", r)
	if err != nil {
		return nil, err
	}
	var out PaymentIntent
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// Get retrieve a payment intent
//
// Retrieve the current state and details of a payment intent.
//
// This endpoint is used to poll the payment intent status after pushing a payment request to a Revolut Terminal. You should poll this endpoint repeatedly until the payment intent reaches a final state.
//
// **Payment intent states:**
//
// | State | Description |
// |-------|-------------|
// | `pending` | Payment intent created and sent to terminal, customer has not yet started interacting |
// | `processing` | Customer is actively interacting with the terminal (e.g., inserting card, entering PIN) |
// | `completed` | Payment authorisation is complete, response includes a `payment_id` that you should use to [retrieve the final payment status](https://developer.revolut.com/docs/merchant/retrieve-payment-details) |
// | `cancelled` | Payment intent was cancelled (by your system or by the customer on the terminal) |
// | `failed` | Payment intent failed due to technical issues (e.g., timeout, terminal became unavailable) |
//
// :::tip Polling strategy
// - Poll every second while the state is `pending` or `processing`
// - Set a reasonable timeout (e.g., 60 seconds) to handle cases where the customer abandons the payment
// :::
//
// :::info
// For the complete push payments flow, see: [Push payments to Revolut Terminal](https://developer.revolut.com/docs/guides/in-person-payments/revolut-terminal/push-payments).
// :::
//
// Docs: https://developer.revolut.com/docs/merchant/retrieve-payment-intent
func (s *PaymentIntents) Get(ctx context.Context, paymentIntentID string, revolutAPIVersion RevolutAPIVersionOptional) (*PaymentIntent, error) {
	if paymentIntentID == "" {
		return nil, errors.New("merchant: payment_intent_id is required")
	}
	if !isUUID(paymentIntentID) {
		return nil, errors.New("merchant: payment_intent_id must be a valid UUID")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if revolutAPIVersion != "" {
		r.Headers.Set("Revolut-Api-Version", string(revolutAPIVersion))
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodGet, "api/payment-intents/"+url.PathEscape(paymentIntentID), r)
	if err != nil {
		return nil, err
	}
	var out PaymentIntent
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// CancelPaymentIntent cancel a payment intent
//
// Cancel a payment intent while it's still in `pending` state, before the customer has completed the payment.
//
// This is useful if the customer changes their mind or if there's an issue with the order before payment is completed.
//
// :::caution
// **Requirements:**
// - Payment intent must be in `pending` state
// - Cannot cancel payment intents that are already `completed`, `cancelled`, or `failed`
// :::
//
// :::info
// For the complete push payments flow, see: [Push payments to Revolut Terminal](https://developer.revolut.com/docs/guides/in-person-payments/revolut-terminal/push-payments).
// :::
//
// Docs: https://developer.revolut.com/docs/merchant/cancel-payment-intent
func (s *PaymentIntents) CancelPaymentIntent(ctx context.Context, paymentIntentID string, revolutAPIVersion RevolutAPIVersionOptional) (*PaymentIntent, error) {
	if paymentIntentID == "" {
		return nil, errors.New("merchant: payment_intent_id is required")
	}
	if !isUUID(paymentIntentID) {
		return nil, errors.New("merchant: payment_intent_id must be a valid UUID")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if revolutAPIVersion != "" {
		r.Headers.Set("Revolut-Api-Version", string(revolutAPIVersion))
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodPost, "api/payment-intents/"+url.PathEscape(paymentIntentID)+"/cancel", r)
	if err != nil {
		return nil, err
	}
	var out PaymentIntent
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}
