// Code generated by revogen. DO NOT EDIT.

package merchant

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"net/url"

	"github.com/greatliontech/revolut-go/internal/transport"
)

// PaymentIntents groups the PaymentIntents endpoints.
type PaymentIntents struct {
	t *transport.Transport
}

// Create create a payment intent
//
// Docs: https://developer.revolut.com/docs/merchant/create-payment-intent
func (s *PaymentIntents) Create(ctx context.Context, orderID string, authorization string, revolutAPIVersion RevolutAPIVersionOptional, req PaymentIntentCreation) (*PaymentIntent, error) {
	if orderID == "" {
		return nil, errors.New("merchant: order_id is required")
	}
	if !isUUID(orderID) {
		return nil, errors.New("merchant: order_id must be a valid UUID")
	}
	if authorization == "" {
		return nil, errors.New("merchant: Authorization is required")
	}
	if req.Amount == 0 {
		return nil, errors.New("merchant: PaymentIntentCreation.amount is required")
	}
	if req.TerminalID == "" {
		return nil, errors.New("merchant: PaymentIntentCreation.terminal_id is required")
	}
	r := transport.RawRequest{
		JSONBody: req,
	}
	r.Headers = http.Header{}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if revolutAPIVersion != "" {
		r.Headers.Set("Revolut-Api-Version", string(revolutAPIVersion))
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodPost, "api/orders/"+url.PathEscape(orderID)+"/payment-intents", r)
	if err != nil {
		return nil, err
	}
	var out PaymentIntent
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Get retrieve a payment intent
//
// Docs: https://developer.revolut.com/docs/merchant/retrieve-payment-intent
func (s *PaymentIntents) Get(ctx context.Context, paymentIntentID string, authorization string, revolutAPIVersion RevolutAPIVersionOptional) (*PaymentIntent, error) {
	if paymentIntentID == "" {
		return nil, errors.New("merchant: payment_intent_id is required")
	}
	if !isUUID(paymentIntentID) {
		return nil, errors.New("merchant: payment_intent_id must be a valid UUID")
	}
	if authorization == "" {
		return nil, errors.New("merchant: Authorization is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if revolutAPIVersion != "" {
		r.Headers.Set("Revolut-Api-Version", string(revolutAPIVersion))
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodGet, "api/payment-intents/"+url.PathEscape(paymentIntentID), r)
	if err != nil {
		return nil, err
	}
	var out PaymentIntent
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// CancelPaymentIntent cancel a payment intent
//
// Docs: https://developer.revolut.com/docs/merchant/cancel-payment-intent
func (s *PaymentIntents) CancelPaymentIntent(ctx context.Context, paymentIntentID string, authorization string, revolutAPIVersion RevolutAPIVersionOptional) (*PaymentIntent, error) {
	if paymentIntentID == "" {
		return nil, errors.New("merchant: payment_intent_id is required")
	}
	if !isUUID(paymentIntentID) {
		return nil, errors.New("merchant: payment_intent_id must be a valid UUID")
	}
	if authorization == "" {
		return nil, errors.New("merchant: Authorization is required")
	}
	r := transport.RawRequest{}
	r.Headers = http.Header{}
	if authorization != "" {
		r.Headers.Set("Authorization", authorization)
	}
	if revolutAPIVersion != "" {
		r.Headers.Set("Revolut-Api-Version", string(revolutAPIVersion))
	}
	body, _, err := s.t.DoRaw(ctx, http.MethodPost, "api/payment-intents/"+url.PathEscape(paymentIntentID)+"/cancel", r)
	if err != nil {
		return nil, err
	}
	var out PaymentIntent
	if err := json.Unmarshal(body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
